### ISSUE TITLE
Continue/Break statement code error

### ISSUE THREAD

**Issue by GoldBranches** [mu-editor/mu#1006]
I am a Mu editor and reporting a possible bug or sample code error. After making a few corrections but not being able to satisfy all, I decided to share.

* What you were trying to do: I was trying to copy some sample code
* What steps you took to make this happen: I manually typed the code
* What you expected to happen: a successful run (continuing the code until the correct input (steve) caused it to break)
* What actually happened: i typed in steve but it kept returning "who are you?"
* Why this difference is problematic: it's not working...is this part of the tutorial or am i typing something wrong? is the sample code wrong?
* Technical details: OS Mojave 10.14.6, Mu editor is Alpha 10.1.0

Thank you, here is what I wrote and the errors in brackets.

while True: 
    print('who are you?')
    name = input()
    if name != 'steve':
        continue
        print('hello, what is the password?')
        password = input()
        if password == 'mü':
            break
            print('access granted')

All of the indentation seems to be correct so I am not sure why typing 'steve' doesn't lead to the next print of 'hello, what is the password?'

**Comment by ZanderBrown** [comment]
Two things:
1. This isn't a python help forum, this is for problems with Mu itself
2. You didn't place your code in a "codeblock" so we can't see your indentation making it hard to help
