### ISSUE TITLE
Please add support for the Arduino Nano 33 IoT board (VID/PID)

### ISSUE THREAD

**Issue by derhexenmeister** [mu-editor/mu#1019]
I'm using Mu 1.0.3 to develop CircuitPython on an Arduino Nano 33 IoT board on a Windows 10 machine. This board is in the list of supported boards here, so others may run into this: https://circuitpython.org/downloads

I found that I had to add a line to C:\Program Files\Mu\pkgs\mu\modes\adafruit.py to get it to recognize the board. " (0x2341, 0x8057), # Arduino Nano 33 IoT". When I looked in the repo, it looks like this structure has been moved to a different file mu/modes/circuitpython.py.

This VID/PID can be verified here https://github.com/arduino/ArduinoCore-samd/blob/master/boards.txt

Anyways after this change it works great. Previously I had used Mu with CircuitPython on a Teensy 4 board and can confirm that it's support without any edits.

**Comment by dybber** [comment]
Added, thanks for reporting @derhexenmeister!
