### ISSUE TITLE
files explorer

### ISSUE THREAD

**Issue by JLFra** [mu-editor/mu#1022]
Hello, Could you add the possiblity to create a Folder and double clic in a folder to go into it to put a file.
How can I add in the third party package the possibilité to add 
https://github.com/micropython/micropython-lib/tree/master/umqtt.simple/umqtt
Thanks a lot.
Your sincerely.
Julien

**Comment by dybber** [comment]
Hi Julien

The request regarding improved Files explorer is already suggested at #996. Adding a third-party package for MicroPython is not a Mu problem, and in general you should ask such questions on the MicroPython forums. I will thus close this issue. However, as a quick note here's how to install libraries on MicroPython:

First make sure the device is connected to the internet, then execute:
```
import upip
upip.install("micropython-umqtt.simple")
```
