### ISSUE TITLE
REPL not working

### ISSUE THREAD

**Issue by 1104045928** [mu-editor/mu#1023]
I install the mu-editor with python 3.6.9 on Ubuntu system.
After I installed it, I find that I cannot type anything in REPL!
And nothing is shown in the interactive shell. It is totally blank.
![Screenshot from 2020-04-07 01-12-56](https://user-images.githubusercontent.com/37465048/78632409-f32f8400-786c-11ea-9b34-70652c1ffcf4.png)

**Comment by carlosperate** [comment]
Thank you for the report @1104045928.

Could you send us a copy of the Mu log? that would help us identify the issue.
If you could open the Mu editor, then open the REPL (as shown in this creenshot), and the copy the log from the settings that would help us find the issue at the end of the log.

**Comment by 1104045928** [comment]
Sorry I didn't get anything. I didn't send report to you, I think.

Carlos Pereira Atencio <notifications@github.com>于2020年8月3日 周一下午1:38写道：

**Comment by carlosperate** [comment]
Sorry, I'm not sure I quite understood. Do you still have this issue with the Mu editor? If you are, would you be able to send us the log?

**Comment by 1104045928** [comment]
No, thank you!

Carlos Pereira Atencio <notifications@github.com>于2020年8月3日 周一下午4:17写道：

**Comment by carlosperate** [comment]
Okay, thanks for the quick reply! I'll close the issue then

**Comment by Moey27** [comment]
hey I have the same problem

**Comment by Moey27** [comment]
@carlosperate  
Ive got the same problm, the blank Repl and cant type anything. How'd you fix it?

**Comment by carlosperate** [comment]
Hi @Moey27,

As this issue is close, could you open a new one indicating what issue you are encountering, which version of Mu you are runnning, what mode is selected, the log etc? The new issue template indicates all the things that will help us diagnose the issue.
