### ISSUE TITLE
I could not launch Mu

### ISSUE THREAD

**Issue by mcmucyo** [mu-editor/mu#1024]
hello, after download and install mu-editor_1.0.3 could not launch my OS windows 7 pack 1

**Comment by dybber** [comment]
Hi @mcmucyo, I'm sorry you've had trouble, and we haven't replied to you before now. Did you get Mu to run?

**Comment by carlosperate** [comment]
I'll close this issue due to inactivity, and not having enough information to replicate.

@mcmucyo if you are still experiencing this problem please reopen, thanks!
