### ISSUE TITLE
macOS Catalina Dark Theme doesn't change text color

### ISSUE THREAD

**Issue by DIYglenn** [mu-editor/mu#1027]
It seems like there's an issue with macOS Catalina and Mu 1.1.0 alpha 2 with dark themes. 
Text is black and therefore unreadable.

<img width="1552" alt="Skjermbilde 2020-04-17 kl  20 26 42" src="https://user-images.githubusercontent.com/10504432/79602214-5c738a80-80ea-11ea-9bb1-015dcd487c74.png">

**Comment by ntoll** [comment]
@DIYglenn this issue was fixed in master a few weeks ago and will be in the next alpha release: https://madewith.mu/mu/releases/2020/01/26/mu-1-0-3.html
