### ISSUE TITLE
Added to winget packages

### ISSUE THREAD

**Issue by richardjharding** [mu-editor/mu#1049]
I took the liberty of adding mu editor to the new winget package list - https://github.com/microsoft/winget-pkgs

What documentation should I update to show the new windows install option?

**Comment by carlosperate** [comment]
Great, thanks @richardjharding !

**Comment by carlosperate** [comment]
Thanks again @richardjharding!
As this is all done I'll close this issue. I've also created https://github.com/mu-editor/mu/issues/1141 to update it on the next release.
