### ISSUE TITLE
Ensure 1.1 build of Mu works with Apple's signing / application verification process.

### ISSUE THREAD

**Issue by ntoll** [mu-editor/mu#1069]
What the issue says. We're an outlier so we need to ensure all our processes are in place to make this as smooth as possible. Possibly reach out to folks at Apple to ensure we're doing the right sorts of things from the get go.

**Comment by carlosperate** [comment]
We should keep an eye on this: https://github.com/beeware/briefcase/issues/365

I've also seen this article recommended in the PyInstaller tracker: https://nativeconnect.app/blog/mac-app-notarization-from-the-command-line/

**Comment by carlosperate** [comment]
As this is already covered in https://github.com/mu-editor/mu/issues/940 I'll close this issue to keep thing tidy.
