### ISSUE TITLE
Importing openpyxl in mu 

### ISSUE THREAD

**Issue by annieacres** [mu-editor/mu#1084]
![image](https://user-images.githubusercontent.com/69018287/89097255-42c62c80-d3d5-11ea-87f4-373a53491c74.png)

**Comment by annieacres** [comment]
Hi, 

I have been trying to import the openpyxl module in python on my macOS catalina 10.15.6. I have successfully used pip install openpyxl in the terminal, but when I come to use >>>import openpyxl in python an error message appears saying 'openpyxl' is not defined. I have also looked through the modules in mu and openpxyl does not seem to be there. 

I'd be very grateful to receive some help!

**Comment by carlosperate** [comment]
Hi @annieacres,

Mu runs it's own isolated copy of Python and packages, so it is not able to access packages installed using pip in a normal terminal.
If you install the latest alpha version of Mu there is a new option in the settings that allows you install 3rd party packages inside this isolated environment:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/4189262/88465409-be4a4a00-ceba-11ea-86b2-c4e82eda75b1.png">

**Comment by carlosperate** [comment]
Hi @annieacres 
As it's been a while without a response I'll close this issue as resolved, but please feel free to reopen if you had any issues installing packages inside Mu.

I've also created this ticket to ensure we remember to document this feature for the next release: https://github.com/mu-editor/mu/issues/1107
