### ISSUE TITLE
Save a File crashes #635

### ISSUE THREAD

**Issue by standera** [mu-editor/mu#1092]
Two years ago I reported a problem with the Mu editor always crashing while saving a file (see the issue #635). Today I downloaded end installed the alpha version named "mu-editor_1.1.0-alpha.2" for Windows. The problem still persist! No way how to save a file.

**Comment by carlosperate** [comment]
Thanks for letting us know @standera, as this is a continuation of #635 I'll close this ticket and continue the conversation there.
