### ISSUE TITLE
Docs: Third Party Packages

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#1107]
Logging this here as a "todo".
When the next version of Mu is ready for release we need to add a tutorial in the docs about installing third party packages.

<img width="836" alt="image" src="https://user-images.githubusercontent.com/4189262/88465409-be4a4a00-ceba-11ea-86b2-c4e82eda75b1.png">

**Comment by carlosperate** [comment]
The Automate The Boring Stuff with Python had to add this to the appendix: https://automatetheboringstuff.com/2e/appendixa/

**Comment by carlosperate** [comment]
@ntoll there is already a PR from the great @martinohanlon in https://github.com/mu-editor/mu-editor.github.io/pull/51

**Comment by martinohanlon** [comment]
Thesw instructions should still be relevant. I don't think anything has changed since I created them.

**Comment by carlosperate** [comment]
PR https://github.com/mu-editor/mu-editor.github.io/pull/51 has been merged, thanks @ntoll! 🎉 
And @martinohanlon thank you for submitting the PR!
