### ISSUE TITLE
Only show administration tabs relevant for the current mode

### ISSUE THREAD

**Issue by dybber** [mu-editor/mu#1125]
To simplify the administration panel, I suggest that only tabs relevant for the current mode are shown. We currently do this for the ESP Firmware flasher, but might also be relevant to do for:

 - micro:bit tab only shown in micro:bit mode
 - Python3 Environment + Third Party Packages, only in Python 3 and Web mode

At least that's my suggestions, but I'm not sure if that would introduce any problems to hide them? In the future when more and more modes are added it could be come unwieldy.

**Comment by tjguk** [comment]
I'm broadly in agreement, but can we hold off on this for now, please? I'm juggling with enough changes to the admin panel as it is for the venv stuff

**Comment by dybber** [comment]
Okay, no problem!
