### ISSUE TITLE
Color Syntax Highlighting in 1.1.0

### ISSUE THREAD

**Issue by dianarwang** [mu-editor/mu#1133]
Right now as I am using 1.1.0.alpha.2, there is no color syntax highlighting. Everything is black. How could I obtain color syntax highlighting?

**Comment by carlosperate** [comment]
Are you using macOS Catalina? Try version 1.0.3, that version should have fixed the colour syntax issue.

I'll close this as resolves, but please do reopen it if that didn't work.
