### ISSUE TITLE
The compatibility of micropython pyboard

### ISSUE THREAD

**Issue by CaptainJackey** [mu-editor/mu#1142]
Why Mu still not compatible with micropython (pyBoard) ? Will fix it soon?

**Comment by dybber** [comment]
Hi @CaptainJackey 
Thank you for the reminder, there's already a pull request at #650, which I've promised to look at. I will take a look this week and see if we can get it in a state where we can merge it.

**Comment by CaptainJackey** [comment]
Great, waiting for your good news!!

**Comment by dybber** [comment]
Seems like just some very small changes are necessary, to get it running and then we can merge it into Mu. See https://github.com/kyoungmeyer/mu/pull/1

**Comment by CaptainJackey** [comment]
@dybber Already add to the latest ALPHA  version?

**Comment by dybber** [comment]
Hi @CaptainJackey, you can try it through the most recent development build: http://mu-builds.s3-website.eu-west-2.amazonaws.com/?prefix=

**Comment by CaptainJackey** [comment]
> Hi @CaptainJackey, you can try it through the most recent development build: http://mu-builds.s3-website.eu-west-2.amazonaws.com/?prefix=

Love you so much!
