### ISSUE TITLE
Dark theme patch needs to check for macOS Catalina

### ISSUE THREAD

**Issue by frenoy** [mu-editor/mu#1152]
**Issue:**
Dark mode doesn't seem to be working as intended on macOS Catalina (10.15.7). I believe this was first observed on Mojave (#552) and recently for Catalina (#1027).

![Screenshot 2020-11-23 at 21 37 54](https://user-images.githubusercontent.com/33038741/100018983-3d05b400-2dd5-11eb-8193-f99d49eb6299.png)

![Screenshot 2020-11-23 at 21 38 02](https://user-images.githubusercontent.com/33038741/100018991-41ca6800-2dd5-11eb-9b19-9eb8ff96cf2a.png)

**Fix:**
A temporary fix (#567) was used to resolve this for Mojave which checks the OS version (Darwin-18.) This needs to be extended to check for Catalina (Darwin-19.). I don't have access to a machine running Big Sur to check the behaviour there.

The following screenshots were taken after updating line 43 of themes.py (local copy) from:

`return platform.platform().startswith("Darwin-18.")` 

to:

`return platform.platform().startswith("Darwin-18.") or platform.platform().startswith("Darwin-19.")`

![Screenshot 2020-11-23 at 21 38 31](https://user-images.githubusercontent.com/33038741/100019355-cb7a3580-2dd5-11eb-997a-a5a4e736bc43.png)

![Screenshot 2020-11-23 at 21 38 39](https://user-images.githubusercontent.com/33038741/100019365-cf0dbc80-2dd5-11eb-8f80-84f71963fbce.png)

P.S. Thank you for the great work! Please accept my apologies if I haven't followed proper etiquette - I'm pretty new to software development.

**Comment by carlosperate** [comment]
Thanks for the report @frenoy, have you tried the v1.0.3 release? I think this issue was solved in that release.

**Comment by frenoy** [comment]
@carlosperate Thanks for responding. I was using v1.1.0 alpha.2 which I thought was the latest. Just installed v1.0.3 and I can confirm that the issue doesn't appear there.

Closing this now.
