### ISSUE TITLE
Null ine in csv file

### ISSUE THREAD

**Issue by JLFra** [mu-editor/mu#1182]
I have openned the csv file in data_capture after using the plotter. But there is a Null line inbetween each data line? A don"t understand this null line?

**Comment by tjguk** [comment]
Looks like looks like `remove_plotter` in `modes/base.py` opens its output file without `newline=''`

**Comment by ntoll** [comment]
Hmm... should a CSV file have `newline=""` set..? I assume this is a Windows newline related thing..? (Sorry about that.)

**Comment by tjguk** [comment]
Don't think it's Windows-specific. (Although it might be)

https://docs.python.org/3/library/csv.html#id3

**Comment by JLFra** [comment]
So did you found a solution? When we creat a csv file in micropython, it works perfectly? So why do you add a newline when you create the csv file? thanks to help
