### ISSUE TITLE
local-scripts directory for dev tools

### ISSUE THREAD

**Issue by tjguk** [mu-editor/mu#1187]
I typically have a few scripts kicking around to make dev more productive. But they'll be Windows-specific or even me-specific. I suggest that we add a `local-scripts` directory which is versioned but whose contents are ignored.

**Comment by dybber** [comment]
I think you should just add `local-scripts` to the .gitignore file (and commit that). You can't add an empty directory to a Git repository.

**Comment by tjguk** [comment]
For completeness, I've just done this in the context of work for #1358
