### ISSUE TITLE
Hello, I have an m5stack device, are you going to support this type of device?

### ISSUE THREAD

**Issue by fraramon** [mu-editor/mu#1215]
You have to put the device in (APP mode), after installing MU go to the file editor and open the folder C: \ Users % user \ AppData \ Local \ Mu \ Paqs \ mu \ modes and open the esp.py file . Find the valid_boards block in the file and add one more line.

```
valid_boards = [
# VID, PID
(0x1A86, 0x7523), # HL-340
(0x10C4, 0xEA60), # CP210x
(0x0403, 0x6001), # CH552
(0x0403, 0x6015), # Sparkfun ESP32 VID, PID
]

```

**Comment by dybber** [comment]
Hi @fraramon, yes, it's actually already added to Mu a year ago, but we haven't been able to release a new version since then due to packaging issues, that we had to get resolved. We hope to do a beta release soon with all the new additions. I'm closing this.

**Comment by fraramon** [comment]
Hello @dybber,
Ok, thank you very much...
