### ISSUE TITLE
Find uses regex mode by default

### ISSUE THREAD

**Issue by devdanzin** [mu-editor/mu#1222]
It seems we search using regex syntax and I can't find anything to suggest it's on purpose. Unclear we'd want to change it now as some users might be depending on this behaviour. To reproduce:

1. Open Mu, paste the code below;
```python
for line in open('test.txt', 'r'):
    print(line)
```
2. Hit `Ctrl+F` and search for `t.` (tee dot);
3. If the bug is real, it should highlight `te`, `t.`, `t'` and `t(` each time you hit `Crtl+F` then `Enter`.

Sending a trivial PR as soon as we agree this should change. Or a different PR with just a test to ensure we don't change it by accident.

**Comment by ntoll** [comment]
OK... given our users are supposed to be beginners, the thought of introducing them to regex feels a bit like schadenfreude. I concur that we should just match by plan text and not regex pattern. :+1:
