### ISSUE TITLE
Cannot run under macOS Big Sur

### ISSUE THREAD

**Issue by mattpackwood** [mu-editor/mu#1232]
Error when trying to run in Big Sur v11.1

Error is: `“mu-editor” can’t be opened because Apple cannot check it for malicious software.`

<img width="279" alt="image" src="https://user-images.githubusercontent.com/1097448/104076433-131d1b00-51e4-11eb-9754-86e1f80cab69.png">

**Comment by ajs256** [comment]
Right-click ➡️ Open ➡️ Open Anyway (or similar) ➡️ Enter your password

It's because the developers are a small team and can't afford Apple's $99/yr dev licenses.

**Comment by filipejsbrandao** [comment]
If you click Ok it will close the message and Mu won't open. Then if you go to System Preferences, under Security & Privacy > General tab you can open the app.

**Comment by mattpackwood** [comment]
I tried "Command - Click" to get the "Open anyway", selected that, the app appears in the Task Bar, but I have to Force Close it as it does not do anything...

**Comment by ajs256** [comment]
Then you're probably running into #1147. Take a look at my instructions in https://github.com/mu-editor/mu/issues/1147#issuecomment-731609561 to build from source.

**Comment by ajs256** [comment]
Actually, try [the alpha version](https://github.com/mu-editor/mu/releases/tag/1.1.0-alpha.2) first.

**Comment by filipejsbrandao** [comment]
It worked! @ajs256 THANKS!!

**Comment by dybber** [comment]
This is actually a duplicate of #940, as it's an old issue we also had with Catalina. It will be fixed when #940 is fixed, so I'm closing this. The fix would be part of the next beta release.
