### ISSUE TITLE
Update homebrew cask for 1.1 release

### ISSUE THREAD

**Issue by dybber** [mu-editor/mu#1255]
There's a homebrew cask for Mu editor, which we should update when we release the next version of Mu

More details in Carlos comment here:
https://github.com/mu-editor/mu/issues/1147#issuecomment-767566801

Here's the file that needs to be updated:
https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/mu-editor.rb

**Comment by carlosperate** [comment]
This has been done already in https://github.com/Homebrew/homebrew-cask/commit/cbb6eaf072023701089e9a027fbf549acc5a84b2.
