### ISSUE TITLE
Mu creates directories in my home

### ISSUE THREAD

**Issue by deshipu** [mu-editor/mu#126]
Every time I start Mu, it creates a directory called "python" in my home directory. Not only is this extremely annoying, but it also took me some time to figure out which application is responsible for this, as the name is completely unrelated to Mu.

If it needs a configuration directory, I would suggest using ``~/.config/mu`` by default (or even better, follow the xdg standard for configuration directories).

**Comment by ntoll** [comment]
Hi @deshipu!

Mu *does* use the standard location for configuration. The `python` directory is for your source code. The feedback I got from Carrie Anne was that kids (and teachers) wanted a single standard place for their code on all the computers they used. Mu, by default, checks the expected `~/python` directory for loading and saving. 

How about I add a configuration option for default source code directory..? If you're `1337` enough to get annoyed by the `python` directory you'd certainly be `1337` enough to read the docs and update the settings in the very simple JSON file that Mu uses. ;-)

**Comment by deshipu** [comment]
Can you also make it so that if it's set to "", no directories are created at all?

**Comment by deshipu** [comment]
By the way, not sure if "python" is a good default name, you can get conflicts with other python-related tools that had a similar idea...

**Comment by ntoll** [comment]
Upon reflection it should be something like `mu_code` - it names the application *and* tells you what's in it.

**Comment by deshipu** [comment]
That sounds great, thank you. Sorry for complaining, but I figured that I will tell you, and you can ignore it if there are more pressing things to work on.

**Comment by carlosperate** [comment]
I was thinking about this as well a few days ago when reading https://github.com/ntoll/mu/issues/86.
Having the option in the config file would be a good alternative to be able to configure this option if required, but not having to worry about it.

**Comment by ZanderBrown** [comment]
as templates and project types are being added a `Mu Projects` or `Mu Workspace` folder would probably be better than a `python` folder, although we do need to be careful not to form a directory structure of too much complexity the 'stick everything in one folder' approach may not be the best

**Comment by tibs** [comment]
I'm working on changing the name to mu_code, which seems simple but fairly self-explanatory.

**Comment by deshipu** [comment]
I would still love to not have it at the top level of my home directory.

**Comment by carlosperate** [comment]
For that we will add a new entry to the settings file to select the project folder location. The change @tibs is mentioning will only modify the mane of the folder itself.

**Comment by ntoll** [comment]
@deshipu Having it in the top level of your home directory is precisely where teachers and students have told us they want to find it! ;-)

Of course, you should be able to override it as per #86.

**Comment by deshipu** [comment]
I don't think #156 fixes the original issue reported here.
