### ISSUE TITLE
Project versioning mismatch

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#1292]
The GH releases use semver:
- https://github.com/mu-editor/mu/releases/tag/1.1.0-beta.1
- https://github.com/mu-editor/mu/releases/tag/1.1.0-alpha.2

The Python package uses something that is not semver (`1.1.0-beta.1`), is not a [PEP 440](https://www.python.org/dev/peps/pep-0440/) beta release  (`1.1.0b1`/`1.1.0beta1`), doesn't quite fit PEP 440 post release format (`1.1.0.postRelease1`), and probably matches a "development version of a post release" (`X.Y.postN.devM`):
https://github.com/mu-editor/mu/blob/26abb94b309a48aa550524de832010a07b09ace8/mu/__init__.py#L9

The PyPI version ends up being correctly formatted as PEP 440. Does PyPI automatically correct it?
For example, with PyPI version `1.0.0rc1`:
- https://pypi.org/project/mu-editor/1.0.0rc1/  <-- PEP 440
- https://github.com/mu-editor/mu/releases/tag/v1.0.0.rc.1   <-- Semver
- https://github.com/mu-editor/mu/blob/v1.0.0.rc.1/setup.py#L36  <-- Semver
    - https://github.com/mu-editor/mu/blob/v1.0.0.rc.1/mu/__init__.py

The Windows installer actually ends up using PEP 440 format correctly, although I'm not sure how it does this @tmontes?
The resulting file name is `Mu Editor 1.1.0b1.msi`.

@ntoll do you have a specific format you'd like to consolidate? This can be important if in the future we need to store and compare the Mu version for installation upgrades.

**Comment by tmontes** [comment]
> The Windows installer actually ends up using PEP 440 format correctly, although I'm not sure how it does this @tmontes?
> The resulting file name is `Mu Editor 1.1.0b1.msi`.

There are two different things at play, with Windows MSI packaging:

* One is common to all packaging: getting the PEP 440 version. This is done by extracting the version from the metadata of a wheel that `pup` produces from its "source" (see https://github.com/mu-editor/pup/blob/master/src/pup/plugins/metadata.py#L67). That's what you get in the name of the MSI file as well as in the name of the installed product under Windows Programs and Features.
* The other is MSI specific: its version format is more limited than PEP 440's. For example the `b1` suffix is not supported and the resulting installed version is actually `1.1.0` under Windows Programs and Features. `pup` issues a warning about that (see https://github.com/mu-editor/pup/blob/master/src/pup/plugins/win/create_msi.py#L190).
