### ISSUE TITLE
Wrong link in splash screen

### ISSUE THREAD

**Issue by ajs256** [mu-editor/mu#1325]
_bug report template removed because it doesn't matter for this issue_

The new splash screen added in https://github.com/mu-editor/mu/commit/75b167bc21a3bea98c9f025cc241f46e0811f68d shows [`codewithmu.com`](https://codewithmu.com) as the website. I believe [`codewith.mu`](https://codewith.mu) is the correct URL.

**Comment by carlosperate** [comment]
Great catch, thanks @ajs256!

@ntoll assigning to you as maybe this is something we'll need to ask Steve?

**Comment by ntoll** [comment]
Yeah... one for @hawkz

**Comment by ntoll** [comment]
Also, this week's Eagle eyes of code award goes to @ajs256 :eagle: :eyes:  :1st_place_medal:

**Comment by carlosperate** [comment]
This has been fixed in 4c14d239abec9593c8950e591f8f7ce48273d96a 🎉 
Thanks @hawkz!
