### ISSUE TITLE
Crash Report - FEDORA LİNUX KDE Virtual Environment not working after installation for mu-editor

### ISSUE THREAD

**Issue by blalyasar** [mu-editor/mu#1424]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.3
Locale: en_GB
Platform: Linux 5.11.10-200.fc33.x86_64 #1 SMP Thu Mar 25 16:51:31 UTC 2021 x86_64

```
Traceback (most recent call last):
  File "/home/xxx/.VirtualMuEditor/lib64/python3.8/site-packages/mu/app.py", line 162, in run
    raise ex
  File "/home/xxx/.VirtualMuEditor/lib64/python3.8/site-packages/mu/app.py", line 149, in run
    venv.ensure_and_create(self.display_text)
  File "/home/xxx/.VirtualMuEditor/lib64/python3.8/site-packages/mu/virtual_environment.py", line 459, in ensure_and_create
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Unable to create a working virtual environment.

```

**Comment by blalyasar** [comment]
I am effort for this problem solve : -
config.py -> line:9 ->
VENV_NAME = "mu_venv"

Read the doc not writed venv name..
This important case pls. write venv name website

**Comment by blalyasar** [comment]
yesterday I am delete .cache file. both local and  venv.
today
İt is amazing. Problem solved . I dont now how solved. 
Now: 
pip version 20.2.2
python verison 3.8.8
 pip install mu-editor==1.1.0b3
and
mu-editor
run.
thanks for reply

**Comment by ntoll** [comment]
Well done..! :tada:
