### ISSUE TITLE
Problem with opening the Mu editor

### ISSUE THREAD

**Issue by katarzynaozik** [mu-editor/mu#1449]
I have problem with running the new version of Editor Mu under Win10. I have uninstalled the previous version, and install the new one Mu-Editor-Win64-1.1.0b3.msi and it does not start. What can I do? 
Maybe there is conflict with previous version which was installed for all users (I have unistalled it!)- this one is only for one user.

There is no error message on the screen.

**Comment by carlosperate** [comment]
Hi @katarzynaozik, thanks for the report!

Hopefully there shoudn't be any conflict with previously installed editors, but we will need the log file to have a better look.

Can you attempt to one  the Mu editor, and immediately after it crashes send us the log?
It should be located in `%LOCALAPPDATA%\python\mu\Logs`

**Comment by katarzynaozik** [comment]
But I do not have the folder named **python** in localization C:\Users\katarzyna\AppData\Local.

I also tried to install in new Win account and it works fine. So there is something wrong with my account.

**Comment by carlosperate** [comment]
Thanks for the update @katarzynaozik. So with a new user account Mu works fine, but with the old one (possibly named `katarzyna`) it has issues, is that right?

In the account with issues, how did the problem manifest? When trying to open the Mu editor, did something opened at all? did you see a splash screen like this one?
<img width="846" alt="image" src="https://user-images.githubusercontent.com/4189262/114164166-e2539b80-9922-11eb-951d-a08ed0778010.png">

**Comment by katarzynaozik** [comment]
Yes, for the new account katarzyna2, it works, but the old one - katarzyna it doesn't. I cannot see a splash screen.
I even tried to run by command from mu folder: pythonw -m mu. There are no error messages.

**Comment by carlosperate** [comment]
That's really odd, could you try uninstalling and reinstalling the Mu app in the "bad" account? Maybe something went wrong during the installation that stops Mu from launching.
Do you have any antivirus software, or something along those lines, that could be interfering?

**Comment by katarzynaozik** [comment]
Success! I delete a folder in Roaming directory (C:\Users\katarzyna\AppData\Roaming) with Python. Now everything is ok. Thanks for help.

By the way is it possible to install Mu Editor for all users? It is more for convenient for using at school with different accounts?

**Comment by carlosperate** [comment]
I'm glad you resolved it!
I've opened this issue to track that feature request, thanks @katarzynaozik!
https://github.com/mu-editor/mu/issues/1473

**Comment by katarzynaozik** [comment]
Thank you!
