### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by thomasjmew** [mu-editor/mu#1450]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.3
Locale: en_ZA
Platform: Linux 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64

```
Traceback (most recent call last):
  File "/home/thomas/.local/lib/python3.8/site-packages/mu/interface/panes.py", line 607, in contextMenuEvent
    local_filename = self.currentItem().text()
AttributeError: 'NoneType' object has no attribute 'text'

```

**Comment by carlosperate** [comment]
Thank you very much for the report @thomasjmew!

We've recently resolved this in https://github.com/mu-editor/mu/pull/1432, so the next Mu beta release will have this fixed.
For that reason I hope you don't mind if I close this issue, to try to keep the issue tracker organised, but please feel free to reopen if you think this is a different problem.

In the meantime the workaround would be not to right click on it an empty file list from the Files panel.
