### ISSUE TITLE
Un problème est survenu pendant le flashage de la micro:bit.

### ISSUE THREAD

**Issue by profroques** [mu-editor/mu#1463]
Bonjour,

je suis sur Mac Catalina. J'ai installé la dernière version de Mu-editor (Mu.Editor.1.1.0b3) sans problème. Lorsque je flash la carte micro:bit, j'ai ce message d'erreur qui apparait : 
Un problème est survenu pendant le flashage de la micro:bit. Ne pas déconnecter le périphériques tant que le flashage n'est pas terminé. Regarde les logs pour plus d'informations.

Auriez vous déjà été confrontés à ce problème ?

Merci pour votre aide :)

**Comment by tjguk** [comment]
@profroques  -- would you be able to provide the logs from Mu onto this ticket, please? Ideally as an attached file

There are instructions here:

https://codewith.mu/en/howto/1.1/read_logs

**Comment by carlosperate** [comment]
Hi @profroques,

Are you still experiencing this issue? if you are, could you update to the latest beta version, try again and if the problem persists send the log? Should be located in `~/Library/Logs/mu`

**Comment by carlosperate** [comment]
Hi @profroques 
If you are in macOS and having issues flashing some board could you try the steps listed here? https://github.com/mu-editor/mu/issues/1383#issuecomment-810537546

**Comment by carlosperate** [comment]
Hi @profroques,

This should have been fixed in beta.6: https://github.com/mu-editor/mu/releases/tag/1.1.0-beta.6

More info in https://github.com/mu-editor/mu/issues/1383#issuecomment-935760258.
