### ISSUE TITLE
Check button on windows exe doesn't do anything yet

### ISSUE THREAD

**Issue by dannystaple** [mu-editor/mu#147]
Using some sample code the check button doesn't seem to do anything:
```
from microbit import *

# Write your code here :-)
display.
print('missing quote)
```

Pressing the check button pops up nothing. Mu does show the missing quote as an error by default.

**Comment by carlosperate** [comment]
This might be related to https://github.com/mu-editor/mu/issues/117. Was this the version downloaded from codewit.mu ? Could you try this exe as well? (latest build) https://s3-us-west-2.amazonaws.com/ardublockly-builds/microbit/windows/mu-2016-08-25_20_51_43.exe

**Comment by dannystaple** [comment]
That worked.

**Comment by carlosperate** [comment]
Great. We need to make sure the patched executable goes to the website.

**Comment by ntoll** [comment]
I've updated the website. Apologies for the delay on my part.... post PyCon UK work got in the way. Only just catching up on PRs. :-)
