### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Robert021965** [mu-editor/mu#1475]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.3
Locale: en_US
Platform: Linux 5.4.88-12233-g8e0826df26a0 #1 SMP PREEMPT Wed Apr 7 19:44:59 PDT 2021 x86_64

```
Traceback (most recent call last):
  File "/home/robertogiusto/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 442, in ensure_and_create
    self.ensure()
  File "/home/robertogiusto/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 467, in ensure
    self.ensure_path()
  File "/home/robertogiusto/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 480, in ensure_path
    raise VirtualEnvironmentError(message)
mu.virtual_environment.VirtualEnvironmentError: /home/robertogiusto/.local/share/mu/mu_venv-37-20210414-083748 does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/robertogiusto/.local/lib/python3.7/site-packages/mu/app.py", line 162, in run
    raise ex
  File "/home/robertogiusto/.local/lib/python3.7/site-packages/mu/app.py", line 149, in run
    venv.ensure_and_create(self.display_text)
  File "/home/robertogiusto/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 449, in ensure_and_create
    self.create()
  File "/home/robertogiusto/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 596, in create
    self.install_baseline_packages()
  File "/home/robertogiusto/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 649, in install_baseline_packages
    wheels.download()
  File "/home/robertogiusto/.local/lib/python3.7/site-packages/mu/wheels/__init__.py", line 115, in download
    check=True,
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'wheel', '--no-deps', '--wheel-dir', '/home/robertogiusto/.local/lib/python3.7/site-packages/mu/wheels', '/home/robertogiusto/.local/lib/python3.7/site-packages/mu/wheels/cryptography-3.4.7.tar.gz']' returned non-zero exit status 1.

```

**Comment by Robert021965** [comment]
New to Linux, new to Python 🤦

Using Linux on a Chromebook to run Python

**Comment by carlosperate** [comment]
Thanks for the repot @Robert021965!

Could you run the following commands on a terminal and copy/paste the output here? It will help us with the debugging:

```
/usr/bin/python3 -m pip --version
```

```
/usr/bin/python3 -m pip wheel --no-deps --wheel-dir /home/robertogiusto/.local/lib/python3.7/site-packages/mu/wheels /home/robertogiusto/.local/lib/python3.7/site-packages/mu/wheels/cryptography-3.4.7.tar.gz
```

**Comment by Robert021965** [comment]
>
>
> Could you run the following commands on a terminal and copy/paste the
> output here? It will help us with the debugging:
>
> /usr/bin/python3 -m pip --version
>
> pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)


> /usr/bin/python3 -m pip wheel --no-deps --wheel-dir /home/robertogiusto/.local/lib/python3.7/site-packages/mu/wheels /home/robertogiusto/.local/lib/python3.7/site-packages/mu/wheels/cryptography-3.4.7.tar.gz
>
>
 Processing
./.local/lib/python3.7/site-packages/mu/wheels/cryptography-3.4.7.tar.gz
  Installing build dependencies ... done
Building wheels for collected packages: cryptography
  Running setup.py bdist_wheel for cryptography ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools,
tokenize;__file__='/tmp/pip-req-build-8nd79xwq/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d
/tmp/pip-wheel-xojq4yfo:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/cryptography
  copying src/cryptography/__about__.py ->
build/lib.linux-x86_64-3.7/cryptography
  copying src/cryptography/__init__.py ->
build/lib.linux-x86_64-3.7/cryptography
  copying src/cryptography/exceptions.py ->
build/lib.linux-x86_64-3.7/cryptography
  copying src/cryptography/fernet.py ->
build/lib.linux-x86_64-3.7/cryptography
  copying src/cryptography/utils.py ->
build/lib.linux-x86_64-3.7/cryptography
  creating build/lib.linux-x86_64-3.7/cryptography/hazmat
  copying src/cryptography/hazmat/__init__.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat
  copying src/cryptography/hazmat/_der.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat
  copying src/cryptography/hazmat/_oid.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat
  copying src/cryptography/hazmat/_types.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat
  creating build/lib.linux-x86_64-3.7/cryptography/x509
  copying src/cryptography/x509/__init__.py ->
build/lib.linux-x86_64-3.7/cryptography/x509
  copying src/cryptography/x509/base.py ->
build/lib.linux-x86_64-3.7/cryptography/x509
  copying src/cryptography/x509/certificate_transparency.py ->
build/lib.linux-x86_64-3.7/cryptography/x509
  copying src/cryptography/x509/extensions.py ->
build/lib.linux-x86_64-3.7/cryptography/x509
  copying src/cryptography/x509/general_name.py ->
build/lib.linux-x86_64-3.7/cryptography/x509
  copying src/cryptography/x509/name.py ->
build/lib.linux-x86_64-3.7/cryptography/x509
  copying src/cryptography/x509/ocsp.py ->
build/lib.linux-x86_64-3.7/cryptography/x509
  copying src/cryptography/x509/oid.py ->
build/lib.linux-x86_64-3.7/cryptography/x509
  creating build/lib.linux-x86_64-3.7/cryptography/hazmat/backends
  copying src/cryptography/hazmat/backends/__init__.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends
  copying src/cryptography/hazmat/backends/interfaces.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends
  creating build/lib.linux-x86_64-3.7/cryptography/hazmat/bindings
  copying src/cryptography/hazmat/bindings/__init__.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/bindings
  creating build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/__init__.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/_asymmetric.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/_cipheralgorithm.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/_serialization.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/cmac.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/constant_time.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/hashes.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/hmac.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/keywrap.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/padding.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/poly1305.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
  creating build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/__init__.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/aead.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/backend.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/ciphers.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/cmac.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/decode_asn1.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/dh.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/dsa.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/ec.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/ed25519.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/ed448.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/encode_asn1.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/hashes.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/hmac.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/ocsp.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/poly1305.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/rsa.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/utils.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/x25519.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/x448.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/x509.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  creating build/lib.linux-x86_64-3.7/cryptography/hazmat/bindings/openssl
  copying src/cryptography/hazmat/bindings/openssl/__init__.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/bindings/openssl
  copying src/cryptography/hazmat/bindings/openssl/_conditional.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/bindings/openssl
  copying src/cryptography/hazmat/bindings/openssl/binding.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/bindings/openssl
  creating
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/__init__.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/dh.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/dsa.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/ec.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/ed25519.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/ed448.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/padding.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/rsa.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/utils.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/x25519.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/x448.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
  creating build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/__init__.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/aead.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/algorithms.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/base.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/modes.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/ciphers
  creating build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/__init__.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/concatkdf.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/hkdf.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/kbkdf.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/scrypt.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/x963kdf.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
  creating
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/serialization
  copying src/cryptography/hazmat/primitives/serialization/__init__.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/serialization
  copying src/cryptography/hazmat/primitives/serialization/base.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/serialization
  copying src/cryptography/hazmat/primitives/serialization/pkcs12.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/serialization
  copying src/cryptography/hazmat/primitives/serialization/pkcs7.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/serialization
  copying src/cryptography/hazmat/primitives/serialization/ssh.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/serialization
  creating
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/twofactor
  copying src/cryptography/hazmat/primitives/twofactor/__init__.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/twofactor
  copying src/cryptography/hazmat/primitives/twofactor/hotp.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/twofactor
  copying src/cryptography/hazmat/primitives/twofactor/totp.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/twofactor
  copying src/cryptography/hazmat/primitives/twofactor/utils.py ->
build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/twofactor
  running egg_info
  writing src/cryptography.egg-info/PKG-INFO
  writing dependency_links to src/cryptography.egg-info/dependency_links.txt
  writing requirements to src/cryptography.egg-info/requires.txt
  writing top-level names to src/cryptography.egg-info/top_level.txt
  adding license file 'LICENSE' (matched pattern 'LICEN[CS]E*')
  adding license file 'LICENSE.APACHE' (matched pattern 'LICEN[CS]E*')
  adding license file 'LICENSE.BSD' (matched pattern 'LICEN[CS]E*')
  adding license file 'LICENSE.PSF' (matched pattern 'LICEN[CS]E*')
  reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'docs/_build'
  warning: no previously-included files found matching 'vectors'
  warning: no previously-included files matching '*' found under directory
'vectors'
  warning: no previously-included files matching '*' found under directory
'.github'
  warning: no previously-included files found matching 'release.py'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching
'dev-requirements.txt'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files found matching 'mypy.ini'
  warning: no previously-included files matching '*' found under directory
'.zuul.d'
  warning: no previously-included files matching '*' found under directory
'.zuul.playbooks'
  writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
  copying src/cryptography/py.typed ->
build/lib.linux-x86_64-3.7/cryptography
  running build_ext
  generating cffi module 'build/temp.linux-x86_64-3.7/_padding.c'
  creating build/temp.linux-x86_64-3.7
  generating cffi module 'build/temp.linux-x86_64-3.7/_openssl.c'
  running build_rust

      =============================DEBUG
ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps
to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for
most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation.html for
specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq.html
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation.html#rust
      5) If you are experiencing issues with Rust for *this release only*
you may
         set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
      =============================DEBUG
ASSISTANCE=============================

  error: can't find Rust compiler

  If you are using an outdated pip version, it is possible a prebuilt wheel
is available for this package but pip is not able to install from it.
Installing from the wheel would avoid the need for a Rust compiler.

  To update pip, run:

      pip install --upgrade pip

  and then retry package installation.

  If you did intend to build this package from source, try installing a
Rust compiler from your system package manager and ensure it is on the PATH
during installation. Alternatively, rustup (available at https://rustup.rs)
is the recommended way to download and update the Rust compiler toolchain.

  This package requires Rust >=1.41.0.

  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
  Complete output from command /usr/bin/python3 -u -c "import setuptools,
tokenize;__file__='/tmp/pip-req-build-8nd79xwq/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  running clean
  removing 'build/temp.linux-x86_64-3.7' (and everything under it)
  removing 'build/lib.linux-x86_64-3.7' (and everything under it)
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.7' does not exist -- can't clean it
  removing 'build'
  running clean_rust

      =============================DEBUG
ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps
to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for
most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation.html for
specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq.html
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation.html#rust
      5) If you are experiencing issues with Rust for *this release only*
you may
         set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
      =============================DEBUG
ASSISTANCE=============================

  error: can't find Rust compiler

  If you are using an outdated pip version, it is possible a prebuilt wheel
is available for this package but pip is not able to install from it.
Installing from the wheel would avoid the need for a Rust compiler.

  To update pip, run:

      pip install --upgrade pip

  and then retry package installation.

  If you did intend to build this package from source, try installing a
Rust compiler from your system package manager and ensure it is on the PATH
during installation. Alternatively, rustup (available at https://rustup.rs)
is the recommended way to download and update the Rust compiler toolchain.

  This package requires Rust >=1.41.0.

  ----------------------------------------
  Failed cleaning build dir for cryptography
Failed to build cryptography
ERROR: Failed to build one or more wheels


Thanks for your help

**Comment by carlosperate** [comment]
Thanks @Robert021965, that more or less confirms my suspicion that perhaps the pip version is too old.

Did you try to run `/usr/bin/python3 -m pip --version` as well? What version of pip does it report?

If you can update pip with this command it should fix the issue:

```
/usr/bin/python3 -m pip install --upgrade pip
```

**Comment by Robert021965** [comment]
It worked! Thank you so much!

Il giorno mer 14 apr 2021 alle ore 11:44 Carlos Pereira Atencio <
***@***.***> ha scritto:

**Comment by carlosperate** [comment]
I'm glad you were able to resolve it, thanks for all the testing!
