### ISSUE TITLE
Antiviruses considering the Mu installer "dangerous"

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#1495]
There are reports of some antiviruses warning against the Mu installer: https://github.com/mu-editor/mu/issues/1484#issuecomment-822764888

> Thanks for the additional help. I downloaded Mu-editor- Win64-1.1.04b.msi and installed it although a bit reluctantly. Windows defender indicated this could harm my computer but Norton said it was safe so I took a chance. After the installation I started Mu and received the attached crash report log.

We'll probably need to submit the final installers for consideration in their allowlists or check what we might need to do to not be considered "dangerous".

I believe @ntoll has done something related to this for Norton, and we looked into issues with McAfee in the past: https://github.com/mu-editor/mu/issues/280

**Comment by tjguk** [comment]
@carlosperate  -- I'm fairly sure that the "Windows defender" issue is basically the fact that the installer isn't signed (because @ntoll can't yet renew the Windows cert). It's the MS equivalent of the Apple "this app can seriously damage your health" warning which we had to cope with on OSX.

**Comment by carlosperate** [comment]
I though the Windows installer was fully signed now? Is that not the case?

**Comment by carlosperate** [comment]
Moving the conversation from https://github.com/mu-editor/mu/issues/1600#issuecomment-877709029 here:

> Despite many efforts I can't get this to download. Microsoft Defender blocks the msi file as unsafe (so I can't even try to install it). I have reported it as a safe file so hopefully this will be resolved quickly.

@AnnEvans is there no way to bypass that warning?
Would you be able to take any screenshots trying to download the file https://github.com/mu-editor/mu/releases/download/1.1.0-beta.5/Mu-Editor-Win64-1.1.0b5.msi ?

**Comment by carlosperate** [comment]
Getting this warning on Edge browser on Windows, but not on macOS:

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/4189262/129328353-37984f62-380b-40ed-a48d-d3b116c93714.png">

The "see more" link/button doesn't do anything, I think that's only to see previously downloaded files in the list.

When mouse over the entry this is the menu from the ellipsis button:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/4189262/129328771-9459263d-8a94-4461-8746-848efbc2add0.png">

We need users to click on "keep" to be able to download the file.
Ideally we could ask people to "Report this file as safe" first, that might be able to build some kind of trust over time.

@ntoll there is an option to submit a form as the owner, so that this warning/blockage can get reviewed:
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/4189262/129329152-aadeb395-fe9e-49bc-a01e-73335232ad85.png">

**Comment by carlosperate** [comment]
After all that we also get this "Windows Defender Smart screen":
<img width="546" alt="image" src="https://user-images.githubusercontent.com/4189262/129330027-63cee6f8-aa9b-4787-bde4-6ef4ab969626.png">

**Comment by carlosperate** [comment]
Just FYI, Firefox will soon block non-signed executable downloads as well: https://therecord.media/firefox-follows-chrome-and-prepares-to-block-insecure-downloads/

**Comment by carlosperate** [comment]
The Edge issue was due to the Windows installer not being signed, now that they are signed again the warnings do not trigger any more.

The antivirus issue looks like might not be a problem anymore, if a user reports an antivirus marking Mu as a thread we can look into it at that point.

This is good to be closed 👍
