### ISSUE TITLE
Markdown the website 

### ISSUE THREAD

**Issue by dannystaple** [mu-editor/mu#150]
So it is easier to contribute.
Consider jekyll bootstrap.

**Comment by ZanderBrown** [comment]
Definitely a good idea. particularly when we start writing the help pages

**Comment by carlosperate** [comment]
This has been implemented in https://github.com/mu-editor/mu-editor.github.io/pull/3, although we might still need to discuss how the help documentation creation works (https://github.com/mu-editor/mu-editor.github.io/issues/4).

**Comment by ntoll** [comment]
I just copied it over. :-)

It might be better to simply move the help docs over from their own repos.

Not sure why they were separated out in the first place..?!?!? Anyone?

**Comment by carlosperate** [comment]
> Not sure why they were separated out in the first place..?!?!? Anyone?

Why the help files were separated?
A repository like https://github.com/mu-editor/mu-editor.github.io can be quite intimidating to edit if you don't know what's going on (and I must admit I still struggle!). Having a repository only with the markdown files is a lot more welcoming.
Then the idea was to have a git submodule/s inside https://github.com/mu-editor/mu-editor.github.io, which is what https://github.com/mu-editor/mu-editor.github.io/pull/8 was aiming to do.

**Comment by carlosperate** [comment]
Already implemented in https://github.com/mu-editor/mu-editor.github.io/pull/9, the markdown help pages can be edited in https://github.com/mu-editor/help-pages
