### ISSUE TITLE
In the website move the downloads to releases

### ISSUE THREAD

**Issue by dannystaple** [mu-editor/mu#151]
Move executables and tarballs to github releases  - keep the clones small.
Ensure any website links to download will still reach the releases before merging.

**Comment by ntoll** [comment]
Any docs on how to do this?

**Comment by carlosperate** [comment]
https://help.github.com/articles/creating-releases/

It's basically a git tag with additional content attached to it in GitHub. An advantage is to be able to retrieve all this data from the GitHub API: https://developer.github.com/v3/repos/releases/

**Comment by ntoll** [comment]
OK... I'll take a look.

**Comment by carlosperate** [comment]
There is a related discussion to this one in https://github.com/mu-editor/mu/issues/155 (linking the issues to easily keep track).

**Comment by ntoll** [comment]
Fixed. See the brand new release associated with this repos!
