### ISSUE TITLE
Mu installed but window not appearing when run (only splash screen)

### ISSUE THREAD

**Issue by BarryButler** [mu-editor/mu#1570]
Mu suddenly has stopped working when the icon is clicked (mu-editor_1.1.0-alpha.2_win64).  I removed the program and reinstalled it and have the same problem.

When I click on the Mu icon, the splash screen appears and the icon is put on my task bar but the Mu window does not appear.  Passing the mouse over the task bar icon shows that the program is loaded.

I cannot get into the window, so cannot get to the log file.  Let me know where it is located

**Comment by BarryButler** [comment]
Found the mu.log

[mu.log](https://github.com/mu-editor/mu/files/6490890/mu.log)

**Comment by carlosperate** [comment]
Thanks for the report and the log @BarryButler!

Looking at the log it seems like sometimes the window does open and you are able to close it via the "Quit" button is that right?

Alpha.2 is a very old release, if could you also try the latest beta and see if you still have this issue? https://github.com/mu-editor/mu/releases/tag/1.1.0-beta.5

Thanks!

**Comment by BarryButler** [comment]
Everything works great.


Regards,

Barry Butler
Teacher (Digital Technology, Aviation, Maths, Science)

[2019 Email Signature Block]
------------------------

This message (including attachments) is intended for the addressee named above. It may also be confidential, privileged and/or subject to copyright. If you wish to forward this message to others, you must first obtain the permission of the author. If you are not the addressee named above, you must not disseminate, copy, communicate or otherwise use or take any action in reliance on this message. You understand that any privilege or confidentiality attached to this message is not waived, lost or destroyed because you have received this message in error. If you have received this message in error please notify the sender and delete from any computer. Unless explicitly attributed, the opinions expressed in this message do not necessarily represent the official position or opinions of the State of Queensland or the Department of Education, Training and Employment. Whilst all care has been taken, the Department of Education, Training and Employment disclaims all liability for loss or damage to person or property arising from this message being infected by computer virus or other contamination.

**Comment by carlosperate** [comment]
That's great, thanks for the update @BarryButler!
