### ISSUE TITLE
Crash Report - cannot import name 'PY36_VERSIONS' from 'black'

### ISSUE THREAD

**Issue by Pro-sketch** [mu-editor/mu#1581]
[**REMEMBER]
([mu.log](https://github.com/mu-editor/mu/files/6521880/mu.log)) 
TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.4
Locale: en_US
Platform: Windows 7 6.1.7601 x86

```
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\mu\logic.py", line 1779, in tidy_code
    from black import format_str, FileMode, PY36_VERSIONS
ImportError: cannot import name 'PY36_VERSIONS' from 'black' (C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\black\__init__.py)

```

**Comment by carlosperate** [comment]
Thank you very much for the report @Pro-sketch!
And specially for attaching the log as well 👍 

We fixed this issue in https://github.com/mu-editor/mu/pull/1519 and will be part of the next beta release.

I'll close this issue to keep things tidy, but thank you again for taking the time to report this.
Let us know if you find any other issues :)
