### ISSUE TITLE
venv QProcess timeout error is printed on console but not the logs 

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#1611]
From https://github.com/mu-editor/mu/issues/1600#issuecomment-851635763.

When the venv pip install process times out we can see this error in the console, but nothing gets captured in the logs:

```
QProcess: Destroyed while process ("/home/pi/.local/share/mu/mu_venv-35-20210527-122405/bin/pip") is still running.
```

**Comment by tjguk** [comment]
I *think* that's addressed by a change I've just made to the QProcess wait/finish logic. 

https://github.com/tjguk/mu/commit/bf97e60480ef9c821e4316e9e9cef7979e36678b

**Comment by carlosperate** [comment]
Between tjguk@bf97e60 and https://github.com/mu-editor/mu/pull/1610 this should be resolved.
