### ISSUE TITLE
deal with overwrite in file pane

### ISSUE THREAD

**Issue by askvictor** [mu-editor/mu#162]
When a file is dragged from local to device, and the file already exists on device, should prompt user to overwrite or cancel. Also, currently when this happens, a second file entry for the file appears in the file pane.

**Comment by ntoll** [comment]
Good catch. This is obviously a bug. Pull requests welcome. ;-)

**Comment by carlosperate** [comment]
Just to clarify, I assume the file get's overwritten but two entries are displayed?

**Comment by askvictor** [comment]
Yep. If the file pane gets closed and reopened, everything is good.

**Comment by eduvik** [comment]
Here you go: https://github.com/mu-editor/mu/pull/165

**Comment by ntoll** [comment]
Fixed in latest release.
