### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by ajs256** [mu-editor/mu#1641]
Crash Report originally raised in https://github.com/mu-editor/mu-editor.github.io/issues/63 by @pviljoen2

> Traceback (most recent call last):
> File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 161, in run
> raise ex
> File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 148, in run
> venv.ensure_and_create(self.display_text)
> File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 494, in ensure_and_create
> self.create()
> File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 624, in create
> self.upgrade_pip()
> File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 671, in upgrade_pip
> raise VirtualEnvironmentCreateError("Unable to upgrade pip")
> mu.virtual_environment.VirtualEnvironmentCreateError: Unable to upgrade pip
> 
> *** Note cannot find place to upload log file****

**Comment by carlosperate** [comment]
Oh sorry, didn't realised you had created this already for mu-editor/mu-editor.github.io#63.
I've transferred the issue to https://github.com/mu-editor/mu/issues/1642 so we can continue this conversation over there.
