### ISSUE TITLE
Button "tidy" - Crash Report

### ISSUE THREAD

**Issue by noisestream** [mu-editor/mu#1678]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.4
Locale: en_GB
Platform: Windows 10 10.0.19041 AMD64

```
[mu.log](https://github.com/mu-editor/mu/files/6754924/mu.log)

Traceback (most recent call last):
  File "c:\use
[mu.log](https://github.com/mu-editor/mu/files/6754926/mu.log)
rs\****\appdata\local\programs\python\python38\lib\site-packages\mu\logic.py", line 1779, in tidy_code
    from black import format_str, FileMode, PY36_VERSIONS
ImportError: cannot import name 'PY36_VERSIONS' from 'black' (c:\users\****\appdata\local\programs\python\python38\lib\site-packages\black\__init__.py)

```

**Comment by carlosperate** [comment]
Thank you for the report @noisestream!
I believe this has been fixed in PR https://github.com/mu-editor/mu/pull/1519, and it should work correctly in the next release.

Did you install Mu via pip? If so you can downgrade black to version `19.10b0` as a workaround.
