### ISSUE TITLE
Raspbian package out of date

### ISSUE THREAD

**Issue by gbaman** [mu-editor/mu#168]
Right now, the package available with Raspbian from the Raspbian repos of Mu is rather out of date, [March 2016](http://archive.raspberrypi.org/debian/pool/main/m/mu/). Given the Linux download from the main site doesn't seem to work on Raspbian, any chance we could get an updated copy of Mu in the repos? The March one is missing lots of new cool stuff like radio module support etc.
Apparently the current one is signed by @ntoll.

**Comment by ntoll** [comment]
Hey @asb @bennuttall any idea how to update this? If you give me a couple of days I'll update with all the recent PRs and upstream MicroPython fixes.

**Comment by gbaman** [comment]
Probably best to throw in @XECDesign as well, given his area of expertise as well.

**Comment by XECDesign** [comment]
Happy to accept an updated package whenever it's ready. (serge@<obviousdomain>.org)

**Comment by asb** [comment]
It should be enough to just do `git-buildpackage --git-upstream-tree=master -uc -us` on a Debian system to generate an unsigned package based on current master. Sorry, I'm a bit swamped at the moment to help out more.

**Comment by jg00dman** [comment]
for raspbian please consider my pull request... fixes issue "Mu interface on small screens #122"

**Comment by ZanderBrown** [comment]
@jg00dman please don't add comments to other issues / PRs about a PR you just opened.

We are notified (via email and on GitHub) when you open a PR and it will be reviewed and discussed on it's individual issue

**Comment by jg00dman** [comment]
Sorry, it just seemed relevant... I was trying to find something else I could help with.

**Comment by ntoll** [comment]
People at RPi are handling this as/when we create new versions of Mu.
