### ISSUE TITLE
venv: Downloading wheels does not show progress in the splash screen

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#1687]
Running Mu for the first time without zipped wheels, it gets to the "downloading" step and can stay there for quite some time:

<img width="846" alt="image" src="https://user-images.githubusercontent.com/4189262/124808296-a8605880-df56-11eb-93dd-4ec33a634522.png">

Specially in older systems or with bad internet connections it can look like the start up is  stuck.
We should probably add to the loggging so that each wheel download updates the messaging.

**Comment by tjguk** [comment]
Yes; I spotted this when developing but couldn't quickly see any reason (in principle the "splash screen" logger is passed up the chain). So I left it there for now.

**Comment by carlosperate** [comment]
It was pretty much all setup to be able to do this already, just had to pass the logger as an argument to `wheels.download()`: https://github.com/mu-editor/mu/pull/1735
