### ISSUE TITLE
Copy/Paste via keys not working in REPL

### ISSUE THREAD

**Issue by eduvik** [mu-editor/mu#169]
Works fine using context menu, but hotkeys don't work (at least not on Mac).

**Comment by eduvik** [comment]
Actually; on a Windows/Linux, Ctrl-C should probably not be mapped to Copy; however on Mac Command-C should be (currently doesn't work). Perhaps follow the conventions of plenty of terminal programs and use Ctrl-Shift-C for copy when in REPL? The context menu should also be updated to reflect

**Comment by carlosperate** [comment]
Is there any chance to add  a `QKeySequence` to the context menu `addAction()` calls in #167 ? Ideally it would show up like most menu item shortcuts do, and that could also indicate Windows users of the different key shortcut.

<img width="111" alt="context" src="https://cloud.githubusercontent.com/assets/4189262/19292116/b2d78c00-9011-11e6-93dd-ccc534001b82.png">

**Comment by ntoll** [comment]
This has been fixed by SHIFT-CTRL-[C|V] etc...

**Comment by carlosperate** [comment]
Could we get the SHIFT-CTRL-[C|V]  in the documentation if it's not there already?

**Comment by ntoll** [comment]
It'll be in the keyboard shortcuts tutorial on the new website. ;-)

**Comment by carlosperate** [comment]
Awesome, thanks!

**Comment by carlosperate** [comment]
> It'll be in the keyboard shortcuts tutorial on the new website. ;-)

I've created https://github.com/mu-editor/mu-editor.github.io/issues/30 to track things to include in this shortcuts page.
