### ISSUE TITLE
Dark Mode should support f"{x}:{y}"

### ISSUE THREAD

**Issue by rsbohn12** [mu-editor/mu#1707]
### What were you trying to do?

Use an f-string while in dark mode.

### What steps did you take to trigger the issue?

```python
x=20
y=30
print(f"{x}:{y}")
```

### What did you expect to happen?

f-strings should look like other strings

### What actually happened?

The f-string is purple on white. The variables (x,y) are gray on black.

### Operating System Version

Windows 10

### Mu Version

1.1.0-beta-5

**Comment by FoamyGuy** [comment]
Here is a screenshot of how the fstrings appear in dark mode:
![image](https://user-images.githubusercontent.com/2406189/126042925-3936e724-1305-4785-8e41-2164d056fbbc.png)

**Comment by ntoll** [comment]
Hmm.... nice catch.
