### ISSUE TITLE
Dragging a file to the micro:bit file system shows it as duplicated

### ISSUE THREAD

**Issue by whaleygeek** [mu-editor/mu#176]
If the micro:bit file system already has a file called 'fred.txt' listed in the left hand FILES pane, dragging another fred.txt file from the right pane to the left pane now shows the file 'fred.txt' in the left pane twice. If you close the pane and open it again, it is only listed once.

**Comment by carlosperate** [comment]
Hi David, 

This has been reported on https://github.com/mu-editor/mu/issues/162, and should be fixed soon from PR https://github.com/mu-editor/mu/pull/166.

**Comment by ntoll** [comment]
Fixed in latest release.
