### ISSUE TITLE
Better compatibility for restricted environments in schools

### ISSUE THREAD

**Issue by rpiuser** [mu-editor/mu#178]
Would there be any possibility of setting a default save / load path under a windows environment ? Currently C: is restricted and My Documents is redirected using GPO. When loading a "This operation has been cancelled due to restrictions in effect on this computer" message is displayed (Due to C: being restricted) clicking okay takes you to "My Documents" The same behaviour happens with save. Ideally pointing to the users home folder (e.g H:\Mu) would be a lot cleaner and a much better experience / less confusing for the students using it.

**Comment by ZanderBrown** [comment]
Take a look at #126 & #86

**Comment by rpiuser** [comment]
Thank you, I've read through the threads and can't seem to determine if this has been resolved. I'm assuming I need the settings.json and I need to set a path in there, however I'm unsure of the format of the path  :- "paths": ["path/foo.py" so would I use "paths": ["path/H:/mu"] ? I'll try testing.

**Comment by ZanderBrown** [comment]
Ah yes seems that didn't happen. I'm assuming your using the exe?

**Comment by rpiuser** [comment]
Using this build mu-2016-10-23_16_42_53.exe on windows

**Comment by ZanderBrown** [comment]
Okay. Having received some support for the feature in #179 hopefully it should make it into master over the next week to be included in the next release

**Comment by rpiuser** [comment]
Thank you, much appreciated

**Comment by ZanderBrown** [comment]
#179 has been merged. Does it resolve your issue?

**Comment by carlosperate** [comment]
As a general note to remind us before we close this issue: We really need to add a page about the settings file to the documentation so that this feature can be discovered.

**Comment by rpiuser** [comment]
Using mu-0.9.13.win works great thank you, however if you specify a wrong drive letter or the drive doesn't exist in settings.json mu exits with a run returned -1

**Comment by ZanderBrown** [comment]
ah makes sense. I will put a check in asap

**Comment by rpiuser** [comment]
Other than that, it's working great - kids are merrily coding away using it :)

**Comment by ntoll** [comment]
Closing since fixed.
