### ISSUE TITLE
Accessibility - add keyboard short-cuts for the buttons

### ISSUE THREAD

**Issue by ntoll** [mu-editor/mu#183]
I've been liaising with people who are interested in having a Braille display work with Mu. It would be *really* useful for them if we had keyboard short-cuts for the buttons. They suggest the following schema:

* New - `Ctrl+N`
* Load - `Ctrl+O`/`Ctrl+L`
* Save - `Ctrl+S`
* Flash - `F9`
* Files - `Ctrl+F`
* Repl - `Ctrl+R`
* Zoom-In - `Ctrl+Shift+plus`
* Zoom-Out - `Ctrl+Shift+minus`
* Theme - `Ctrl+T`
* Check - `F8`
* Help - `Ctrl+H`
* Quit - `Alt+F4`

I guess the important this is such short-cuts are based upon current conventions given the operating system we may be running under.

**Comment by ZanderBrown** [comment]
Looks good but:

Files `Ctrl+F` - This is an editor and most editors use `Ctrl+F` for 'Find' which maybe confusing

Help `Ctrl+H` - Most programs use `F1` for help and editors often use this for 'Replace'

**Comment by carlosperate** [comment]
This should be a useful guideline: https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts

**Comment by scruss** [comment]
Doesn't use the standard system quit of Ctrl+Q or Ctrl+W

**Comment by ntoll** [comment]
Implemented (ages ago) as per the helpful guidelines and pointers from everyone. Thank you!
