### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by guru8000** [mu-editor/mu#1867]
Hey, everything was ok with Mu editor untill I installed python on my computer. Then I couldn't open MuEditor anymore. It wasn't crashing, just wasn't opening. I uninstalled it and installed again - didn't help. Then I uninstalled python, reinstalled MuEditor, didn't help. all of it was yesterday. Today, I reversed my computer to the saved point from before installing python. Reinstalled MuEditor and the crash report appeared. Please help.

**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.5
Locale: pl_PL
Platform: Windows 10 10.0.19041 AMD64

```
ll_wheel
    generated_console_scripts = maker.make_multiple(scripts_to_generate)
  File "C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254\lib\site-packages\pip\_vendor\distlib\scripts.py", line 422, in make_multiple
    filenames.extend(self.make(specification, options))
  File "C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254\lib\site-packages\pip\_internal\operations\install\wheel.py", line 448, in make
    return super().make(specification, options)
  File "C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254\lib\site-packages\pip\_vendor\distlib\scripts.py", line 411, in make
    self._make_script(entry, filenames, options=options)
  File "C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254\lib\site-packages\pip\_vendor\distlib\scripts.py", line 312, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254\lib\site-packages\pip\_vendor\distlib\scripts.py", line 242, in _write_script
    launcher = self._get_launcher('t')
  File "C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254\lib\site-packages\pip\_vendor\distlib\scripts.py", line 390, in _get_launcher
    raise ValueError(msg)
ValueError: Unable to find resource t64.exe in package pip._vendor.distlib

`
[mu.log](https://github.com/mu-editor/mu/files/7439644/mu.log)
``

**Comment by tjguk** [comment]
Thanks for reporting, @guru8000 -- and thanks for attaching the logs. Unfortunately, although I can see the marker in your report which suggests you dropped the log file there, the files don't seem to have been attached to the issue. Can you try on the web interface, please, by adding a new comment and dropping the log file there again.

**Comment by guru8000** [comment]
Strange. I see the file attached. at the bottom there is: https://github.com/mu-editor/mu/files/7439644/mu.log

when u paste it in browser there is the log.
I tried with other computer and I can see the log.

**Comment by tjguk** [comment]
Thanks; not sure what happened there. Thanks for the relink: I can see it now. I'll dip in and see what's happening

**Comment by guru8000** [comment]
Can't wait :)

**Comment by guru8000** [comment]
@tjguk U think u can help me with this?

**Comment by carlosperate** [comment]
@guru8000 could you run this in command prompt and paste the result here? It'll help us diagnose the issue:

```
"C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254\scripts\pip.exe" list --verbose
```

**Comment by guru8000** [comment]
> 
> 
> @guru8000 could you run this in command prompt and paste the result here? It'll help us diagnose the issue:
> 
> ```
> "C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254\scripts\pip.exe" list --verbose
> ```

It says "System nie może odnaleźć określonej ścieżki". - wich means "the system cannot find the path specified"

I checked, I don't have this folder: "mu_venv-38-20211029-085254" instead I have this folder: "mu_venv-38-20211029-085254.FAILED"

When I run in command prompt this: `"C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254.FAILED\Scripts\pip.exe" list --verbose` it says: `Fatal error in launcher: Una
![python](https://user-images.githubusercontent.com/93370224/139827863-baba9800-ff3f-42ca-9e21-2f77e49505e6.png)
ble to create process using '"C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254\Scripts\python.exe"  "C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254.FAILED\Scripts\pip.exe" list --verbose': Nie mo?na odnale?? okre?lonego pliku.` wich means that couldn't find the file specified.

I attached screenshot of this folder.

**Comment by guru8000** [comment]
@carlosperate I don't know if u read the begining of my post, maybe this will halp to find solution:
`everything was ok with Mu editor untill I installed python on my computer. Then I couldn't open MuEditor anymore. It wasn't crashing, just wasn't opening. I uninstalled it and installed again - didn't help. Then I uninstalled python, reinstalled MuEditor, didn't help. all of it was yesterday. Today, I reversed my computer to the saved point from before installing python. Reinstalled MuEditor and the crash report appeared. Please help.`

**Comment by carlosperate** [comment]
Thanks @guru8000, I think the problem is that something in the OS is telling Mu that there are packages installed in the system Python, Mu is then trying to use them, and it fails.

Can you rename the `mu_venv-38-20211029-085254.FAILED` folder to `mu_venv-38-20211029-085254` and try again with:
```
"C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254\Scripts\pip.exe" list --verbose
```
and
```
"C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254\Scripts\python.exe" -m pip list --verbose
```

Thanks!

**Comment by guru8000** [comment]
sure, @carlosperate 

after first command:
`C:\Windows\System32>"C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254\Scripts\pip.exe" list --verbose
Package      Version Location                                                                           Installer
------------ ------- ---------------------------------------------------------------------------------- ---------
backcall     0.2.0   c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
bitstring    3.1.7   c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
cffi         1.14.5  c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
click        8.0.1   c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
colorama     0.4.4   c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
cryptography 3.4.7   c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
debugpy      1.3.0   c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
decorator    5.0.9   c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
ecdsa        0.17.0  c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
esptool      3.1     c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages
pip          21.2.4  c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
setuptools   58.1.0  c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
wheel        0.37.0  c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254\Scripts\python.exe -m pip install --upgrade pip' command.`

after second:

`C:\Windows\System32>"C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254\Scripts\python.exe" -m pip list --verbose
Package      Version Location                                                                           Installer
------------ ------- ---------------------------------------------------------------------------------- ---------
backcall     0.2.0   c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
bitstring    3.1.7   c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
cffi         1.14.5  c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
click        8.0.1   c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
colorama     0.4.4   c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
cryptography 3.4.7   c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
debugpy      1.3.0   c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
decorator    5.0.9   c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
ecdsa        0.17.0  c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
esptool      3.1     c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages
pip          21.2.4  c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
setuptools   58.1.0  c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
wheel        0.37.0  c:\users\dell\appdata\local\python\mu\mu_venv-38-20211029-085254\lib\site-packages pip
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\dell\AppData\Local\python\mu\mu_venv-38-20211029-085254\Scripts\python.exe -m pip install --upgrade pip' command.`

**Comment by carlosperate** [comment]
Thanks @guru8000, that's really helpful. From that we can see that the virtualenv does correctly only pick up the packages from it's own env, maybe the issue is with the Mu-packages Python/pip.

Could you run this as well and paste the result?

```
"C:\Users\dell\AppData\Local\Programs\Mu Editor\Python\python.exe" -m pip list --verbose 
```

**Comment by guru8000** [comment]
ok, @carlosperate , but I'll do it tomorrow, I'm on a different PC now.

**Comment by guru8000** [comment]
@carlosperate  at first, this is me, who thanks here for help :)

at second: didn't work.

I uninstalled Mu, then i deleted whole folder 'Mu Editor' from `c:\users\dell\appdata\local\programs` Then I downloded fresh installation program fom https://github.com/mu-editor/mu/releases/download/1.1.0-beta.6/Mu-Editor-Win64-1.1.0b6.msi

It has been installed. But after trying to open the program, crash appeard (attached screenshot)

I also attach log from this crash.
![mu 1](https://user-images.githubusercontent.com/93370224/140026038-17fbdd92-0318-4a35-a5b5-4606c367cdda.png)
[mu.log](https://github.com/mu-editor/mu/files/7466079/mu.log)

**Comment by guru8000** [comment]
@carlosperate did u find any solution?

**Comment by guru8000** [comment]
@carlosperate did u find any solution?

**Comment by guru8000** [comment]
@carlosperate I think u forgot about me.

**Comment by carlosperate** [comment]
Hi @guru8000,

I'm sorry, I didn't forget, but due to work and other commitments I have almost no free time to really look into Mu issues at the moment. This is a volunteer led project so all the maintainers donate the little free time we might have.

With respect to this specific problem, my guess is that it is somewhat related to the different Python installation in the system, as you suggested before, but I have never encountered this specific issue before, so not too sure how to continue diagnosing it without doing more research online.

If you could find a similar issue in this issue tracker that maybe help us as well: https://github.com/pypa/pip/issues
I wouldn't open an issue there, as this is likely be a problem with how Mu uses `pip`, and not with `pip` itself, but maybe other people had similar problems.

**Comment by carlosperate** [comment]
@guru8000 We think we might have found a solution. Would you be able to try the installer at the bottom of this page, in the "Artifacts" section to see if it resolves the problem you are encountering?
https://github.com/mu-editor/mu/actions/runs/1574840282

To ensure things go smoothly it'd be highly recommended to first uninstall the version of Mu in your PC before installing this version.

If you could try this installer it would be very very useful to us to confirm the issue has been fixed.

**Comment by guru8000** [comment]
@carlosperate I love you !!!!
It works perfectly now.

Thank You :D
