### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by wiknetauto** [mu-editor/mu#1984]
Hey folks! I installed Mu on a new Ubuntu Linux VM yesterday and it was running fine. After powering on the linux VM (virtualbox) this morning, Mu crashed on launch. Any ideas on the fix?

[mu.log](https://github.com/mu-editor/mu/files/7889856/mu.log)

**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: en_US
Platform: Linux 5.11.0-46-generic #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/nathan/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/nathan/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/nathan/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/nathan/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/nathan/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/nathan/.local/share/mu/mu_venv-38-20220118-081600
STDERR: /usr/bin/python3: No module named virtualenv

```
[mu.log](https://github.com/mu-editor/mu/files/7889862/mu.log)

**Comment by carlosperate** [comment]
Hi @wiknetauto,

Thanks for the report and the log!
I believe this might be the issue you are encountering: https://github.com/mu-editor/mu/issues/1954

The main workaround at the moment would be to install the `python3-virtualenv` package using apt and hopefully that should fix it.

**Comment by wiknetauto** [comment]
Thanks!! I'll try that!

**Comment by carlosperate** [comment]
I should have also mentioned that the best fix would be to install Mu in a virtual environment, as that is the recommended way and it should work much better.

I would also personally recommend to use pipx, as it's great for installing Python-based applications: https://pypa.github.io/pipx/
pipx will automatically install Python applications in their own isolated virtual environment, and add the executable to the PATH so that it can be easily launched like any other app.

**Comment by wiknetauto** [comment]
Thanks again, @carlosperate! After installing python3-virtualenv (sudo apt install python3-virtualenv) Mu is working again! I like the virtual environment install method; I will check that out.

**Comment by carlosperate** [comment]
Awesome! Glad it worked.

In that case I'll close this crash report as resolved, we'll continue to investigate the issue itself in https://github.com/mu-editor/mu/issues/1954.
