### ISSUE TITLE
OS X build is unsigned, downloaded from a plaintext website

### ISSUE THREAD

**Issue by glyph** [mu-editor/mu#206]
The "getting started" process for Mu teaches new programmers on macOS a _terrible_ security habit:

1. https://codewith.mu has an invalid certificate
2. the application bundle is unsigned, meaning it won't launch if you've properly secured your mac

This leaves Mu in [venerable company](https://glyph.twistedmatrix.com/2015/11/editor-malware.html), but both of these issues really ought to be fixed.  Teaching people that there are serious consequences to plaintext downloads is hard enough without useful projects providing no way to securely get their software.

**Comment by ntoll** [comment]
Morning @glyph - we're painfully aware of these shortcomings. We're a young project run by time poor volunteers. That's not meant to be an excuse, but it at least demonstrates why we've not done these things yet.

They're on our list and we're getting there.  Thanks for letting us know!

**Comment by ntoll** [comment]
For reference - details on adding TLS to custom domain hosted on GitHub pages: https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by ntoll** [comment]
@carlosperate anything to add on signing releases?

**Comment by carlosperate** [comment]
Indeed, this is something that's on the to-do list. The other thing about signing the applications is that there is a cost to get a Windows certificate and to become an Apple Developer.
Wayne was just telling me about CloudFlare for github pages last Thursday, @WayneKeenan were the instructions that @ntoll linked what you were referring to?

Also, for reference there are individual issues already opened for these topics: https://github.com/mu-editor/mu/issues/148 https://github.com/mu-editor/mu/issues/177 https://github.com/mu-editor/mu/issues/194.

**Comment by glyph** [comment]
Perhaps the PSF would be interested in sponsoring those certificates?

TLS, at least, should be free via let's encrypt.

**Comment by glyph** [comment]
Oh hey I see @ntoll already suggested that on the relevant issue :).  If this is just a duplicate of existing stuff, I'm happy to see it closed.

**Comment by ntoll** [comment]
OK... I've just kicked off migration to CloudFlare - which will give us free TLS support.

**Comment by ZanderBrown** [comment]
Any way to force HTTPS? https://codewith.mu works fine but just entering codewith.mu still uses HTTP

**Comment by ntoll** [comment]
Yup... just wanted to ensure TLS (eventually) worked. Didn't want to put the site into a bad state by default. I'll pull the lever / press the button / cast the enchantment right now. ;-)

**Comment by WayneKeenan** [comment]
@carlosperate yep, that's it.

**Comment by ntoll** [comment]
OK - lever has been pulled. We serve over TLS by default and redirect to a secure endpoint if the user uses just `http://codewith.mu/`

**Comment by carlosperate** [comment]
That's great! Can confirm it works as expected :D
We can now close https://github.com/mu-editor/mu/issues/194 as well.

And thanks for confirming @WayneKeenan (might end up doing the same for my domain, seeing that https is needed for web-bluetooth pages).

**Comment by glyph** [comment]
Thanks a bunch for making this happen.  Security educators everywhere salute you for making their jobs a little easier :)

**Comment by glyph** [comment]
I'm going to close this now, since the download is HTTPS, at least, so there's _some_ authenticity. Codesigning would be nice but at least users are not operating on zero assurance.
