### ISSUE TITLE
mu running from repo installs many packages twice

### ISSUE THREAD

**Issue by ghollf** [mu-editor/mu#2082]
### What were you trying to do?

runnung mu

### What steps did you take to trigger the issue?

checkout mu
./run.py

### What did you expect to happen?

nothing

### What actually happened?

- to get run.py starting many packages have to be installed (=> ~/.local/lib/python3.9/site-packages)
- after run.py is starting, many of the packages get installed again (=> ~/.local/share/mu/mu_venv-39-20220226-213230/lib/python3.9/site-packages)

~/.local/lib/python3.9/site-packages
adafruit_board_toolkit-1.1.0.dist-info
asttokens-2.0.5.dist-info
backcall-0.2.0.dist-info
black-22.1.0.dist-info
click-8.0.4.dist-info
debugpy-1.5.1.dist-info
decorator-5.1.1.dist-info
entrypoints-0.4.dist-info
executing-0.8.2.dist-info
ipykernel-6.9.1.dist-info
ipython-8.0.1.dist-info
ipython_genutils-0.2.0.dist-info
jedi-0.18.1.dist-info
jupyter_client-7.1.2.dist-info
jupyter_core-4.9.2.dist-info
matplotlib_inline-0.1.3.dist-info
mypy_extensions-0.4.3.dist-info
nest_asyncio-1.5.4.dist-info
packaging-21.3.dist-info
parso-0.8.3.dist-info
pathspec-0.9.0.dist-info
pickleshare-0.7.5.dist-info
platformdirs-2.5.1.dist-info
prompt_toolkit-3.0.28.dist-info
pure_eval-0.2.2.dist-info
pycodestyle-2.8.0.dist-info
pyflakes-2.4.0.dist-info
Pygments-2.11.2.dist-info
pyparsing-3.0.7.dist-info
PyQt5-5.15.6.dist-info
PyQt5_Qt5-5.15.2.dist-info
PyQt5_sip-12.9.1.dist-info
pyserial-3.5.dist-info
python_dateutil-2.8.2.dist-info
pyzmq-22.3.0.dist-info
QScintilla-2.13.1.dist-info
qtconsole-5.2.2.dist-info
QtPy-2.0.1.dist-info
semver-2.13.0.dist-info
stack_data-0.2.0.dist-info
tomli-2.0.1.dist-info
tornado-6.1.dist-info
traitlets-5.1.1.dist-info
typing_extensions-4.1.1.dist-info
wcwidth-0.2.5.dist-info

~/.local/share/mu/mu_venv-39-20220226-213230/lib/python3.9/site-packages$ ls |grep "dist.info" 
asttokens-2.0.5.dist-info
backcall-0.2.0.dist-info
bitstring-3.1.9.dist-info
cffi-1.15.0.dist-info
click-8.0.4.dist-info
cryptography-36.0.1.dist-info
decorator-5.1.1.dist-info
ecdsa-0.17.0.dist-info
entrypoints-0.4.dist-info
esptool-3.2.dist-info
executing-0.8.2.dist-info
Flask-2.0.3.dist-info
ipykernel-5.5.6.dist-info
ipython-8.1.0.dist-info
ipython_genutils-0.2.0.dist-info
itsdangerous-2.1.0.dist-info
jedi-0.18.1.dist-info
Jinja2-3.0.3.dist-info
jupyter_client-7.1.2.dist-info
jupyter_core-4.9.2.dist-info
MarkupSafe-2.1.0.dist-info
matplotlib_inline-0.1.3.dist-info
nest_asyncio-1.5.4.dist-info
numpy-1.22.2.dist-info
parso-0.8.3.dist-info
pexpect-4.8.0.dist-info
pgzero-1.2.1.dist-info
pickleshare-0.7.5.dist-info
pip-20.3.4.dist-info
pkg_resources-0.0.0.dist-info
prompt_toolkit-3.0.28.dist-info
ptyprocess-0.7.0.dist-info
pure_eval-0.2.2.dist-info
pycparser-2.21.dist-info
pygame-2.1.2.dist-info
Pygments-2.11.2.dist-info
pyserial-3.5.dist-info
python_dateutil-2.8.2.dist-info
pyzmq-22.3.0.dist-info
reedsolo-1.5.4.dist-info
setuptools-60.9.3.dist-info
six-1.16.0.dist-info
stack_data-0.2.0.dist-info
tornado-6.1.dist-info
traitlets-5.1.1.dist-info
wcwidth-0.2.5.dist-info
Werkzeug-2.0.3.dist-info
wheel-0.34.2.dist-info

### Operating System Version

Debian 5.10

### Mu Version

1.1.1

**Comment by carlosperate** [comment]
Hi @ghollf,

This is by design, Mu creates a virtual environment to run the user code in isolation of Mu and it's Python environment, as you can install and uninstall packages within Mu itself without a virtualenv it would be too easy for users to accidentally install/uninstall packages that could affect Mu itself or the system packages.

Mu then installs inside this user virtual environment the dependencies required to run the different Mu modes like `ipython` for "Python mode" or `pygame` & `pgzero` for "Pygame Zero mode".
