### ISSUE TITLE
Deb packaging warning: badly formatted line on changelog

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#214]
When trying to build a .deb file I get the following warning:

```
...
parsechangelog/debian: warning: mu-0.9.13/debian/changelog(l5): badly formatted trailer line
LINE:  -- Nicholas Tollervey <ntoll@ntoll.org> Sun, 06 Oct 2016 11:32:58 +0000
...
```

Sounds a bit silly, but it might be that it needs a double white space before weekday.
I'm not quite sure when I'll be able to give this a try, but it is here for tracking and in case anybody else wants to give it a go.

**Comment by ntoll** [comment]
What's the command to make this happen?

**Comment by carlosperate** [comment]
You can see the build script I'm currently using here: https://github.com/carlosperate/mu/blob/pi_ci_scripts/package/pi_ci_scripts/build.sh

**Comment by ntoll** [comment]
aha! I knew it'd be somewhere.

**Comment by carlosperate** [comment]
Can confirm the warning does not appear any more with https://github.com/mu-editor/mu/commit/607bbb398add9072fe032a537e98941dd6cb06b4.
