### ISSUE TITLE
Check code should not highlight (trivial) whitespace issues

### ISSUE THREAD

**Issue by tjguk** [mu-editor/mu#219]
At present, the check code includes checks for trailing whitespace, including on blank lines. These cause red flags to appear when in fact there's no real issue (that any beginner need worry about). We should disable these checks and --optionally -- simply strip any trailing whitespace from lines as we save.

**Comment by NKT00** [comment]
Yes, it is maddening for things to fail for the reason of "Not a multiple of 4 whitespace"!

**Comment by ntoll** [comment]
Fixed. ;-) Closing.
