### ISSUE TITLE
Change the default python of MU to execute openpyxl

### ISSUE THREAD

**Issue by heather21327** [mu-editor/mu#2204]
### What were you trying to do?

execute openpyxl in mu

### What steps did you take to trigger the issue?

C:\Users\heath>pip install --user -U openpyxl==2.6.2
Requirement already satisfied: openpyxl==2.6.2 in c:\users\heath\appdata\roaming\python\python39\site-packages (2.6.2)
Requirement already satisfied: jdcal in c:\users\heath\appdata\roaming\python\python39\site-packages (from openpyxl==2.6.2) (1.4.1)
Requirement already satisfied: et_xmlfile in c:\users\heath\appdata\local\programs\python\python39\lib\site-packages (from openpyxl==2.6.2) (1.1.0)

Jupyter QtConsole 4.7.7
Python 3.8.11 (default, Jul 24 2021, 23:33:17) [MSC v.1929 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.

import openpyxl
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <module>
----> 1 import openpyxl

ModuleNotFoundError: No module named 'openpyxl'

### What actually happened?

![MU](https://user-images.githubusercontent.com/91174588/166170893-233aa509-252c-48f2-a4a9-c9609f5336eb.PNG)

### Mu Version

1.1.1

**Comment by carlosperate** [comment]
Hi @heather21327, thanks for the report!

As @ajs256 has mentioned (thanks!) you can install Python dependencies via the setting window. More info can be found here: https://codewith.mu/en/tutorials/1.1/pypi

I'll close this issue assuming this method will work for you, but please don't hesitate to reopen it if it doesn't work or you have any other questions.
