### ISSUE TITLE
mu.editor non si avvia dopo l'installazione

### ISSUE THREAD

**Issue by bnfgnn** [mu-editor/mu#2205]
### What were you trying to do?

ho installato mu-editor da Ubuntu Software

### What steps did you take to trigger the issue?

Installazione terminata senza errori.
Icona dell'editor presente tra i programmi ma non si avvia.

### What did you expect to happen?

Che il programma partisse

### What actually happened?

Al doppio click sull'icona non succede nulla.

### Operating System Version

Ubunto 22.04 LTS 

### Mu Version

22.04 LTS (64 bit)

### Other Info

Versione Python installata: 3.10.4

### Editor Log

non trovato percorso /.cache/mu/

**Comment by carlosperate** [comment]
Hi @bnfgnn,

I believe the issue you might be encountering is this one: https://github.com/mu-editor/mu/issues/2228

If you follow that link there are a couple of workaround that should be able to help you.

As we are tracking this problem over there I'll close this issue, but please feel free to reopen it if the workaround doesn't work, you need any help or have any questions.

Thanks for the report!
