### ISSUE TITLE
not opening

### ISSUE THREAD

**Issue by SANJAYNS1122009** [mu-editor/mu#2220]
### What were you trying to do?

open the app

### What steps did you take to trigger the issue?

just clicking in my applications I am using Ubuntu 22.04

### What did you expect to happen?

open the app and run properly

### What actually happened?

it is not opening.

### Operating System Version

ubuntu 22.04

### Mu Version

1.0.3+dfsg

**Comment by carlosperate** [comment]
Hi @SANJAYNS1122009, thanks for the report.

I believe the issue is this one: https://github.com/mu-editor/mu/issues/2228

There is a section with workaround that should help you launch Mu in the meantime, until the debian package can be updated.
