### ISSUE TITLE
Docs: AppImage additional instructions needed for Ubuntu 22.04

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#2223]
Until the libfuse2 dependency for AppImage is resolved (more info in https://github.com/AppImage/AppImageKit/issues/877#issuecomment-1114252750 and [Ubuntu issue](https://bugs.launchpad.net/ubuntu/+source/ubuntu-meta/+bug/1965636)), we need to add an additional step for Ubuntu 22.04 (and any distros shipping without it):

```
sudo apt install libfuse2
```

Apart from that, there is an issue (I think this is Mu-specific, not related to AppImage, so hopefully it can be fixed in the Mu source code by setting QT env variables internally), where launching the AppImage as it is doesn't currently work:

```
$ ./Mu_Editor-x86_64.AppImage 
No settings file found at /home/carlos/.local/share/mu/venv.json; skipping
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Segmentation fault (core dumped)
```

This is discussed in https://github.com/mu-editor/mu/discussions/1402#discussioncomment-2439978.

To launch Mu successfully it needs to be launched with this env variable set:

```
$ QT_QPA_PLATFORM=wayland ./Mu_Editor-x86_64.AppImage 
```

**Comment by carlosperate** [comment]
Interestingly about the `QT_QPA_PLATFORM=wayland`  en var, running Mu from source code and these three configurations seem to work (even if they print warnings on the terminal):

```
$ python run.py

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
libGL error: pci id for fd 23: 1ab8:0010, driver (null)
pci id for fd 24: 1ab8:0010, driver (null)
```

```
$ QT_QPA_PLATFORM=wayland python run.py 

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
libEGL warning: pci id for fd 13: 1ab8:0010, driver (null)

pci id for fd 14: 1ab8:0010, driver (null)
```


```
$ QT_QPA_PLATFORM=xcb python run.py 

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
libGL error: pci id for fd 23: 1ab8:0010, driver (null)
pci id for fd 24: 1ab8:0010, driver (null)

```

```
$ env -u WAYLAND_DISPLAY  python run.py 

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
libGL error: pci id for fd 22: 1ab8:0010, driver (null)
pci id for fd 23: 1ab8:0010, driver (null)
```

**Comment by tmontes** [comment]
Docs have been updated to include some distribution-specific details (see https://github.com/mu-editor/mu-editor.github.io/pull/70).

**Comment by carlosperate** [comment]
That's great, thanks @tmontes! 🎉
