### ISSUE TITLE
Add additional night mode

### ISSUE THREAD

**Issue by obrasier** [mu-editor/mu#233]
I think the current dark mode could be improved by having a high-contrast mode for the vision impaired, as well as a night mode with pretty syntax highlighting. (e.g. Sublime Text)

See my picture for comments:
![mu_dark_mode](https://cloud.githubusercontent.com/assets/4486457/22179047/1eacaac0-e09c-11e6-9c18-3b2a1ac11738.png)

**Comment by carlosperate** [comment]
Thanks for the feedback Owen, as discussed in the slack channel we can definitely rotate between themes on each click to the toolbar button.

Adding this should also clarify the difference between a dark theme and high contrast, so we should probably also do some work to use less shades of grey on dark contrast.

P.D. @ZanderBrown (writing this here as there is no privates in GH): are you aware of the [microbit slack channel](http://tech.microbit.org/get-involved/where-to-find/)?

**Comment by ZanderBrown** [comment]
I had heard it mentioned

**Comment by ntoll** [comment]
Done. Closing. See latest beta builds.
