### ISSUE TITLE
python compatibility 3.10

### ISSUE THREAD

**Issue by TecDroiD** [mu-editor/mu#2344]
Hi,
I just wanted to get mu via pip3 and got the error
```
ERROR: Ignored the following versions that require a different python version: 1.1.0b2 Requires-Python >=3.5,<3.9; 1.1.0b3 Requires-Python >=3.5,<3.9; 1.1.0b4 Requires-Python >=3.5,<3.9; 1.1.0b5 Requires-Python >=3.5,<3.9; 1.1.0b6 Requires-Python >=3.5,<3.9; 1.1.0b7 Requires-Python >=3.5,<3.9; 1.1.1 Requires-Python >=3.5,<3.9
ERROR: Could not find a version that satisfies the requirement mu-editor (from versions: 1.0.0b12, 1.0.0b13, 1.0.0b14, 1.0.0b15, 1.0.0b16, 1.0.0b17, 1.0.0rc1, 1.0.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for mu-editor
```

Can you please add compatibility to Python 3.10? Since there have not been any removals in 3.10 (as far as I know) it should just be adding 3.10 to Requires-Python

**Comment by carlosperate** [comment]
Hi TecDroid,

In an ideal world it'd just be changing the `requires-python`, but mostly we are stuck in these Python versions until we update some of the dependencies, and updating the dependencies will break compatibility with older Python versions and older operating systems, so we are holding off doing that until the next v1.2 release. Once that is out, we'll update the dependencies and the Python version compatibility.
