### ISSUE TITLE
mu-editor on Ubuntu 22.04 WITHOUT Wayland

### ISSUE THREAD

**Issue by agutierrm** [mu-editor/mu#2350]
Hi there, we are using mu-editor on our Linux lab on University. We are on Ubuntu 22.04 jammy jellyfish, and we have downloaded the AppImage file of mu-editor 1.1. Some of our computers runs x11 wihtout Wayland, because they are using nvidia drivers. 

So, is possible to run mu-editor 1.1.1 WITHOUT Wayland? For me it's impossible to run. And, also I have discovered that pip install mu-editor doesnt works:

`pip install mu-editor                                         
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement mu-editor (from versions: 1.0.0b12, 1.0.0b13, 1.0.0b14, 1.0.0b15, 1.0.0b16, 1.0.0b17, 1.0.0rc1, 1.0.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for mu-editor`

This is normal? Thank you so much.

**Comment by carlosperate** [comment]
How have you tried to run the AppImage? Just double clicking on it?

Have you run them from the command line? do they throw any error?

Usually the problem we encounter is launching the AppImage **with** wayland.

Can you try running it with these two environemntal variables to see if they run?
```
QT_QPA_PLATFORM=xcb ./Mu_Editor-1.1.1-x86_64.AppImage
```
```
QT_QPA_PLATFORM=wayland ./Mu_Editor-1.1.1-x86_64.AppImage
```

**Comment by agutierrm** [comment]
Hello @carlosperate , thanks for your answer. 

I am running Ubuntu 22.04 LTS with nvidia driver, not using Wayland (x11). XDG_SESSION_TYPE contents "x11" value.

So, Im running : ./Mu_Editor-1.1.1-x86_64.AppImage A window appears asking for "Only run" or "Integrate and run" (I have translated from spanish, maybe with english language is different). If I click on "Only run" nothing happens. This window dissapears. No message in terminal.

If I run with: QT_QPA_PLATFORM=xcb ./Mu_Editor-1.1.1-x86_64.AppImage the behaviour is the same. Nothing happens. 

:-(

**Comment by KGOrphanides** [comment]
I'm also affected by this, running Pop!_OS 22.04. Although I'm on AMD graphics hardware, I have a specific setup on my primary workstation that precludes using Wayland right now. 

Given the popularity of xorg, I presume that someone must have a viable workaround? 
*looks hopefully into the void*

**Comment by dhalbert** [comment]
Related: #2318.

**Comment by carlosperate** [comment]
Yes, thanks @dhalbert!

@agutierrm @KGOrphanides if you could check if this test AppImage works in your environment that'd be great!

You'll need to be logged into GitHub to be able to click on the download link from this page:
https://github.com/mu-editor/mu/actions/runs/3479069676
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/4189262/202176725-94239358-a1ef-40f1-aa8e-b4cc4b309264.png">

**Comment by ntoll** [comment]
Bravo @carlosperate and hurrah @agutierrm ... best of luck with your students..! :tada:

**Comment by KGOrphanides** [comment]
Working here, too. Thank you, @carlosperate !

**Comment by carlosperate** [comment]
Thanks everyone! I'll close this issue as resolved and the fix will be shipped in the next release 👍

**Comment by RasheedAZ** [comment]
> How have you tried to run the AppImage? Just double clicking on it?
> 
> Have you run them from the command line? do they throw any error?
> 
> Usually the problem we encounter is launching the AppImage **with** wayland.
> 
> Can you try running it with these two environemntal variables to see if they run?
> 
> ```
> QT_QPA_PLATFORM=xcb ./Mu_Editor-1.1.1-x86_64.AppImage
> ```
> 
> ```
> QT_QPA_PLATFORM=wayland ./Mu_Editor-1.1.1-x86_64.AppImage
> ```

``It's not working for me either. Tried both variables. Pop!_OS 22.04

No settings file found at /home/az/.local/share/mu/venv.json; skipping
Segmentation fault (core dumped)``
