### ISSUE TITLE
MuEditor-OSX being flagged on Virus Total

### ISSUE THREAD

**Issue by paul-cossey** [mu-editor/mu#2356]
### What were you trying to do?

Checking for malicious software. 

### What steps did you take to trigger the issue?

Not really a bug, but...

Before we install new software/updates on customer computers we automatically check the downloads with [https://www.virustotal.com](https://www.virustotal.com) 

Both of your latest releases are being flagged by a couple of vendors. I think they're false positives, but you may wish to work with them so that Mu doesn't get flagged in future.

MuEditor-OSX-1.1.1.dmg: https://www.virustotal.com/gui/file/3cb81559e97ee8813d126810fb11f981b32981d22e1767204f43b1a33f6e9f11/detection/f-3cb81559e97ee8813d126810fb11f981b32981d22e1767204f43b1a33f6e9f11-1667740410

MuEditor-OSX-1.2.0.dmg: https://www.virustotal.com/gui/file/306bef4ebfafd1dcf928bc260d5d57e64efbccb537b27f5818a9fc12437726b6

### What did you expect to happen?

Security vendors to pass the App

### What actually happened?

Flagged

### Operating System Version

macOS

### Mu Version

1.1.1 and 1.2.0

### Other Info

N/A

### Editor Log

N/A

**Comment by ntoll** [comment]
Hi @paul-cossey - thank you so much for letting us know about this. I've reached out to their technical support and will post updates to this thread if/when they respond.

N.

**Comment by paul-cossey** [comment]
Latest version is no longer being flagged. Thanks. 😄 

https://www.virustotal.com/gui/file/306bef4ebfafd1dcf928bc260d5d57e64efbccb537b27f5818a9fc12437726b6
