### ISSUE TITLE
mu crashes when opening a file with unexpected encoding

### ISSUE THREAD

**Issue by inglesp** [mu-editor/mu#236]
When mu tries to open a file in an unexpected encoding, it crashes.  Instead, it should tell the user what's happened.

**Comment by carlosperate** [comment]
We need to investigate a bit further to find out what exactly is crashing, in linux and windows what I've seen in some cases is the character not being rendered as expected (like shown by @deshipu in https://github.com/mu-editor/mu/issues/231#issuecomment-273826614), which is the same way most editors I have ever used react.

**Comment by carlosperate** [comment]
This has been resolved by the fantastic encoding work done by @tjguk, so we can close this one.
