### ISSUE TITLE
mu will crash on saving or loading a file when the encoding is unexpected

### ISSUE THREAD

**Issue by inglesp** [mu-editor/mu#237]
If the system's preferred encoding is not utf-8 then loading or saving a file containing unicode will cause mu to crash.

@ntoll says that he "[like[s] the idea of enforcing utf-8](https://github.com/mu-editor/mu/issues/231#issuecomment-274045430)", in which case we should apply @carlosperate's [experimental fix here](https://github.com/mu-editor/mu/commit/e6f637f867509464b7ba9eb814ef16ced043ef92).

This will mitigate problems like #231, but we'll still have problems when trying to open a file that's not in utf-8, if for example it's been produced by another text editor.  I have opened #236 to track this.

**Comment by ntoll** [comment]
Fixed by the godlike @tjguk --- apologies for not closing / referencing in this issue. :-/
