### ISSUE TITLE
Dutch translation reviewed

### ISSUE THREAD

**Issue by pygamegirl** [mu-editor/mu#2380]
Hi

I reviewed the Dutch translation and it's OK!

https://github.com/mu-editor/mu/pull/2111

It can be added in the next version.

**Comment by carlosperate** [comment]
Thanks @pygamegirl!
@ntoll has merged PR https://github.com/mu-editor/mu/pull/2111, so we can consider this tasks done 🎉

**Comment by pygamegirl** [comment]
great!!!
