### ISSUE TITLE
How to use in Ubuntu 16.04 64bit???

### ISSUE THREAD

**Issue by KimHwaMok** [mu-editor/mu#239]
I tried "python3 run.py" but "ImportError: No module named 'pyQt5'"
so I installed "sudo apt-get install python-qt4"
but same happen again.

How to use in Ubuntu 16.04 64bit?

and I want to modify the menu of mu-editor to support various languages.
I know which module is defined. but, I wonder how I rebuild the source code if I change the source code.

**Comment by ntoll** [comment]
Hi,

Check out the developer instructions in the README. Essentially you need: python3-pyqt5, python3-pyqt5.qsci and python3-pyqt5.qtserialport

**Comment by KimHwaMok** [comment]
@ntoll 
hi, thank you so much for reply.
I have completed the installation for the mentioned things to solve all dependency problems.
error code is "No module named 'pyQt5.Qsci'"
so I tried to "apt-get install python3-pyqt5.qsci" but same happen.

**Comment by ZanderBrown** [comment]
have you tryed `sudo pip install requirements.txt` followed by `sudo python3 setup.py install`

**Comment by carlosperate** [comment]
Are you sure you are using Python 3? So running `python3 run.py` instead of `python run.py`?

Could you execute the following lines individually in the command line:

```
python3 -c "import PyQt5;print('PyQt5 installed')"
```

```
python3 -c "import PyQt5.Qsci;print('Qsci installed')"
```

```
python3 -c "import PyQt5.QtSerialPort;print('QtSerialPort installed')"
```
