### ISSUE TITLE
i can't download mu 64 bits

### ISSUE THREAD

**Issue by nazha7** [mu-editor/mu#2402]

**Comment by carlosperate** [comment]
Hi @nazha7,
I'll the links in https://codewith.mu/en/download seem to be working. How did you try to download Mu?

**Comment by calli299** [comment]
I cant download either 
![GitHub Support and 6 more pages - Personal - Microsoft​ Edge 5_5_2023 4_57_44 AM (2)](https://user-images.githubusercontent.com/127318744/236424733-cce8329d-f24a-4828-adde-892f2807e96d.png)

**Comment by ntoll** [comment]
@calli299 this appears to be because your computer is managed / limited in some way to only allow official downloads. Please speak to your system administrator to fix this.

**Comment by calli299** [comment]
I am the admin of my pc and I don't know where to go to fix it

**Comment by ntoll** [comment]
It's probably your virus checking software.

**Comment by calli299** [comment]
I turned it off, still the same

**Comment by calli299** [comment]
Thank you, I have it installed

**Comment by xbecas** [comment]
Closing - all ended well.

Enjoy Mu and please share suggestions and bugs you may find.
