### ISSUE TITLE
Mu screen-center PGZ

### ISSUE THREAD

**Issue by humpda** [mu-editor/mu#2404]
Hi everyone
I have seen a few comments about this, but not sure if I am missing something.  When we run a PGZ project, the top left game Window spawn from the screen centre, meaning a chunk of the game can be off the screen. I believe a fix was in the work from a pervious post in 2022. Has anyone got a work-around that I can test?

Thanks
Humpda

**Comment by xbecas** [comment]
Hi @humpda. Thanks for your input. Please check #2086 for some links with extra details on the matter.

It seems to be a pygame zero issue, with a fix proposed on the following link (yet to be merged)
https://github.com/lordmauve/pgzero/commit/bf48fc964b5168d8e1e101a32adc2ac6cb685c69

You can try to update your local files with the proposed fixes and see if it solves the issue.

Hope it helps. Cheers.
