### ISSUE TITLE
EASIEST THING BUT DOSENT WORK

### ISSUE THREAD

**Issue by ethantse** [mu-editor/mu#2411]
### What were you trying to do?

I was trying to make a forever game loop.

### What steps did you take to trigger the issue?

i put
`poop = 5
while poop != 0:
   print('poop')`   
easy right?
but it dsays
`  File "c:\users\hp\mu_code\game2.py", line 86
    poop = 6
    ^
SyntaxError: invalid syntax
>>> `

### What did you expect to happen?

forever print'poop'.

### Mu Version

1.2.0

**Comment by dsssssssss9** [comment]
Hi

You need to put each part on its own line ....

`poop = 5

while poop != 0:

    print('poop')`
