### ISSUE TITLE
I can't find running button in Chinese version

### ISSUE THREAD

**Issue by Tina2023H** [mu-editor/mu#2470]
I installed it 
![no run button](https://github.com/mu-editor/mu/assets/151191555/0d24406b-3ee8-4b41-b440-aa50223982c3)
and opened it. But I can't see the running button.

**Comment by carlosperate** [comment]
Hi @Tina2023H,
If the Mu Editor is in CircuitPython mode the code is run every time is saved inside the CIRCUITPY drive.

**Comment by carlosperate** [comment]
I'll close this as resolved, but feel free to open a thread in the [Discussions tab](https://github.com/mu-editor/mu/discussions) if you any other questions 👍
