### ISSUE TITLE
ERROR: No matching distribution found for pup

### ISSUE THREAD

**Issue by roboticsware** [mu-editor/mu#2473]
### What were you trying to do?

make win64

### What steps did you take to trigger the issue?

1. Made virtual env with Python 3.8 by minoconda
2. Installed dependancies by the command, pip install -e ".[dev]"
3. Tried to build win64 version

### What did you expect to happen?

No build error

### What actually happened?

subprocess.CalledProcessError: Command '['./venv-pup/Scripts/pip.exe', 'install', 'pup']' returned non-zero exit status 1.

### Operating System Version

Windows 10

### Mu Version

1.2

### Editor Log

(mu) C:\dev\mu>python make.py win64
Fetching wheels
Downloading wheels to C:\dev\mu\mu\wheels\1.2.2.zip
Removing wheel/sdist files from C:\dev\mu\mu\wheels
Removing existing wheel/sdist C:\dev\mu\mu\wheels\1.2.2.zip
Running pip download for pgzero / ('pgzero>=1.2.1', 'pygame<2.1.3') / [] / []
Looking in links: c:\Users\JJ\AppData\Local\Temp\tmp4yt8al82
Collecting pgzero>=1.2.1
  Using cached pgzero-1.2.1-py3-none-any.whl (71 kB)
Collecting pygame<2.1.3
  Using cached pygame-2.1.2-cp38-cp38-win_amd64.whl (8.4 MB)
Collecting numpy (from pgzero>=1.2.1)
  Using cached numpy-1.24.4-cp38-cp38-win_amd64.whl.metadata (5.6 kB)
Using cached numpy-1.24.4-cp38-cp38-win_amd64.whl (14.9 MB)
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\pgzero-1.2.1-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\pygame-2.1.2-cp38-cp38-win_amd64.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\numpy-1.24.4-cp38-cp38-win_amd64.whl
Successfully downloaded pgzero pygame numpy
Running pip download for flask / ('flask==2.0.3', 'Werkzeug<3.0.0') / [] / []
Looking in links: c:\Users\JJ\AppData\Local\Temp\tmp4yt8al82
Collecting flask==2.0.3
  Using cached Flask-2.0.3-py3-none-any.whl (95 kB)
Collecting Werkzeug<3.0.0
  Using cached werkzeug-2.3.8-py3-none-any.whl.metadata (4.1 kB)
Collecting Jinja2>=3.0 (from flask==2.0.3)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting itsdangerous>=2.0 (from flask==2.0.3)
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting click>=7.1.2 (from flask==2.0.3)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting MarkupSafe>=2.1.1 (from Werkzeug<3.0.0)
  Using cached MarkupSafe-2.1.3-cp38-cp38-win_amd64.whl.metadata (3.1 kB)
Collecting colorama (from click>=7.1.2->flask==2.0.3)
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached werkzeug-2.3.8-py3-none-any.whl (242 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached MarkupSafe-2.1.3-cp38-cp38-win_amd64.whl (17 kB)
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\flask-2.0.3-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\werkzeug-2.3.8-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\click-8.1.7-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\itsdangerous-2.1.2-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\jinja2-3.1.2-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\markupsafe-2.1.3-cp38-cp38-win_amd64.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\colorama-0.4.6-py2.py3-none-any.whl
Successfully downloaded flask Werkzeug click itsdangerous Jinja2 MarkupSafe colorama
Running pip download for ipykernel / ('ipykernel>=4.1,<6',) / [] / []
Looking in links: c:\Users\JJ\AppData\Local\Temp\tmp4yt8al82
Collecting ipykernel<6,>=4.1
  Using cached ipykernel-5.5.6-py3-none-any.whl (121 kB)
Collecting ipython-genutils (from ipykernel<6,>=4.1)
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting ipython>=5.0.0 (from ipykernel<6,>=4.1)
  Using cached ipython-8.12.3-py3-none-any.whl.metadata (5.7 kB)
Collecting traitlets>=4.1.0 (from ipykernel<6,>=4.1)
  Using cached traitlets-5.13.0-py3-none-any.whl.metadata (10 kB)
Collecting jupyter-client (from ipykernel<6,>=4.1)
  Using cached jupyter_client-8.6.0-py3-none-any.whl.metadata (8.3 kB)
Collecting tornado>=4.2 (from ipykernel<6,>=4.1)
  Using cached tornado-6.3.3-cp38-abi3-win_amd64.whl.metadata (2.6 kB)
Collecting backcall (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting decorator (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting jedi>=0.16 (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting matplotlib-inline (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting pickleshare (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached prompt_toolkit-3.0.41-py3-none-any.whl.metadata (6.5 kB)
Collecting pygments>=2.4.0 (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting stack-data (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached stack_data-0.6.3-py3-none-any.whl.metadata (18 kB)
Collecting typing-extensions (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting colorama (from ipython>=5.0.0->ipykernel<6,>=4.1)
  File was already downloaded c:\users\jj\appdata\local\temp\tmp4yt8al82\colorama-0.4.6-py2.py3-none-any.whl
Collecting importlib-metadata>=4.8.3 (from jupyter-client->ipykernel<6,>=4.1)
  Using cached importlib_metadata-6.8.0-py3-none-any.whl.metadata (5.1 kB)
Collecting jupyter-core!=5.0.*,>=4.12 (from jupyter-client->ipykernel<6,>=4.1)
  Using cached jupyter_core-5.5.0-py3-none-any.whl.metadata (3.4 kB)
Collecting python-dateutil>=2.8.2 (from jupyter-client->ipykernel<6,>=4.1)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pyzmq>=23.0 (from jupyter-client->ipykernel<6,>=4.1)
  Using cached pyzmq-25.1.1-cp38-cp38-win_amd64.whl.metadata (5.1 kB)
Collecting zipp>=0.5 (from importlib-metadata>=4.8.3->jupyter-client->ipykernel<6,>=4.1)
  Using cached zipp-3.17.0-py3-none-any.whl.metadata (3.7 kB)
Collecting parso<0.9.0,>=0.8.3 (from jedi>=0.16->ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting platformdirs>=2.5 (from jupyter-core!=5.0.*,>=4.12->jupyter-client->ipykernel<6,>=4.1)
  Using cached platformdirs-4.0.0-py3-none-any.whl.metadata (11 kB)
Collecting pywin32>=300 (from jupyter-core!=5.0.*,>=4.12->jupyter-client->ipykernel<6,>=4.1)
  Using cached pywin32-306-cp38-cp38-win_amd64.whl (9.4 MB)
Collecting wcwidth (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached wcwidth-0.2.12-py2.py3-none-any.whl.metadata (14 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->jupyter-client->ipykernel<6,>=4.1)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting executing>=1.2.0 (from stack-data->ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached executing-2.0.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting asttokens>=2.1.0 (from stack-data->ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached asttokens-2.4.1-py2.py3-none-any.whl.metadata (5.2 kB)
Collecting pure-eval (from stack-data->ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Using cached ipython-8.12.3-py3-none-any.whl (798 kB)
Using cached tornado-6.3.3-cp38-abi3-win_amd64.whl (429 kB)
Using cached traitlets-5.13.0-py3-none-any.whl (84 kB)
Using cached jupyter_client-8.6.0-py3-none-any.whl (105 kB)
Using cached importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
Using cached jupyter_core-5.5.0-py3-none-any.whl (28 kB)
Using cached prompt_toolkit-3.0.41-py3-none-any.whl (385 kB)
Using cached pygments-2.17.2-py3-none-any.whl (1.2 MB)
Using cached pyzmq-25.1.1-cp38-cp38-win_amd64.whl (1.2 MB)
Using cached stack_data-0.6.3-py3-none-any.whl (24 kB)
Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Using cached asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
Using cached executing-2.0.1-py2.py3-none-any.whl (24 kB)
Using cached platformdirs-4.0.0-py3-none-any.whl (17 kB)
Using cached zipp-3.17.0-py3-none-any.whl (7.4 kB)
Using cached wcwidth-0.2.12-py2.py3-none-any.whl (34 kB)
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\ipykernel-5.5.6-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\ipython-8.12.3-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\tornado-6.3.3-cp38-abi3-win_amd64.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\traitlets-5.13.0-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\ipython_genutils-0.2.0-py2.py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\jupyter_client-8.6.0-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\importlib_metadata-6.8.0-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\jedi-0.19.1-py2.py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\jupyter_core-5.5.0-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\prompt_toolkit-3.0.41-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\pygments-2.17.2-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\python_dateutil-2.8.2-py2.py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\pyzmq-25.1.1-cp38-cp38-win_amd64.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\backcall-0.2.0-py2.py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\decorator-5.1.1-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\matplotlib_inline-0.1.6-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\pickleshare-0.7.5-py2.py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\stack_data-0.6.3-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\typing_extensions-4.8.0-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\asttokens-2.4.1-py2.py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\executing-2.0.1-py2.py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\parso-0.8.3-py2.py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\platformdirs-4.0.0-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\pywin32-306-cp38-cp38-win_amd64.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\six-1.16.0-py2.py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\zipp-3.17.0-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\pure_eval-0.2.2-py3-none-any.whl
Saved c:\users\jj\appdata\local\temp\tmp4yt8al82\wcwidth-0.2.12-py2.py3-none-any.whl
Successfully downloaded ipykernel ipython tornado traitlets ipython-genutils jupyter-client importlib-metadata jedi jupyter-core prompt-toolkit pygments python-dateutil pyzmq backcall colorama decorator matplotlib-inline pickleshare stack-data typing-extensions asttokens executing parso platformdirs pywin32 six zipp pure-eval wcwidth
Running pip download for ipython_genutils / ('ipython_genutils>=0.2.0',) / [] / []
Looking in links: c:\Users\JJ\AppData\Local\Temp\tmp4yt8al82
Collecting ipython_genutils>=0.2.0
  File was already downloaded c:\users\jj\appdata\local\temp\tmp4yt8al82\ipython_genutils-0.2.0-py2.py3-none-any.whl
Successfully downloaded ipython_genutils
Building zip C:\dev\mu\mu\wheels\1.2.2.zip from wheels in C:\Users\JJ\AppData\Local\Temp\tmp4yt8al82
Adding asttokens-2.4.1-py2.py3-none-any.whl to zip
Adding backcall-0.2.0-py2.py3-none-any.whl to zip
Adding click-8.1.7-py3-none-any.whl to zip
Adding colorama-0.4.6-py2.py3-none-any.whl to zip
Adding decorator-5.1.1-py3-none-any.whl to zip
Adding executing-2.0.1-py2.py3-none-any.whl to zip
Adding Flask-2.0.3-py3-none-any.whl to zip
Adding importlib_metadata-6.8.0-py3-none-any.whl to zip
Adding ipykernel-5.5.6-py3-none-any.whl to zip
Adding ipython-8.12.3-py3-none-any.whl to zip
Adding ipython_genutils-0.2.0-py2.py3-none-any.whl to zip
Adding itsdangerous-2.1.2-py3-none-any.whl to zip
Adding jedi-0.19.1-py2.py3-none-any.whl to zip
Adding Jinja2-3.1.2-py3-none-any.whl to zip
Adding jupyter_client-8.6.0-py3-none-any.whl to zip
Adding jupyter_core-5.5.0-py3-none-any.whl to zip
Adding MarkupSafe-2.1.3-cp38-cp38-win_amd64.whl to zip
Adding matplotlib_inline-0.1.6-py3-none-any.whl to zip
Adding numpy-1.24.4-cp38-cp38-win_amd64.whl to zip
Adding parso-0.8.3-py2.py3-none-any.whl to zip
Adding pgzero-1.2.1-py3-none-any.whl to zip
Adding pickleshare-0.7.5-py2.py3-none-any.whl to zip
Adding platformdirs-4.0.0-py3-none-any.whl to zip
Adding prompt_toolkit-3.0.41-py3-none-any.whl to zip
Adding pure_eval-0.2.2-py3-none-any.whl to zip
Adding pygame-2.1.2-cp38-cp38-win_amd64.whl to zip
Adding pygments-2.17.2-py3-none-any.whl to zip
Adding python_dateutil-2.8.2-py2.py3-none-any.whl to zip
Adding pywin32-306-cp38-cp38-win_amd64.whl to zip
Adding pyzmq-25.1.1-cp38-cp38-win_amd64.whl to zip
Adding six-1.16.0-py2.py3-none-any.whl to zip
Adding stack_data-0.6.3-py3-none-any.whl to zip
Adding tornado-6.3.3-cp38-abi3-win_amd64.whl to zip
Adding traitlets-5.13.0-py3-none-any.whl to zip
Adding typing_extensions-4.8.0-py3-none-any.whl to zip
Adding wcwidth-0.2.12-py2.py3-none-any.whl to zip
Adding werkzeug-2.3.8-py3-none-any.whl to zip
Adding zipp-3.17.0-py3-none-any.whl to zip
Building 64-bit Windows installer
Running: C:\Users\JJ\miniconda3\envs\mu\python.exe -m virtualenv venv-pup
created virtual environment CPython3.8.18.final.0-64 in 1246ms
  creator CPython3Windows(dest=C:\dev\mu\venv-pup, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\JJ\AppData\Local\pypa\virtualenv)
    added seed packages: pip==23.3.1, setuptools==68.2.2, wheel==0.41.3
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Running: ./venv-pup/Scripts/pip.exe install pup
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the 
SSL module is not available.")': /simple/pup/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the 
SSL module is not available.")': /simple/pup/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the 
SSL module is not available.")': /simple/pup/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the 
SSL module is not available.")': /simple/pup/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the 
SSL module is not available.")': /simple/pup/
Could not fetch URL https://pypi.org/simple/pup/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pup/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement pup (from versions: none)
ERROR: No matching distribution found for pup
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Traceback (most recent call last):
  File "make.py", line 501, in <module>
    sys.exit(main(*sys.argv[1:]))
  File "make.py", line 497, in main
    return function(*args)
  File "make.py", line 453, in win64
    _build_windows_msi(bitness=64)
  File "make.py", line 439, in _build_windows_msi
    subprocess.check_call(cmd)
  File "C:\Users\JJ\miniconda3\envs\mu\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./venv-pup/Scripts/pip.exe', 'install', 'pup']' returned non-zero exit status 1.

**Comment by carlosperate** [comment]
Thanks for the report @roboticsware, just in case this happened to be an intermitent connection error, have you tried again since the issue was opened? Do you still get the same error?

**Comment by roboticsware** [comment]
I fixed it by https://github.com/conda/conda/issues/8273.
