### ISSUE TITLE
Flake issues are hidden by PEP8 issues

### ISSUE THREAD

**Issue by tjguk** [mu-editor/mu#256]
Because the Flake and PEP8 issue markers are applied one after the other in logic:check_code any PEP8 issues for a line will overwrite any Flake issues already applied for the same line.

To see this in action:
* Create a new file
* Enter the word "blah" (or some other nonsense)
* Press the [Check] button

The error which is indicated complains that there is no newline at the end of the file, and totally ignores that NameError!

**Comment by ntoll** [comment]
Ooh... good catch! :-)

**Comment by moshez** [comment]
Does not reproduce for me.

![screenshot from 2018-05-27 19-36-51](https://user-images.githubusercontent.com/422703/40594681-602a1e9e-61e5-11e8-94f6-d61e41ad2218.png)

This is running on Linux, directly from master, git revision 6c6921f0fec3f9d36cf9a8e022fe254d7da6c83e

**Comment by ntoll** [comment]
This has been fixed. Closing. Thanks for the report and check. :-)
