### ISSUE TITLE
Remove comments before flashing program

### ISSUE THREAD

**Issue by webmaster442** [mu-editor/mu#258]
Comments should be removed before flashing program to the microbit, to save space.

**Comment by ZanderBrown** [comment]
This has been brought up before.

Is it something you could add in a PR?

**Comment by carlosperate** [comment]
I'd be against removing comments unless is absolutely necessary, and even when doing so there should be a warning to the user of what's about to happen. This is because the script can be recovered from the .hex file output.
This is also discussed in https://github.com/mu-editor/mu/issues/192.

**Comment by kamar535** [comment]
Just got hit by this when developing an assignment for my students. In the source I've have plenty of comments for documenting the API's of functions etc.

**Comment by rhubarbdog** [comment]
write a sed script to rip comments out `sed 's/\( *#.*\)//' my-file.py > comment-free.py`

**Comment by kamar535** [comment]
@rhubarbdog The comments serves a purpose during reading/editing the source and I would prefer if Mu had an option to remove the comments prior to flashing the program to the Microbit.  Using an external tool, for example sed, to remove the comments before loading the file in Mu is not an ideal workflow for (novice) students.

**Comment by carlosperate** [comment]
The master branch now offers the option in the settings to minify the micro:bit Python code (added in https://github.com/mu-editor/mu/commit/bf8bb7586e37f51e3f7434f17bb56e996eaf1f28), and will be included in the next release of Mu:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/4189262/38954330-3d8f481a-4349-11e8-8f64-9f1298e503c0.png">
I'll close this issue, but please feel free to reopen if you have any questions or suggestions.

**Comment by kamar535** [comment]
This is great!
