### ISSUE TITLE
Pop up help for radio.init() shows spi.init() help

### ISSUE THREAD

**Issue by DavidWhaleMEF** [mu-editor/mu#262]
Mu version: https://codewith.mu/help/0.9.13/

When I use the pop up help in Mu on the radio module, the init() incorrectly shows the help for the spi.init() method

![screen shot 2017-04-19 at 08 24 01](https://cloud.githubusercontent.com/assets/25079586/25167992/b4df96e8-24d9-11e7-9c74-a5b57538fcda.png)

**Comment by DavidWhaleMEF** [comment]
Clearly I should be using radio.config()

But I didn't understand why it offered me spi help for the radio module in the first place?

**Comment by ntoll** [comment]
We've known about this for a while, and when I investigated it found that it is a limit of the underlying Scintilla widget. Without re-writing it all from scratch there's nothing we can really do about it. :-(
