### ISSUE TITLE
Open file from command line

### ISSUE THREAD

**Issue by peter-jensen** [mu-editor/mu#268]
Unable to open a file from the command line. Double clicking on a python script does therefore not work.
I.e ./run.py test.py does not open file.
Version of "mu".  37f4c7e365797151bfdd32b143098d0a7cd0f033
Platform Ubuntu 16.04.

**Comment by ZanderBrown** [comment]
Good one, this should probably be a priority with our change of focus

**Comment by peter-jensen** [comment]
If files can be opened by clicking on them, then there is a high probability that several invocations of the editor may exist. This could affect common resources such as .local/share/mu/settings.json and .cache/mu/log/mu.log.

**Comment by ZanderBrown** [comment]
Single instance is probably worth looking into

**Comment by carlosperate** [comment]
Implemented in #270, thanks @matt-land!
