### ISSUE TITLE
no control over creating code folder location

### ISSUE THREAD

**Issue by scruss** [mu-editor/mu#277]
It makes `~/mu_code`, and there's no obvious way to change it in the code pulled from git

**Comment by ZanderBrown** [comment]
workspace key in settings.json

Unmerged documentation update [here](https://github.com/mu-editor/help-pages/pull/1/files)

**Comment by carlosperate** [comment]
The PR https://github.com/mu-editor/help-pages/pull/1 has been merged already, but we don't yet have an entry for this key info, so I've created this issue https://github.com/mu-editor/help-pages/issues/2.
Let's leave this one open until the documentation is done.

**Comment by ntoll** [comment]
The documentation is in the new website (coming soon). Closing.
