### ISSUE TITLE
Update mu/package/icons with new logo

### ISSUE THREAD

**Issue by ntoll** [mu-editor/mu#284]
The icons found in `mu/package/icons` all use the old logo. Please update these to the new logo (see attached).
![icon](https://user-images.githubusercontent.com/37602/30643992-d27673fe-9e08-11e7-8a93-cb640d397e07.png)

**Comment by ZanderBrown** [comment]
Looks nice, not 'mu' as such but at least it's distinct from IDLE

**Comment by ntoll** [comment]
I wanted a snake to represent Python, but not the blue or yellow snakes from the official logo. "Mu" as in the Greek letter would be lost on most people. 

Also, I think she deserves a name! Pynelope perhaps..? ;-)

**Comment by ZanderBrown** [comment]
I like it but maybe we can come up with something that's got an obscure reference in it? (unless i'm missing something other than the py)

**Comment by ZanderBrown** [comment]
Neidr? Not so much a python reference but is apparently the welsh for snake (seems appropriate for a PyCon in Cardiff

**Comment by ntoll** [comment]
Penelope is the name of my daughter... :-P

Pynelope seems an appropriate name for another thing I've "fathered" into existence. Is that obscure enough. :-D

**Comment by ZanderBrown** [comment]
I'd say that's a good name then.

**Comment by ntoll** [comment]
Hehehehe... it's official then. My daughter will be both amused, embarrassed and slightly annoyed. 

I'm not going to mention it until PyCon UK (she's coming along to the kids' day). :-D

**Comment by carlosperate** [comment]
Awesome, which branch should I PR against? numu?

**Comment by ntoll** [comment]
Do it against master. I merged numu into that when I delivered the beta version (i.e. feature complete, needs testing / debugging) for RPi last week.

**Comment by carlosperate** [comment]
There will be no code updates, just icon files, so I'll commit directly to master if that's okay with you

**Comment by ntoll** [comment]
+1 and please feel free to close this issue when it's pushed. Thanks! :-)

**Comment by carlosperate** [comment]
Implemented in adef1daa756817d532edbfa36f0b3eddbfe0a07b :)
