### ISSUE TITLE
Using Mu to run Python on a PC?

### ISSUE THREAD

**Issue by iantresman** [mu-editor/mu#292]
Mu has a lovely interface. Is there a way to get it to run Mu-edited Python on a PC easily (ie. one click), rather than having to save to disk. Using IDLE is a bit clunky.

**Comment by ZanderBrown** [comment]
I believe this is supported in the upcoming release

**Comment by carlosperate** [comment]
If you like, you can try the current master of this repository, you should be able to start a project for Python running on your PC.

**Comment by ntoll** [comment]
You should be able to right-click and set Mu as the preferred application for opening Python files. In any case, @ZanderBrown is correct, Mu will now open files sent in its direction via the OS.
