### ISSUE TITLE
Load and Save don't update your "recent-files"

### ISSUE THREAD

**Issue by rhubarbdog** [mu-editor/mu#307]
When I click load there is the option to select from a number of folders or special option recent-files.
Neither load or save update recent files. I'm running Linux Mint 18.2

**Comment by ntoll** [comment]
This is something to do with your OS and Qt obviously doesn't interact with this feature (i.e. Mu causes Qt to open your OS's file select window).

**Comment by ntoll** [comment]
Marking as won't-fix since this appears to be a Qt rather than Mu related problem. Perhaps report this upstream to Qt (or PyQt)..? Thanks!

**Comment by ZanderBrown** [comment]
Recent files must be recorded explicitly, in Gtk it's achieved through `GtkRecentManager`

No idea about the PyQt world
