### ISSUE TITLE
Find teachers and other interested people to act as crash test dummies!

### ISSUE THREAD

**Issue by ntoll** [mu-editor/mu#31]
We should release early and release often. The sooner we get this project in front of teachers and other potential users the sooner we can get actionable feedback.

We should gather together a cohort of willing crash-test dummies who are willing to feel the pain of pre-Alpha software.

This groups must include:
- [ ] Teachers.
- [ ] Non-technical parents.
- [ ] School technicians and/or sys admins.
- [ ] Classroom assistants.
- [ ] Professional programmers who are not authoring this project.

We should include clear first steps instructions and a well defined mechanism for creating feedback and interacting with the project.

'nuff said. :-)

**Comment by jonwitts** [comment]
Happy to be one of your crash test dummies!

**Comment by ZanderBrown** [comment]
Not sure I want to be a 'crash test dummy' as such but ill happy test mu

**Comment by ntoll** [comment]
Great stuff... there will be a new release soon and I'll ping you when we get close. ;-)

**Comment by ntoll** [comment]
"Fixed" by modus operandi explained here: https://mu.readthedocs.io/en/latest/user-experience.html
