### ISSUE TITLE
Documentation needed: How to use a different version of micro:bit MicroPython

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#313]
We need to document how to use a different version of MicroPython with Mu, this will be specially useful for testing beta releases and similar.

The simplest way to do this is to via editing the settings.json file. In it there should be a `microbit_runtime_hex` key, by default set to `null`. You can add a path for a different MicroPython hex file there.

We can combine this with the fact that mu will prioritise a settings.json file located in the same directory than mu. 

So we can create this file `settings.json` file in the same directory than `run.py` (defaults will be used for the missing values, and they will be added to the file when Mu is closed):
```json
{
  "microbit_runtime_hex": "<path_to_my_microbit_micropython.hex"
}
```

Note: This feature was added after the 0.9.13 release, so you'd need to run Mu from source as we don't currently have appveryor builds (they have been broken for a few months now).

**Comment by ntoll** [comment]
Fixed by release of the new website: https://codewith.mu/en/howto/microbit_settings
