### ISSUE TITLE
change - 'ctrl-D' in MU code editor window to something else

### ISSUE THREAD

**Issue by ltheoret** [mu-editor/mu#323]
Hi,

I would like to say that MU v.1.0.0 Beta 13 works but every time I want to do a soft reboot 'ctrl-D' it copies text in my code if I forget to click in the REPL window first.
Can 'ctrl'-D be disabled or changed in the code editor?
I use in Windows 10.

Luc

**Comment by ntoll** [comment]
CTRL+D in the editor pane is the shortcut for "duplicate". People actually use this so I guess the solution is to ensure you have the focus on the REPL. Sorry... :-(
