### ISSUE TITLE
Windows install cant use 'installed' packages

### ISSUE THREAD

**Issue by martinohanlon** [mu-editor/mu#330]
OS - Windows 10
Installed using Windows 64 bit installer. https://s3-eu-west-2.amazonaws.com/mu-builds/windows/mu_2018-02-10_19_12_master_3893ae7_64bit.exe

When I try to import packages I have installed via pip (e.g. guizero), it cant find them.

I know they are installed as the Python REPL will happily import them (see below).

![mu-windows-errorpng](https://user-images.githubusercontent.com/2329501/36106454-537b33a4-100f-11e8-8f76-efab11da2c94.PNG)

**Comment by ntoll** [comment]
Doh... my fault for not explaining things clearly enough. As per the packaging docs: the version of Python used by Mu and the "system" Python are different. That's why you're not seeing them from Mu.

**Comment by ntoll** [comment]
It's for this reason that people can install Mu and NOT have Python installed on Windows.... Mu comes with its own version that is "sandboxed" from everywhere else.

The good news is that we can tell the Mu installer to include the Windows version of GPIOZero so it's available to Mu's version of Python.

Does that make sense?

**Comment by martinohanlon** [comment]
Ok how do I get Mu to use other packages?

**Comment by ntoll** [comment]
We agree before I cut a release, which packages should be included in the Mu version of Python. Does this make sense..?

**Comment by ntoll** [comment]
As discussed, this is by design.
