### ISSUE TITLE
Create a PyGame Zero mode

### ISSUE THREAD

**Issue by bennuttall** [mu-editor/mu#334]
How easy would it be to create a PyGame Zero mode? I'd be happy to have a go with some guidance.

The way PyGame Zero works is you write your code in an editor, and run it from the command line with `pgzrun`. EDIT for clarity: So in this mode, the "Run" button would run your code with `pgzrun` rather than `python3`.

Things to consider:

- Assuming it doesn't get bundled with Mu, pgzero may not be installed (it is pre-installed on Raspbian)
- Since a pgzero script does not have to be a valid Python file (i.e. pgzero imports are not necessary) the checker would not be accurate without knowledge of the pgzero globals (MVP could remove the checker, but a fully featured version could add it back in with a sophisticated pgzero aware checker)

FAO @lordmauve

**Comment by tjguk** [comment]
@bennuttall are you suggesting that mu actually *run* the pgzero (ie by invoking pgzrun)? Or simply that it not be confused by the lack of imports etc.

**Comment by bennuttall** [comment]
Run!

**Comment by ntoll** [comment]
@bennuttall this is on my radar for this week. Great minds think alike (or fools seldom differ). ;-)

**Comment by ntoll** [comment]
See the work taking place on the `pygamezero` branch.

**Comment by bennuttall** [comment]
This is great! It works very well 👍

**Comment by ntoll** [comment]
Great stuff... it was hacked together in about 45mins last night. 

ToDo:

- [ ] Tests
- [ ] Docs
- [ ] Developer docs description for how I implemented it (so others can follow the process)
- [ ] Add buttons to show images and sounds used by PyGameZero (so users can just copy their own game assets over to the right place)
- [ ] Create the default images and sounds from the PyGameZero tutorial in the expected location on the file system.
- [ ] Add API autocomplete / call tips.
- [ ] Make sure code checking works as expected for implied names in PyGameZero namespace.

**Comment by ntoll** [comment]
First working Windows installer here: https://s3-eu-west-2.amazonaws.com/mu-builds/windows/mu_2018-02-15_20_49_pygamezero_5861bdc_64bit.exe

**Comment by ntoll** [comment]
Landed in master 53cd0fc6d67921103429f4185835dcb828174850

Updated docs here: https://mu.readthedocs.io/en/latest/index.html (including using this work as an example for creating a new mode in Mu).

64bit Windows build here: https://s3-eu-west-2.amazonaws.com/mu-builds/windows/mu_2018-02-16_20_02_master_53cd0fc_64bit.exe

YouTube video of a quick demo: https://www.youtube.com/watch?v=jmIK3XfSvNI

**Comment by lordmauve** [comment]
This is super exciting! All this Pygame and Mu development is making me want to get a new release of Pygame Zero out.

**Comment by bennuttall** [comment]
:1st_place_medal:

**Comment by yonghuming** [comment]
@lordmauve hmmm, i think pyzero need some ui for sudents to input some info, eg: input textbox, pygzero is a game engine and it need ui framework to make it more comfortable to use
