### ISSUE TITLE
Clicking Check when there are no errors gives no feedback

### ISSUE THREAD

**Issue by martinohanlon** [mu-editor/mu#337]
When you click check and there are no errors in the program you received no feedback as to whether the check was successful or not and its difficult to know if it ran at all.

A couple of ideas:
 - give an update as a 'toast' (a message which appears and then disappears after a period of time) in the status bar
![image](https://user-images.githubusercontent.com/2329501/36194238-d1b96554-1160-11e8-8a1f-33a32af33e4c.png)

 - turn the check icon green for a few seconds to show that it was run successfully
![image](https://user-images.githubusercontent.com/2329501/36194328-1ce2c606-1161-11e8-80e2-8879a43fe488.png)

**Comment by ntoll** [comment]
Fixed by 960cf998fafddfaa02c700fa243fcea0ccc7c5a4
