### ISSUE TITLE
Run / Stop button state is incorrect when save file is cancelled

### ISSUE THREAD

**Issue by martinohanlon** [mu-editor/mu#338]
This is a slightly obscure error but if you follow these steps you can recreate it:
 - create a new file
 - write some code
 - click Run (and the icon changes to Stop)
 - (the Save dialog appears) click Cancel

The Run icon stays as Stop - even though the program isnt running.

**Comment by ntoll** [comment]
Fixed by 960cf998fafddfaa02c700fa243fcea0ccc7c5a4
