### ISSUE TITLE
Help button url is broken in 1.0.0.beta.14

### ISSUE THREAD

**Issue by martinohanlon** [mu-editor/mu#339]
The help button takes you to https://codewith.mu/en/help/1.0

![image](https://user-images.githubusercontent.com/2329501/36194593-31f0df5a-1162-11e8-9b99-916792af099e.png)

**Comment by ZanderBrown** [comment]
#306

**Comment by ntoll** [comment]
This is fixed with the beta.16 release and the new website: https://codewith.mu/

(The actual help screen users will see for this release is: https://codewith.mu/en/help/1.0)
