### ISSUE TITLE
Pygame Zero mode doesn't finish running when the program finishes

### ISSUE THREAD

**Issue by tjguk** [mu-editor/mu#342]
Switch to Pygame Zero mode
Run some code (even an empty file)
Let it finish (eg Ctrl-Q or your game dies or whatever)

mu is still in "Running" mode and won't offer the "Play" button until the "Stop" button is pressed

**Comment by ntoll** [comment]
That's correct. The stdin/out panel at the bottom of the screen should show a message saying the process is finished.

This is so any output from the finished program is still visible to the end user, until they want to explicitly dismiss it by clicking "stop".

Does this make sense? Any way to make it clearer? Happy to have suggestions.

**Comment by ntoll** [comment]
This appears to be the correct behaviour (as explained above) so closing.
