### ISSUE TITLE
Debugger, breakpoints on line 1 point break

### ISSUE THREAD

**Issue by martinohanlon** [mu-editor/mu#346]
If you place a break point on line 1 of programmer the debugger doesn't stop at the breakpoint. 

A breakpoint on line 2 works fine.

To replicate, set a breakpoint on line 1 of a program and click **debug**  - it should stop at line 1, but it doesn't.

![ezgif com-optimize 1](https://user-images.githubusercontent.com/2329501/36377545-7b2a154a-156f-11e8-9e18-cce6a3a4393f.gif)

**Comment by ntoll** [comment]
Heh... I suspect you've found an off-by-one error. The debugger starts counting lines from 1 but QScintilla starts counting from 0. That's my hunch. I'll check it out and fix in any case (I have a number of debugger related bugs that I want to fix).

**Comment by ntoll** [comment]
This is fixed in af47bc1ba247856af88d5f504a448c8360ea3314
