### ISSUE TITLE
Debugger - stepping over the final line of code results in an IndexError exception

### ISSUE THREAD

**Issue by martinohanlon** [mu-editor/mu#347]
When using the debugger, if you step over the final line of code in any program it results in:

```
exception: IndexError('list index out of range',)1
```

... and the program restarts from the break point. If you then step over the program again, it completes with no errors.

![ezgif com-optimize 2](https://user-images.githubusercontent.com/2329501/36378135-8b6dd55c-1571-11e8-8b5e-633a907d0cdc.gif)

**Comment by ntoll** [comment]
This is fixed in af47bc1ba247856af88d5f504a448c8360ea3314
