### ISSUE TITLE
Flashing micro:bit blocks UI

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#350]
Tested on Mu v1.0.0.beta.14 installed via pip in Python 3.5.2 32-bit in Windows 10 x64.

When flashing the micro:bit the UI thread is blocked. Clicks and interactions are registered, but the actions only take place after the flashing/copying has finished.

This has been the normal behaviour on Windows since the beginning (or as far as I can remember), but last time I mentioned it in person you showed some interest to get it fixed, so logging it here so that we don't forget.

**Comment by ntoll** [comment]
Argh... I knew there was something I'd missed. Every time I tried to remember what it might be I came back blank. It was this..! THANK YOU! I'll take a look at fixing it today or tomorrow. :-)

**Comment by ntoll** [comment]
Fixed in 64db73dd3fff9388400b51f457b1f21b6e01e3d4

**Comment by ntoll** [comment]
Oops... that should be 64379f321eb2fbed8eb906d2e31f46cdfe3b36d3
