### ISSUE TITLE
Mu always adds .py to a file, even if the filename as a file extenstion.

### ISSUE THREAD

**Issue by martinohanlon** [mu-editor/mu#361]
When saving a file Mu will always add a .py extension to the end of the file. 

Super, unless of course you want to create a file which has a different file extension, e.g. a .txt file which your program loads in at runtime.

Using this model is really common when getting learners to work with files.

.e.g 
First create a file which has a list of names in it and called it names.txt. 
Open names.txt in your Python program.
Read in the names.
etc, etc.

**Comment by martinohanlon** [comment]
I would recommend that if a filename is presented which doesnt have a file extension it adds .py, if a file extension is included it doesn't.

**Comment by ntoll** [comment]
+1 on that suggested behaviour.

**Comment by martinohanlon** [comment]
Submitted PR https://github.com/mu-editor/mu/pull/362
