### ISSUE TITLE
Will 'lightLevel' function be supported in micropython ?

### ISSUE THREAD

**Issue by DavidMS51** [mu-editor/mu#369]
I ask this question via slack in the summer and the suggestion was that 'lightLevel' would be supported in a future release of micropython just interested to see if this is still the plan ?

**Comment by ZanderBrown** [comment]
I suspect you want the micropython repo, more specifically issue https://github.com/bbcmicrobit/micropython/issues/466

**Comment by DavidMS51** [comment]
Thanks
