### ISSUE TITLE
bug of plotter

### ISSUE THREAD

**Issue by yonghuming** [mu-editor/mu#375]
![image](https://user-images.githubusercontent.com/435079/37141834-4a147452-22f1-11e8-870f-08729be97945.png)
i want to track random data.
but the figure seems wrong, i use random()  to generate data, and the chart does not show the data in right form

**Comment by ntoll** [comment]
You're right! Well done, you've found a bug. I think the numbers along the vertical axis should work as floating point values. It's obvious that the middle "0" is the real "0", but the "0"s above and below it should read 0.5 and -0.5. I'll see what I can do. :-)

Also, it's *so* good to see you using the Chinese Mu!

I have a question about "Mu" which I hope you can answer. Could "Mu" be represented in Chinese like the following example: https://en.wikipedia.org/wiki/Mu_(negative)?

**Comment by ntoll** [comment]
Fixed by 981c909c3ca33f71a983fa4d1a50cbaace4fc36e
