### ISSUE TITLE
maybe the APIs also need i18n

### ISSUE THREAD

**Issue by yonghuming** [mu-editor/mu#384]
![image](https://user-images.githubusercontent.com/435079/37255146-3d2ba82a-2583-11e8-8ae1-4d24da412f03.png)

Since APIs in ```mu/api``` dir also could be translated maybe need a machinic to i18n APIs
it will be more easy to use mu

**Comment by ZanderBrown** [comment]
I'm confused what do you want translated?

**Comment by yonghuming** [comment]
@ntoll yes it help

**Comment by yonghuming** [comment]
@ntoll i tried make translateall on windows 10 under mu root dir, but it seems have no make translateall command
```
D:\coding\mu>python make.py translateall
Traceback (most recent call last):
  File "make.py", line 196, in main
    function = _exported[command]
KeyError: 'translateall'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "make.py", line 204, in <module>
    sys.exit(main(*sys.argv[1:]))
  File "make.py", line 198, in main
    raise RuntimeError("No such command: %s" % command)
RuntimeError: No such command: translateall

```

**Comment by tjguk** [comment]
Sorry; it's on my to-do list. cf #381

**Comment by tjguk** [comment]
Of course, anyone else is very welcome to submit a PR; I'm happy to review

**Comment by ntoll** [comment]
Since translating the APIs would be require around 15751 new translation strings, and my guess is this is beyond the scope of a volunteer led project, I'm closing this quickly before anyone actually tries to do it and bite off more than they can chew..! :-)

Thank you for the suggestion.
