### ISSUE TITLE
Check messages first character

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#387]
Not sure if this is a bug, but it looks like the first character on the check messages is not displayed correctly:
<img width="998" alt="image" src="https://user-images.githubusercontent.com/4189262/37348992-5193d90e-26cd-11e8-9054-be2f40c82dc4.png">

Tested on macOS 10.13 High Sierra, running from latest master.

**Comment by tjguk** [comment]
Current Windows looks ok (assuming that the symbol is supposed to be a right-angled arrow)

![image](https://user-images.githubusercontent.com/580948/37349501-7a2fbb52-26ce-11e8-8ce5-ccd6733f2935.png)

**Comment by ntoll** [comment]
Ah yes... I was given feedback that it wasn't obvious how the lines in the feedback related to particular lines of code, hence the use of the arrow pointing up. I guess we should do the easy thing and use a UTF-8 code-point that'll be in a font on *every* computer... ;-)

Open to suggestions! (Basically, we need some visual indication that the feedback relates to the line immediately above the box.)

**Comment by ntoll** [comment]
Good point... (no pun intended)... :-D

**Comment by carlosperate** [comment]
A caret would be a safe bet, but I must admit I'm not a fan. Works well in the terminal, but on a GUI is not very clear that it's mean to be pointing up:

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/4189262/37356078-13118180-26dd-11e8-94b0-04add4a2e411.png">


I think a normal arrows is still a safe bet in mosts systems (↑), and looks much better:

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/4189262/37356176-4c5891fe-26dd-11e8-9de6-b0ccb7eb427c.png">

**Comment by ntoll** [comment]
+1 on the up arrow. Care to make the change..?

**Comment by carlosperate** [comment]
Sure thing, I'll create the PR later tonight :)
