### ISSUE TITLE
it will be intresting use microbit to control pygame zero

### ISSUE THREAD

**Issue by yonghuming** [mu-editor/mu#388]
maybe pygame zero mode should be a sublclass of microbit mode class.
or we need to create a new mode so we can use microbit to contorl pygame
i am trying.

**Comment by ntoll** [comment]
Heh... so this is definitely possible. The thing to do would be to see how PyGame consumes USB serial messages (i.e. from devices like the micro:bit). I know for certain that PyGame supports various game controller / USB devices. It's something I've thought about too, and may use April's PyWeek (see: https://pyweek.org/) as an excuse to try to build something. In the worst case, PySerial could be an option to read and write data to the device.

**Comment by tjguk** [comment]
Pygame's use of USB controllers is via the joystick module. I assume it would be easier to insert your own serial-handler into the pygame loop than to try to make the microbit mimic the joystick data

**Comment by ukBaz** [comment]
FYI: There is work going on over on the micro:bit DAL to get the micro:bit to look like a Bluetooth Hardware Interface Device (HID).
https://github.com/lancaster-university/microbit-dal/pull/249

I know Bluetooth cannot be used by micropython on the micro:bit but to use the micro:bit as a wireless controller in Pygame this would probably make it easier to deal with.

**Comment by ntoll** [comment]
@illume you're a :star: Thank you for posting this!

**Comment by illume** [comment]
I hereby grant all, all permissions on those bytes to do as they wish. *ceremonial bow and handwave*

**Comment by ntoll** [comment]
Stonking stuff... *ceremonial bow and handwave* back at'cha. ;-)

**Comment by ntoll** [comment]
Closing since this is more to do with PyGame than Mu. :-) Thanks for all the input everybody.
