### ISSUE TITLE
Can we tag the beta releases on git/GitHub?

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#395]
No need to make GitHub releases, but adding a git tag would still show in https://github.com/mu-editor/mu/releases and help trave versions to commits.

**Comment by ZanderBrown** [comment]
Releases does have a 'is prerelease' flag from memory

**Comment by ntoll** [comment]
Aha... OK... I'll do this for beta.16. :-)

**Comment by carlosperate** [comment]
Thanks @ntoll!

**Comment by carlosperate** [comment]
@ntoll Since beta 15 has been released to the Raspberry Pi repos (so that's the version you get now when doing `sudo apt-get install mu`), I hope you don't mind I've tagged that release in GitHub.
Should make it easier to compare changes between that release and master whenever we get a bug report.
