### ISSUE TITLE
codewith.mu out of date

### ISSUE THREAD

**Issue by martinohanlon** [mu-editor/mu#400]
codewith.mu installers are out of date.

I was going to make some changes (update links, add instructions, auto download javascript thingy) and push a PR but I couldn't find the repo.

**Comment by ntoll** [comment]
Work on the new website is happening here: https://github.com/mu-editor/mu-editor.github.io/tree/v1 (note the v1 branch). I aim to fill in as much content as I can this week.

**Comment by yonghuming** [comment]
i will help do some translation

**Comment by ntoll** [comment]
@yonghuming please don't do anything yet! :-) This is a work in progress and I'll make an announcement when things are stable enough for translation efforts to start!

Thank you, as always, for your support! :-)

**Comment by ntoll** [comment]
I'm going to close this since efforts on the website are ongoing and will land very soon.

@yonghuming I'll cc/ you in the appropriate issue for the website when it comes to translations etc... (and thank you for the offer). :-)
