### ISSUE TITLE
hope Mu have a examples code menu

### ISSUE THREAD

**Issue by yonghuming** [mu-editor/mu#405]
hope mu have examples code mu just like Arduino and Processing do.
beginner could try some example code, and look the code  run result

**Comment by ntoll** [comment]
Yes and No. :-)

Yes, there will be examples.

No, they will not be built into Mu.

These examples will be in the new website (see: https://github.com/mu-editor/mu-editor.github.io/tree/v1) and accessible by clicking on Mu's "Help" button.
