### ISSUE TITLE
Remove mouse over background colour change in the status bar?

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#407]
This is a very minor thing.
Mousing over the "mode" text in the status bar changes it background, making it look like a clickable UI element, this could be a bit confusing when it doesn't do anything.
![image](https://user-images.githubusercontent.com/4189262/37783443-7100ac64-2ded-11e8-884a-9ad73451bb4a.png)
The tooltip does help clarify what the text mean, which is definitely a good addition to keep there.

**Comment by ZanderBrown** [comment]
When I added this they where clickable (hence I added them)

#406 removes them again as a side effect

**Comment by carlosperate** [comment]
Do the tooltips still work with #406?

**Comment by carlosperate** [comment]
Already fixed on master, thanks @ZanderBrown and @ntoll!
