### ISSUE TITLE
Can't double-click on mode

### ISSUE THREAD

**Issue by tjguk** [mu-editor/mu#410]
When presented with the list of modes, one expects to be able to double-click in lieu of click-and-ok

**Comment by ZanderBrown** [comment]
Looks like it's the `itemDoubleClicked` signal we want, away from my machine for a while but it looks like we want to connect to that around line 66 and handle it by emiting `self.accept`

https://github.com/mu-editor/mu/blob/40fbd75c46f5ae10c458fb478bf5b0af98d1416c/mu/interface/dialogs.py#L46-L91

i.e.

```python
self.setLayout(widget_layout)
self.mode_list = QListWidget()

@self.mode_list.itemDoubleClicked.connect
def select_and_accept():
    self.accept.emit()

widget_layout.addWidget(self.mode_list)
self.mode_list.setIconSize(QSize(48, 48))
```

**Comment by carlosperate** [comment]
I agree with this one, I keep double clicking the mode every time I need to change it, so this additional would definitely be welcomed.

**Comment by ntoll** [comment]
+1

**Comment by ntoll** [comment]
OK... that didn't take long... ;-)
