### ISSUE TITLE
Segmentation Fault attempting to  run Mu 1.0.0.beta.15

### ISSUE THREAD

**Issue by rgall218** [mu-editor/mu#424]
If you are reporting a bug, we would like to know:

Installed MU 1.0.0.beta 15 using pip. I am using linux mint 18.1 = 64 bit.
Installed in my anaconda directory successfully.

Upon running I immediately get a segmentation fault. 

errors from sys.log
Apr  5 01:37:28 rod-Latitude-E6230 kernel: [  175.107837] mu[2691]: segfault at 20 ip 00007fb6bc08273c sp 00007ffdd762c670 error 4 in ld-2.23.so[7fb6bc076000+26000]
Apr  5 01:40:40 rod-Latitude-E6230 kernel: [  367.117711] mu[2746]: segfault at 20 ip 00007f74eb29973c sp 00007ffc1f5a7130 error 4 in ld-2.23.so[7f74eb28d000+26000]

**Comment by ZanderBrown** [comment]
Did Mu manage to open its own log before crashing?

**Comment by rgall218** [comment]
Yes it did open a log.

Starting Mu 1.0.0.beta.15
2018-04-05 01:40:59,880 - root:113(run) INFO: uname_result(system='Linux', node='rod-Latitude-E6230', release='4.4.0-53-generic', version='#74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016', machine='x86_64', processor='x86_64')
2018-04-05 01:40:59,881 - root:114(run) INFO: Python path: ['/home/rod/anaconda3/bin', '/home/rod/anaconda3/lib/python36.zip', '/home/rod/anaconda3/lib/python3.6', '/home/rod/anaconda3/lib/python3.6/lib-dynload', '/home/rod/anaconda3/lib/python3.6/site-packages', '/home/rod/anaconda3/lib/python3.6/site-packages/Sphinx-1.5.1-py3.6.egg', '/home/rod/anaconda3/lib/python3.6/site-packages/IPython/extensions']
2018-04-05 01:40:59,895 - mu.logic:355(__init__) INFO: Setting up editor.
2018-04-05 01:40:59,895 - mu.logic:366(__init__) INFO: Settings path: /home/rod/.local/share/mu/settings.json
2018-04-05 01:40:59,895 - mu.logic:367(__init__) INFO: Log directory: /home/rod/.cache/mu/log
2018-04-05 01:40:59,895 - mu.logic:368(__init__) INFO: Data directory: /home/rod/.local/share/mu
2018-04-05 01:40:59,930 - mu.logic:376(setup) INFO: Available modes: python, adafruit, microbit, debugger, pygamezero


It could be a confutation problem on my part.

**Comment by carlosperate** [comment]
How did you start Mu? From the command line? If so, could you copy and paste everything in the terminal?

**Comment by rgall218** [comment]
My apologies , I should of included all this  I/O in the initial post.

From the cmd line:
rod@rod-Latitude-E6230 ~ $ mu
Logging to /home/rod/.cache/mu/log/mu.log
QApplication: invalid style override passed, ignoring it.
Segmentation fault
rod@rod-Latitude-E6230 ~ $

**Comment by rgall218** [comment]
Sorry for the delay, I am swamped. Anyway..

I did a conda list and packages of interest were:
 pyqt  (version 5.6.0) installed using conda.
PyQt5 (version 5.10) installed using pip. 
mu-editor (version 1.0.0b15) installed using pip.

I uninstalled all packages and reinstalled pyqt using conda,    Pyqt5 and mu-editor using pip.

Ran mu  and we have different error. Seems it can't find a package

I uninstalled  PyQt5  and mu-editor again and let reinstalled the mu-editor by itself using the disable cache option forcing a new download of  PyQt5
pip install --no-cache-dir mu-editor.

same error message as below.



rod@rod-Latitude-E6230 ~/.cache/mu/log $ mu
Traceback (most recent call last):
  File "/home/rod/anaconda3/bin/mu", line 7, in <module>
    from mu.app import run
  File "/home/rod/anaconda3/lib/python3.6/site-packages/mu/app.py", line 50, in <module>
    from mu.interface import Window
  File "/home/rod/anaconda3/lib/python3.6/site-packages/mu/interface/__init__.py", line 1, in <module>
    from .main import Window
  File "/home/rod/anaconda3/lib/python3.6/site-packages/mu/interface/main.py", line 35, in <module>
    from mu.interface.panes import (DebugInspector, PythonProcessPane,
  File "/home/rod/anaconda3/lib/python3.6/site-packages/mu/interface/panes.py", line 33, in <module>
    from qtconsole.rich_jupyter_widget import RichJupyterWidget
ModuleNotFoundError: No module named 'qtconsole.rich_jupyter_widget'
rod@rod-Latitude-E6230 ~/.cache/mu/log $

**Comment by carlosperate** [comment]
Sounds like it might be a similar issue than https://github.com/mu-editor/mu/issues/373 ? (the PyQt used by Mu get's confused looking for it's libraries when PyQt is also installed by conda).

I'm not really sure about how anaconda works, but based on those paths (`/home/rod/anaconda3/lib/python3.6/...`) it sounds like you are using a Python installed by anaconda, and when using pip this is inside that version of python, is that correct?

Could you do a `pip freeze` and copy the results here? It should have `qtconsole` as an installed package.

**Comment by rgall218** [comment]
Yes it is python  3.6 install by anaconda  in the anconda3 directory.

Here is pip freeze for mu-editor

[pip-freeze.txt](https://github.com/mu-editor/mu/files/1886419/pip-freeze.txt)

**Comment by rgall218** [comment]
here rod@rod-Latitude-E6230 ~ $ pip -V
pip 9.0.3 from /home/rod/anaconda3/lib/python3.6/site-packages (python 3.6)
rod@rod-Latitude-E6230 ~ $  the pip version and path

**Comment by carlosperate** [comment]
That's odd, you have the right version of qtconsole.

Do you have other versions of Python installed? Perhaps when running a script with the `RichJupyterWidget` shebang it uses a different one?

How do you normally enter that Python interpreter, is it just `python3`? Can you try:

```
<python interpreter> -m mu
```

So, that could be: `python3 -m mu`

**Comment by rgall218** [comment]
tried..
 python3 -m mu same error

I performed a find command
od@rod-Latitude-E6230 ~ $ sudo find / -name rich_jupyter_widget.py
/home/rod/anaconda3/pkgs/qtconsole-4.2.1-py36_1/lib/python3.6/site-packages/qtconsole/rich_jupyter_widget.py
find: ‘/run/user/1000/gvfs’: Permission denied
rod@rod-Latitude-E6230 ~ $

**Comment by rgall218** [comment]
I have a good  install of mu-editor.
I uninstalled qt-console using pip. and uninstalled  mu-editor using pip.

I then installed mu-editor which installed qtconsole.

I have mu up and  running

**Comment by carlosperate** [comment]
So with the same pip command you have uninstalled `qtconsole` and `mu-editor`, and then reinstalled `mu-editor` and it worked again?
I'm glad it's working, but I'm still confused about what the problem was, since you did have the right dependencies installed (based on your pip freeze output file).

Is it possible qtconsole was a package installed with anaconda instead of pip?

**Comment by ntoll** [comment]
Closing since the problem has been solved (it appears to be configuration conflicts between Anaconda and pip).
