### ISSUE TITLE
mu fails to start with missing NFS mount containing file for open tab

### ISSUE THREAD

**Issue by PeterOGB** [mu-editor/mu#431]
I use an NFS server to hold my projects. 
When away from home this is not available.

Starting mu when there is an open tab for a file on that NFS mount causes the error below:

[mucrash2.txt](https://github.com/mu-editor/mu/files/1887240/mucrash2.txt)

PeterO

**Comment by ZanderBrown** [comment]
Looks like we want to catch OSError here
https://github.com/mu-editor/mu/blob/56fc1a3a83822ce30585d6adde1a646f96545c5d/mu/logic.py#L705

Suppose that makes sense as it's a missing device not file

**Comment by ntoll** [comment]
OK... it's in latest master.
