### ISSUE TITLE
mu does not install pygame zero on some windows 7

### ISSUE THREAD

**Issue by yonghuming** [mu-editor/mu#433]
we have hold some online coding course for kids
some kids install mu on windows 7 and seems it do not install pgzero on windows 7
but no problems with windows 10.
a python script using pygame zero could run properly on my most sutdents's computer but not a little sutdent.
when run pygame zero on windows 7 it shows nothing

**Comment by yonghuming** [comment]
there Python\Python36-32\Scripts is empty

**Comment by yonghuming** [comment]
![image](https://user-images.githubusercontent.com/435079/38468371-3cba44be-3b77-11e8-977a-a9f9c7255c37.png)
mybe bug of python

**Comment by ntoll** [comment]
Are you using Mu as installed with the Windows installer..? If so, it doesn't use the system Python but you'll find the packages in somewhere under the "Program Files\Mu\ " directory.

**Comment by yonghuming** [comment]
ok i'll try to fix the problem

**Comment by yonghuming** [comment]
i checked user's install dir, and no Program Files\Mu\ " directory. seems the pip do not install correctly on windows 7

**Comment by yonghuming** [comment]
though mu use seperate python env, but after i install pgzero on windows 7 use pip through command, pygame zero  mode will work properly

**Comment by yonghuming** [comment]
![image](https://user-images.githubusercontent.com/435079/38495891-f58e8a3e-3c2d-11e8-9f5b-585292878154.png)

**Comment by ntoll** [comment]
Ahh... so you're using `pip` and *NOT* the Windows exe installer..? OK... then the directory I mention won't exist.

I guess there's a pip related problem (are you using the correct version of Python/pip..?). PyGame Zero is *definitely* in the requirements for pip to install... so I'm guessing some sort of configuration problem on your PCs.

**Comment by ntoll** [comment]
Hmm... perhaps the version of Mu on PyPI is older and doesn't include the PyGame Zero requirement. In any case, this will be fixed in the next release. :-)

**Comment by yonghuming** [comment]
seems pgzero not install but i got no error when run pygame games script

**Comment by yonghuming** [comment]
some of our students use windows met this problem

**Comment by ntoll** [comment]
OK... this is fixed in current master, and when the next beta release lands in PyPI then it'll work properly for you. The version in PyPI is relatively old at this moment in time.

**Comment by yonghuming** [comment]
when will next beta be released?

**Comment by ntoll** [comment]
Soon (perhaps in about a week). :-)

If you want the latest version, use Git to clone the repository and, in a virtualenv, `pip install .`

**Comment by yonghuming** [comment]
ok
thank you
