### ISSUE TITLE
settings.json file overwritten on app closure

### ISSUE THREAD

**Issue by WayneKeenan** [mu-editor/mu#434]
I'm trying to set `microbit_runtime_hex` in `~/Library/Application\ Support/mu/settings.json` to a custom firmware but every time `mu` exits it resets the settings.json to default values, thereby deleting the `microbit_runtime_hex` key.  (It also doesn't seem to use the firmware when flashing, a separate issue)

I've placed `firmware.hex` in the `~/Library/Application\ Support/mu/` folder and tried setting `microbit_runtime_hex` to `firmware.hex` and also a fully qualified path, thinking it my be defaulting the config if the file can't be found, but the issue happens in both cases.

`settings.json` before launching `mu`:

```
{
  "theme": "day",
  "workspace": "/Users/wayne/mu_code",
  "paths": [],
  "microbit_runtime_hex": "/Users/wayne/Library/Application Support/mu/microbit-blue-pairing-not-required.hex"
}
```

`settings.json` after exit:
```
{
  "paths": [],
  "workspace": "/Users/wayne/mu_code",
  "theme": "day"
}
```

**Comment by ntoll** [comment]
Hi @WayneKeenan - I'm ahead of you here... it's fixed on `master` and should be in the next release.
