### ISSUE TITLE
mu get different result same function to IDLE

### ISSUE THREAD

**Issue by yonghuming** [mu-editor/mu#442]
i wrote i function to cal the sum two inputed num

![image](https://user-images.githubusercontent.com/435079/38777953-828c737e-40e3-11e8-831a-58c24e05f637.png)

but it get wrong answer,and i get the right answer in IDLE
![image](https://user-images.githubusercontent.com/435079/38777956-94d76570-40e3-11e8-95df-17b62ea6e8be.png)

**Comment by yonghuming** [comment]
![image](https://user-images.githubusercontent.com/435079/38777970-ccc5a118-40e3-11e8-9d03-c0cc566f28bc.png)
but right answer if print b and c

**Comment by yonghuming** [comment]
![image](https://user-images.githubusercontent.com/435079/38777997-2e05bab2-40e4-11e8-877d-37591e33edcd.png)

**Comment by ntoll** [comment]
That's weird... looking into it right now. All Mu is doing, is showing you the output from a standard Python process. I wonder what's going on.

**Comment by ntoll** [comment]
I can reproduce this bug... I'll see what's going on.

**Comment by yonghuming** [comment]
![image](https://user-images.githubusercontent.com/435079/38778010-666543dc-40e4-11e8-898d-8aefb9831c32.png)

**Comment by yonghuming** [comment]
fill really strange

**Comment by yonghuming** [comment]
i think it's a bug of mu for input() works well in IDLE

**Comment by ntoll** [comment]
I believe it's a bug in the Python runner pane that's handling input/output from the Python process. It shouldn't take long to prove (and if so, fix).

**Comment by yonghuming** [comment]
加油

**Comment by ntoll** [comment]
Heh... (thanks to Google translate)

I've found the problem. It's as I expected, a problem in the input/output pane for Python processes. I'll fix it now.

**Comment by yonghuming** [comment]
how efficient of you

**Comment by yonghuming** [comment]
and also it seems mu could not run pygame in some computer, i need reinstall python 3.x and mu to fix this problem ,and this drove me crazy......the script is no error, but show nothing after press play button

**Comment by ntoll** [comment]
Found the problem... just need to write some tests to prove it works and doesn't break anything. But in the meantime, here's picture proof:

![mu_io_fix](https://user-images.githubusercontent.com/37602/38778132-31415278-40ac-11e8-870c-8ceeee050c61.png)

**Comment by yonghuming** [comment]
wanderful,

**Comment by ntoll** [comment]
OK... all pushed to `master`. Thanks for reporting this.

The function that I had to change is probably one of the most complicated in Mu, and I wouldn't be surprised if there are more bugs. In any case, thanks to the tests, it was very easy to find, diagnose and fix. :-)

謝謝 :-)
