### ISSUE TITLE
Appveyor builds fail due to AWS secret key error

### ISSUE THREAD

**Issue by ntoll** [mu-editor/mu#45]
The Windows build appears to work. This is awesome, apart from one fly in the ointment. At the very end the process errors with the following message:

```
Value cannot be null.
Parameter name: awsSecretAccessKey
```

While I can see the asset is created, the actual build is marked as failed. 

Is there any way to fix this?

**Comment by carlosperate** [comment]
We currently have a working AppVeyor project running at: https://ci.appveyor.com/project/carlosperate/mu , which deploys the built executables to http://ardublockly-builds.s3-website-us-west-2.amazonaws.com/index.html?prefix=microbit/windows/

However, the wrong badge is attempted to be displayed in the [package/READM.md](https://github.com/ntoll/mu/blob/master/package/README.md#download-the-mu-executable--) file, so we still need to update that.

**Comment by carlosperate** [comment]
This is not an issue anymore.
