### ISSUE TITLE
Pasting multiple lines into REPL ignores CR/LF

### ISSUE THREAD

**Issue by WayneKeenan** [mu-editor/mu#450]
Mu 1.0.0 beta 15

Pasting multi-line text into the REPL window, be it from Mu itself, Sublime or other editors, results in all lines being concatenated into a single line.

**Comment by ntoll** [comment]
@WayneKeenan which REPL..? MicroPython, CircuitPython, Python 3.

**Comment by WayneKeenan** [comment]
@ntoll ah, can't you see my screen or read my mind :)  sorry, the Microbit REPL

**Comment by WayneKeenan** [comment]
I should also say that this is happening with the stock Micro:bit firmware.

**Comment by ntoll** [comment]
@WayneKeenan OK... it was a very simple fix and will be in tomorrow's beta.16 release. ;-)

Thanks for the heads up and taking the time to report the problem.
