### ISSUE TITLE
Could pygame-zero mode bundle sample assets?

### ISSUE THREAD

**Issue by bennuttall** [mu-editor/mu#456]
Just an idea: would it be possible to bundle a handful of sample game assets in the `images` and `sounds` directories which are created by Mu? I'm not talking about an extensive suite of artwork, just a few sample assets to help someone get started, like the alien ones in the [tutorial](http://pygame-zero.readthedocs.io/en/stable/introduction.html#draw-a-sprite):

![](http://pygame-zero.readthedocs.io/en/stable/_static/alien.png) ![](http://pygame-zero.readthedocs.io/en/stable/_static/alien_hurt.png)

This would mean a user could follow the tutorial without having to work out how to download these images and save them to the right location. A few more would be nice, but I don't know where these ones came from.

ping @lordmauve

**Comment by ptorrone** [comment]
if ya'll want, we can "donate" blinka the circuitpython snake art and/or circuitplayground character art for this (adabot, minerva, etc).

![adafruit_2018_0396](https://user-images.githubusercontent.com/1685947/39409376-f1e3a1fe-4bb3-11e8-91f9-f6882a67a396.jpg)

![minerva](https://user-images.githubusercontent.com/1685947/39409390-20968b06-4bb4-11e8-901c-c5d69ad80e31.png)

**Comment by ntoll** [comment]
@bennuttall that already happens with the version of Mu in master (next beta.16). @ptorrone AWESOME... now we just need a PGZero game with those assets. :-P @lordmauve..?

**Comment by bennuttall** [comment]
Ha! I just realised Mu already did that, came back to say so, and you beat me to it. Great idea by the way! :+1:

**Comment by lordmauve** [comment]
The graphics in the example come from [kenney.nl](http://kenney.nl), which is [noted in the documentation since 1.2](http://pygame-zero.readthedocs.io/en/stable/introduction.html#draw-a-sprite).

**Comment by ntoll** [comment]
OK... I'll close this issue since I've just used my Tardis to go back to fix this a few weeks ago so @bennuttall gets to see that it already works that way...! ;-)

**Comment by bennuttall** [comment]
:+1:
