### ISSUE TITLE
Files panel: micro:bit right click menu not wide enough for text

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#459]
Tested on macOS High Sierra, with the latest master at the time of writting.

<img width="412" alt="image" src="https://user-images.githubusercontent.com/4189262/39516352-96b0df98-4df4-11e8-9f5c-58c4544f7536.png">

**Comment by ZanderBrown** [comment]
It should expand?
https://github.com/mu-editor/mu/blob/48821fdf6566c5a36a1e259b2b997df09072ace6/mu/resources/css/day.css#L102-L111

**Comment by ZanderBrown** [comment]
![screenshot from 2018-05-02 10-45-56](https://user-images.githubusercontent.com/17074021/39516910-3969a5de-4df6-11e8-9456-e0cc72f7cf37.png)
Okay so I can reproduce this on Fedora 28

**Comment by ZanderBrown** [comment]
Commenting out
https://github.com/mu-editor/mu/blob/48821fdf6566c5a36a1e259b2b997df09072ace6/mu/resources/css/day.css#L102-L111
Seems to be an initial workaround
