### ISSUE TITLE
Plotter inaccurate at lower numbers

### ISSUE THREAD

**Issue by kattni** [mu-editor/mu#462]
I have a potentiometer hooked up to a CPX, min 0, max 3.3. At potentiometer max, the plotter does two odd things:
1. It marks the equal grid lines as 1 and 3, so the first grid space would be representing 1 unit and the equally sized second grid space above it would be representing 2 units.
![muplotterscaledto3](https://user-images.githubusercontent.com/7865090/39546242-b6633624-4e21-11e8-8deb-9285860623b4.png)

2. The max of 3.3 appears on the plotter to be less than 3, but difficult to determine exactly as the gridlines are odd per number 1.
![muplottermaxvalueincorrect](https://user-images.githubusercontent.com/7865090/39546321-ff9b4048-4e21-11e8-825f-65d89624d1b8.png)

If I turn the potentiometer until it equals 1.9, it plots along the 1-labeled gridline. 
![muplotter1valueincorrect](https://user-images.githubusercontent.com/7865090/39546424-5b944840-4e22-11e8-9a52-8dd5aea5f3ec.png)

I tested it with a simple `print((1.9,))` to eliminate some unlikely but possible issue with the potentiometer and it plots just below the 1 line as well.
![muplotterprint1point9](https://user-images.githubusercontent.com/7865090/39546640-0f38ac10-4e23-11e8-8558-19911c54760c.png)

It still prints slightly below the line for 7 and 15.
![muplotter7below7-15below15](https://user-images.githubusercontent.com/7865090/39546652-1cca2bec-4e23-11e8-81cc-0129421709fb.png)

31-32 seem to start getting closer to plotting accurately, 61-62 even closer, and 125 seems entirely accurate. It's easiest to tell with these specific numbers because that's where the grid lines on the plotter show up when you start to get into these ranges. It seems the issue evens itself out as you get into higher numbers, but it could be the fact that the plotter is scaling into higher ranges in the same visual space.

**Comment by jepler** [comment]
It's like the numbers on the legend are all 1 value smaller than they ought to be.  If the Y axis values in the first two screenshots were 4, 2, 0, -2, -4 the graph would seem to match the values.

**Comment by ntoll** [comment]
Ouch... that's not good. Thanks for reporting the problem. I'll take a look... I suspect an OBOE (I don't mean the reed instrument either). ;-)

**Comment by ntoll** [comment]
Hi @kattni, what version of Mu are you using? Is it, perhaps, `beta.15`..? 

I've just started to look at the problem and noticed I'd already refactored the way the plotter displays the Y axis to fix an earlier problem. The screenie below shows how it looks now... I hope you agree, it's a more accurate reflection of what should be displayed. This'll be in the upcoming `beta.16` and is currently in `master`.

![accurate_plotter](https://user-images.githubusercontent.com/37602/39586697-999dc602-4eef-11e8-8c37-b5713525ead8.png)

Please feel free to re-open if `beta.16` doesn't work as you expect (when released).

Once again, thanks to you and @jepler for pointing this out. :-)
