### ISSUE TITLE
"check" makes function name lowercase

### ISSUE THREAD

**Issue by martinohanlon** [mu-editor/mu#474]
If you are reporting a bug, we would like to know:

* What you were trying to do,
Using "check" to check the syntax of:

```
Print("hello world")
```

The messages which appears makes the function name lowercase which is a little bit confusing as the error is a case sensitive issue.

![image](https://user-images.githubusercontent.com/2329501/40729129-a0fc9c4a-6423-11e8-98cb-21607dd1c84f.png)

* What steps you took to make this happen,
use the code `Print("hello world")`
click **check**

* What you expected to happen,

**check** to say `Undefined name 'Print'`

* What actually happened,

**check** said `Undefined name 'print'`

* Why this difference is problematic (it may not be a bug!),

Because its confusing.

* Technical details like the version of Mu you're using, your OS version and
  other aspects of the context in which Mu was running. 

1.0.0.beta.15 Windows 10

Please remember to attach a **copy of the full log files for Mu**. You can get
the logs by clicking on the cog icon in the bottom right of the editor window.
Click on the logs and use CTRL-A to select all, then CTRL-C to copy and CTRL-V
to paste the contents into the issue.

Thank you for contributing to Mu! :-)

**Comment by ntoll** [comment]
Ouch... that's a good catch. The problem was a "spare" `.capitalize` on the message string. It appears "capitalize" doesn't just capitalize, but also lower-cases everything else. Fixed in #d2ef1632ad7ef2319bffec967b788b179fa8f76d.
