### ISSUE TITLE
Any Pane/panel: Changing "selected" state resets its size

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#490]
This might be an bug with the macOS version of PyQt5, similar to https://github.com/mu-editor/mu/issues/460, could somebody in other OS try to replicate?

The issue is that when the debugger pane changes from "selected" to "not selected" it also resets its size to the original size. The GIF below show show it better:

![mu_panel_resize](https://user-images.githubusercontent.com/4189262/41596213-7822ba40-73c1-11e8-894c-6e8eb2bf7be5.gif)

**Comment by ntoll** [comment]
I can confirm this happens on Linux. Taking a quick look at the code (see, https://github.com/mu-editor/mu/blob/master/mu/interface/editor.py#L279 -- which is where the interface is updated when a button-click in the debugger causes a change of state) this could be a bug in Qt. :-/

**Comment by carlosperate** [comment]
But that bit of code is about the editor itself, where is the debug inspect pane size set in the first place? I haven't been able to find it on a quick pass at the code.

**Comment by ntoll** [comment]
That's because I think (IIRC) we just let Qt do the "default" settings.

**Comment by carlosperate** [comment]
Right, it's only a small annoyance at the moment. Should we leave this open until the next release of qt, or until we find a bug report in their tracker?
This is low priority, so could be left in the backburner.

**Comment by carlosperate** [comment]
Just to note that the same thing happens with the micro:bit (and I assume other modes) REPL pane when the editor content is modified:

![pane](https://user-images.githubusercontent.com/4189262/42321961-81e52dc2-8052-11e8-8680-5ce7d91b6bfd.gif)

In this case I am still using PyQt5 5.10, but I think 5.11 is out in PyPI already, so we could re-test all this in that version whenever we find a chance.

**Comment by carlosperate** [comment]
I can confirm this still happens in PyQt5 5.11.

**Comment by ZanderBrown** [comment]
This only seems to happen when you interact with QScientilla everything else is fine so i would suggest any upstream bug would be with that not QT

**Comment by ZanderBrown** [comment]
Not running against 5.11 but I'm seeing this on Fedora

**Comment by ntoll** [comment]
I can reproduce this with Qt5.11 on Linux. Since this appears to be an upstream bug, all I can suggest is:

* Is this already reported?
* If not, we should report it.
* If it is we should add comments to make it more visible.

**Comment by bddicken** [comment]
Figured I'd chime in:

I teach intro CS and recommend Mu to my students. I recently did a section on debugging, and this issue is rather annoying when presenting the debugger to students. Perhaps it is a Qt issue, but it would be great to fix this sooner than later.

**Comment by carlosperate** [comment]
I can confirm I could not replicate this in macOS Mojave with PyQt 5.12.1 nor with PyQt 5.13.2.

If somebody could confirm this is not an issue in any of the other platforms I think we can close this one.

**Comment by ZanderBrown** [comment]
I don't see it (5.15)

**Comment by carlosperate** [comment]
Thanks @ZanderBrown, I assume that was on Linux, which was the other platform identified here with the original issue, so we can this one 👍 
Thanks everyone!
