### ISSUE TITLE
Breakpoints from different tabs are merged when debugger is started

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#493]
When setting breakpoints in different tabs they all are "activated" when the debugger is launched.

GIF for clarity:

![breakpoint-merge](https://user-images.githubusercontent.com/4189262/41614114-7cfe7d46-73ef-11e8-8b02-e12aac3cf1f6.gif)

**Comment by ntoll** [comment]
Doh. I AM AN IDIOT. Should be easy to fix.
