### ISSUE TITLE
Detect blocking / dead / infinite loop in debugger child process.

### ISSUE THREAD

**Issue by ntoll** [mu-editor/mu#496]
See #494 for context.

I think we could attempt to detect that the script is blocking (for example, by adding a time-out for responses from the child process). If the response comes back, the timeout is cancelled. If the timeout is hit, all debug related buttons except for stop (which will kill the child process and clean things up) are disabled.

**Comment by tmontes** [comment]
PR #924 just raised to address this.

**Comment by tmontes** [comment]
Just merged #924, addressing this. Closing.
