### ISSUE TITLE
mu microbit gesture "shake" not work

### ISSUE THREAD

**Issue by piramid** [mu-editor/mu#501]
micro python  in BBC micro bit function accelerometer.is_gesture("shake") not work

**Comment by ntoll** [comment]
Please report this to MicroPython with some example code so the maintainers can reproduce the problem: 

https://github.com/bbcmicrobit/micropython

cc/ @dpgeorge

(Mu is just a code editor for writing MicroPython code on the micro:bit... the problem you have is with MicroPython itself.)

Hope this helps. :-)

**Comment by dpgeorge** [comment]
This question has been asked before, and the problem may be the same as discussed in https://github.com/bbcmicrobit/micropython/issues/448

**Comment by piramid** [comment]
On MAC OS is work but on Windows OS not work (mu-editor-beta16_win64.exe) . only **accelerometer.is_gesture("shake")** not work
code:
from microbit import *
while True:
    if accelerometer.is_gesture("up"):
        display.show(Image.ARROW_S)
    elif accelerometer.is_gesture("right"):
        display.show(Image.ARROW_E)
    elif accelerometer.is_gesture("down"):
        display.show(Image.ARROW_N)
    elif accelerometer.is_gesture("left"):
        display.show(Image.ARROW_W)
    elif accelerometer.is_gesture("shake"):
        display.show(Image.SAD)
    else:
        display.clear()
    sleep(20)

**Comment by dpgeorge** [comment]
@piramid that's very strange that it works on Mac but now Windows.  That doesn't sound right, it should work or not, the OS doesn't matter.  The only thing I can think of is that the versions of the micro:bit MicroPython that come with the different mu's for different OS's are different.  But anyway, as mentioned above, please discuss this here: https://github.com/bbcmicrobit/micropython/issues/448
