### ISSUE TITLE
accelerometer.is_gesture("shake") not work

### ISSUE THREAD

**Issue by piramid** [mu-editor/mu#506]
micro python "mu-editor-beta16_win64.exe" in BBC micro bit function accelerometer.is_gesture("shake") not work

**Comment by ZanderBrown** [comment]
Word for word duplicate of #501.

I assume you missed your original issue because it has been closed as it's related to micropython itself not Mu, the issue is being discussed upstream at https://github.com/bbcmicrobit/micropython/issues/448

**Comment by carlosperate** [comment]
Closing as a duplicate of #501, and there are other linked discussions covering this topic.
