### ISSUE TITLE
Materialize code blocks scope

### ISSUE THREAD

**Issue by gquintana** [mu-editor/mu#508]
While explaining Python to teenagers, I had hard times trying to explaining why they should indent code and where they should indent code.

I would find it very useful to visually represent the scope of a code block: "this if statement starts here and finishes here", "this while statement starts here and ends here". It would allow visually checking whether code is properly indented/aligned.

Yet I have no idea whether Scintilla has such a feature.

**Comment by gquintana** [comment]
https://www.scintilla.org/ScintillaDoc.html#TabsAndIndentationGuides

    "Scintilla can also display indentation  guides (vertical lines) to help you to generate code."

**Comment by ntoll** [comment]
Mu already does this!
![indent_lines](https://user-images.githubusercontent.com/37602/41840707-502044bc-785e-11e8-96d4-16b069066999.png)
