### ISSUE TITLE
macOS, annoying messages after upload to micro:bit

### ISSUE THREAD

**Issue by sstaub** [mu-editor/mu#515]
v1.0.0b16

Using micro:bit with macOS 10.13.5

After each upload to the micro:bit you get the same annoying message,
that you unmount the device not correctly. (see german screenshot)
That is a macOS problem which can solved by uploading the code
via CMSIS-DAP instead using MSD, I think.
I have had the same problem with other mbed devices using PlatformIO,
and it was solved with this method.
Hope you can do it also by this way.

<img width="430" alt="screenshot" src="https://user-images.githubusercontent.com/6450325/42041437-3352362e-7af2-11e8-9925-c2451196ff84.png">

**Comment by jaustin** [comment]
@sstaub this behaviour should be fixed (well, more accurately worked around) by the new flashing flow that's been integrated by ntoll in beta17. Could you try that out and confirm that on your machine the dialog is gone (possibly you will still see this for the *first* flash as we have to get the latest version of MicroPython on your board, but after that I hope subsequent flashes would be without the message) - Download is here https://codewith.mu/en/download

**Comment by sstaub** [comment]
Yeah, it is working now.
