### ISSUE TITLE
Feature request: Indentation and commenting options

### ISSUE THREAD

**Issue by bazilione** [mu-editor/mu#516]
Atom and Sublime Text have convenient options (and keyboard shortcuts) for commenting and indentation. (for single and multiple lines at once.) On Mac after placing a cursor or selecting lines of code: Command + '/' (comment/uncomment) and Command + '[' and Command + ']' (for unindent/indent). 

It'd be great to have these capabilities in Mu. 

Best, Vasily.

**Comment by ntoll** [comment]
Hi @bazilione,

Good call. 

Mu already does the indent/un-indent trick: highlight the text with your cursor and use TAB (indent) or Shift-TAB (un-indent) to change things around.

As for toggling comments on and off... you're not the first to ask for this and I believe it'd be very useful. I'll see if I can get it into the next beta.17 release at the end of this week (feedback / testing would be really appreciated for this!).

Thanks for your contribution! N.

**Comment by ntoll** [comment]
OK... Ctrl-K is the key binding for toggling comments (`#`) on and off for all highlighted lines. :-)

It'll be in the beta.17 release by the end of this week.

**Comment by mossworks** [comment]
I gave this a shot, and I noticed that if there are any lines in the selected area that were already commented, Ctrl-K will uncomment them.  It seems to be inverting the commented state of each line, rather than strictly adding or strictly removing a level of commenting.

**Comment by bazilione** [comment]
Nicholas, Thank you for the reply and sorry for not getting back for so
long. Ctrl + K does not seem to work on my Mac for commenting lines. (It
deletes everything to the right from the cursor on the line.) Please
suggest a solution for indenting from the keyboard.
Thank you!
Vasily.

On Wed, Jul 4, 2018 at 6:43 AM, Nicholas Tollervey <notifications@github.com

**Comment by Minhtue997** [comment]
KUBET KUBET11.RENT là nhà cái đẳng cấp và uy tín số 1 châu Á. KUBET đang sở hữu hơn 5.000.000 thành viên. Mỗi ngày có hơn 600.000 lượt truy cập và 200.000 lượt tải app mỗi tháng. Trang chủ Kubet được tổ chức GEOTRUST công nhận an toàn và khuyến nghị người chơi nên tham gia. https://kubet11.rent/
