### ISSUE TITLE
Check Chinese translation.

### ISSUE THREAD

**Issue by ntoll** [mu-editor/mu#534]
This one's for @yonghuming -- the UI is now done, so please check and revise your Chinese translation. Thank you for your contribution and I'd love to get the changes in the release candidate at the end of the week! :+1:  :cow: :heart: :cn: :shipit:

**Comment by carlosperate** [comment]
Just a friendly ping @yonghuming, if you are happy to provide translations the Mu project is finally ready for translating again 🎉 

More info in:
- https://github.com/mu-editor/mu/discussions/1931

**Comment by carlosperate** [comment]
Chinese translation updated in https://github.com/mu-editor/mu/pull/2033, not much to do right now for this ticket, so I'll close it.
