### ISSUE TITLE
Translations and *.mo files

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#540]
I had to force add the .mo file into the #539 PR, as it looks like these files have been gitignored.
Without this file in the translations directory I wasn't able to force the spanish translation to load.

Does the gitignore file has to be edited to include them? Is there a different configuration I need to be able to run the translations from the *.po files only?

**Comment by ntoll** [comment]
Correct. the .mo are auto-generated and thus ignored in Git. However, I don't think this is the behaviour we want for the reasons you state. :-)

**Comment by ntoll** [comment]
See: fb644cd8d20d06a86a2cde91b1f5c985b36ddcef

**Comment by carlosperate** [comment]
Thanks Nicholas!
