### ISSUE TITLE
Style suggestion: Differentiate more the active tab

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#541]
I don't know if this happens to anybody else, but every time I have two tabs open I keep wrongly thinking that the active tab is the one with the darker shade.

Of course, a darker tab usually means it is not the selected tab, but I think my brain gets confused because the selected tab has the same colour as the rest of the window, and so the one that is more visible to me is the other one.

The other themes highlight the tab with a lighter shade, this problem doesn't happen to me when using those, only with the default theme:

![image](https://user-images.githubusercontent.com/4189262/42581813-83a0afd8-8525-11e8-9a64-126c2fcd80c9.png)

**Comment by ZanderBrown** [comment]
@ntoll we can easily change the colour but what would @carlosperate be looking for?

**Comment by carlosperate** [comment]
Thanks Zander! I'm not too bother as long as its different than the background colour and lighter than an inactive tab. Would a lighter shade of grey from the background colour be distinguishable enough?
You are pretty good with these things, so I trust your judgement here.

**Comment by ZanderBrown** [comment]
Thanks for your support!

Not quite sure where to go with this one, the shades are pretty close already.

Looking at the other themes and my comments I intended to use the border colour:
![screenshot from 2018-07-11 18-28-05](https://user-images.githubusercontent.com/17074021/42589360-9c598a46-8538-11e8-81ae-1640a0be4ec1.png)
but that would darken not lighten

The pure white approach might go nicely with the white text area:
![screenshot from 2018-07-11 18-32-52](https://user-images.githubusercontent.com/17074021/42589474-fa91e126-8538-11e8-9d77-749aa7e17cbd.png)

Or a lighter form of the focus colour:
![screenshot from 2018-07-11 18-36-46](https://user-images.githubusercontent.com/17074021/42589608-79a24d8e-8539-11e8-8075-d713b445eca4.png)

I'm largely in favour of the 3rd

**Comment by ntoll** [comment]
I'm with you @ZanderBrown on number 3.

I dunno about you, but this feels like choosing wallpaper... ;-)

**Comment by carlosperate** [comment]
Number 3 sounds like a winner, thanks Zander!

**Comment by carlosperate** [comment]
Thanks Zander and Nicholas! It's subtle, but it makes a big difference :)
