### ISSUE TITLE
Flash button greyed out when REPL button toggled on

### ISSUE THREAD

**Issue by SteveJSmythe** [mu-editor/mu#564]
Mu 1.0.0.rc.1
Windows 10

Sometimes you want to be able to view error messages in the REPL when flashing new code

**Comment by ntoll** [comment]
Hi @SteveJSmythe 

The new flashing method uses a serial connection. Therefore you can't have the REPL (which obviously also uses the serial connection) open at the same time. If you want to see output from a restart follow these steps:

* Flash the code
* Open REPL
* Press reset.

Voila..! I hope this makes sense.

:-)
