### ISSUE TITLE
Memory error - memory allocation failed

### ISSUE THREAD

**Issue by SteveJSmythe** [mu-editor/mu#565]
Mu 1.0.0.rc.1
Windows 10

The attached code generates the following error "Line 16 Memory Error memory allocation failed allocating 2816 bytes". No error is generated when flashing the same code using Mu 0.9.13. The program is test code for a dual 4x7-seg display with MAX7219 driver. 

As the program is quite long by micro:bit standards, it is possible that the new version of Mu just takes up slightly more memory than the old version and runs out of space.

[7-seg test no library with functions 2.zip](https://github.com/mu-editor/mu/files/2205154/7-seg.test.no.library.with.functions.2.zip)

**Comment by carlosperate** [comment]
Thank you for the report Steve!

I've opened https://github.com/bbcmicrobit/micropython/issues/535 in the MicroPython repository to track this issue over there, as this is to do with MicroPython, so I'll close this one.
