### ISSUE TITLE
Debugger - highlighted line goes over by 1 character

### ISSUE THREAD

**Issue by martinohanlon** [mu-editor/mu#571]
When you start the debugger, the highlighted line bleeds over in the next line by 1 character.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/2329501/42993643-cb36cd16-8c03-11e8-8892-036b3c73fa9b.gif)

I have seen this a couple of times now. It doesnt always happen, but I havent been able to work out what makes it happen!

**Comment by ntoll** [comment]
That was fixed in rc.1. See: https://mu.readthedocs.io/en/latest/changes.html#rc-1

(It was an ObOE caused by Windows newlines being `\r\n` rather than `\n` which meant the reported `len` of the line was one (invisible) character too many). :-)

**Comment by martinohanlon** [comment]
Thanks, I was just installing rc1 to see if it was fixed.

**Comment by ntoll** [comment]
Give me a couple of hours and (hopefully) 1.0.0 will be out. ;-)

**Comment by martinohanlon** [comment]
Damn it, Ill have to install 2 versions in 1 day!

**Comment by ntoll** [comment]
...and inevitably you'll find a bug. ;-)
