### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by osaatcioglu** [mu-editor/mu#598]
I like to congratulate all the contributors for such a beginner friendly IDE. I am occasionally helping beginners to get in to the development using Python and Mu Editor looks like the best available option. Kudos! :)

I started to do the Turkish translation. Please put this issue on me. And, if there are any other Turkish fellows, I will be happy to collaborate together.

**Comment by ntoll** [comment]
Hi @osaatcioglu. Thank you for your offer of help with the Turkish translation. :-)

**Comment by osaatcioglu** [comment]
Hi @ntoll, I am very happy to help. Unfortunately, it is taking a bit more time than I anticipated though. I am 60% complete and I hope that I can finish the first version by end of next week. :)

**Comment by libreajans** [comment]
Hi @osaatcioglu 

Hazırladığınız çevirileri son haliyle paylaşabilir misiniz? Eksik kalan kısımları topluluk olarak tamamlamaya çalışırız.

**Comment by carlosperate** [comment]
Hi @osaatcioglu and @libreajans, it's been a while, but if you are still happy to provide translations the Mu project is finally ready  🎉 

More info in:
- https://github.com/mu-editor/mu/discussions/1931

**Comment by carlosperate** [comment]
Hi @osaatcioglu and @libreajans, we'll synchronise translations in this discussion:
- https://github.com/mu-editor/mu/discussions/1931

To keep things tidy I'll close this issue, but if you can still provide a Turkish translation it would be really appreciated!
