### ISSUE TITLE
Please include a link to the Github repo on the download page

### ISSUE THREAD

**Issue by SpotlightKid** [mu-editor/mu#601]
Currently, to find the Github repo from the main website, you first have to

1. open the "Developers" menu
2. go to the documentation,
3. go to the "Developer Setup" section
4. copy and paste the Github repo link manually.

Please include a link to the Github repo on the download page and/or the "Developers" menu/page on the main website.

**Comment by ntoll** [comment]
Fixed in https://github.com/mu-editor/mu-editor.github.io.

Thanks for the heads up. The changes should be live by the time I've finished typing this reply. ;-)
