### ISSUE TITLE
UI becomes unresponsive when printing in a loop

### ISSUE THREAD

**Issue by martinohanlon** [mu-editor/mu#602]
If you run:

```python
while True:
    print("hi")
```

The UI will become unresponsive. 

It is normally possible to stop the program running but it is difficult to get focus to press stop and often Mu will hang.

Putting programs into infinite (or very long) loops and output data is a common practice amongst new learners to look and something which should probably be catered for.

Fyi - I have only tested on Windows.

**Comment by martinohanlon** [comment]
Thanks for the explanation

**Comment by ntoll** [comment]
Fixed in 3d50b15

**Comment by ntoll** [comment]
This'll be in the 1.0.1 release coming in the next week or so. :-)
