### ISSUE TITLE
Help button leads to a wrong page

### ISSUE THREAD

**Issue by pintman** [mu-editor/mu#605]
Pressing the Help-Button in Mu-Editor version 1.0.0 leads to a "page not found" page 

https://codewith.mu/de/help/1.0

**Comment by ntoll** [comment]
Yup... this is because there is no German help (yet). In the meantime it's supposed to redirect to the English version. This will need some Jekyll configuration over in the https://github.com/mu-editor/mu-editor.github.io repository.

Thanks for reporting!

**Comment by ntoll** [comment]
This has been now fixed on the website (the redirects are no in place to point people to the English versions).

**Comment by pintman** [comment]
Thanks for the fast support. :)
