### ISSUE TITLE
Run panel does not remember its position/size

### ISSUE THREAD

**Issue by malbarbo** [mu-editor/mu#614]
To reproduce run some code. Then resize (or attach to left of right) the run console panel. Then stop the running code. The next time the code is run the panel show in the original position. I would expect that the position to be remembered and the panel opens in the last position.

**Comment by carlosperate** [comment]
We had some discussion about this area in this thread: https://github.com/mu-editor/mu/issues/553#issuecomment-407794074

I think at the moment we are inclined to save zoom state, but not the panel size/position.

**Comment by malbarbo** [comment]
I see. The issue here is bad when the screen monitor has more horizontal than vertical space. Think a 16:9 screen with top an bottom panel, splitting the mu editor vertically leaves the editor and run console too small, splitting horizontally temporally fix the problem, but it appears when the code in run again.

**Comment by ntoll** [comment]
Fixed by Fixed by  5b82f22
