### ISSUE TITLE
create hard links

### ISSUE THREAD

**Issue by parisni** [mu-editor/mu#634]
This is a feature request.

> mu find  --format=links "my query"

The above command creates **symlinks**. However I guess being able to create **hardlinks** would be usefull specially if one want to modify the email after a search (say tag, delete and so on)

So what about providing the below:

> --format=hard-links

**Comment by ntoll** [comment]
Hi @parisni,

Umm, I think you maybe in the wrong "mu" repository. This is "mu" the code editor. Perhaps you're thinking of another "mu"? The command you reference is nothing to do with `mu-editor` (the command used to launch the editor).

All the best,

N.

**Comment by parisni** [comment]
sorry for that I was looking for https://github.com/djcb/mu/
thanks for putting me right
