### ISSUE TITLE
Fix OSX automated build to use latest version of briefcase.

### ISSUE THREAD

**Issue by ntoll** [mu-editor/mu#664]
The path which the portable Python is unzipped to is different due to a change in the way briefcase works. It means the current automated builds of the OSX app don't work. I've reverted the version of briefcase we use to a known working version, but we should update our build scripts to work with the latest version.

**Comment by tmontes** [comment]
...I guess this is no longer true and can be closed, correct?

**Comment by ntoll** [comment]
Yup :-)
