### ISSUE TITLE
messages.pot file created is empty

### ISSUE THREAD

**Issue by erdincmutlu** [mu-editor/mu#668]
When I run make translate the pot file is empty, i.e. only has
```
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION'
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2018-10-10 11:37+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=cp1252\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
```
I can see while running it is putting strings into the file, but finally, it is empty. 

I am using Anaconda on windows. 
I am using the latest commit f89fc697ca67df9f71447b7f75aae521e4882fff

**Comment by carlosperate** [comment]
Hi @erdincmutlu, it's been a while, but  the system that regenerates the pot files has been updated to use the babel package, so hopefully it should work better now. Instructions can be found in the docs: https://mu.readthedocs.io/en/latest/translations.html

If you would want to submit a translation that would be fantastic too! We are currently going through the process of updating translations, more info here: https://github.com/mu-editor/mu/discussions/1931
