### ISSUE TITLE
Cannot change indentation to tabs

### ISSUE THREAD

**Issue by fake-name** [mu-editor/mu#673]
* What you were trying to do,

Indent code using tabs

* What steps you took to make this happen,

1. Open Mu
2. Try to find indentation settings.

I'm aware that the python style guide/pep-8 specify indenting with spaces, but as far as I'm concerned, this is one of the very few major mistakes in the python design community.

Anyways, arguing about what indentation is "correct" is a lost cause, and basically opinion based, but I'd expect to be able to at least *change* it to tabs.

Currently, I've ~~hacked~~ "Fixed" it by just editing `editor.py` directly and changing `setIndentationsUseTabs(False)` to True, but that's a less then ideal solution, since updating the package will clobber my changes.

**Comment by ntoll** [comment]
@fake-name hi, thanks for your suggestion. This isn't going to happen since we follow the Python style guide. Furthermore, we "bake in" such settings as it means there's one less thing for beginner's to have to think about. Sorry. :-(
