### ISSUE TITLE
Feature - where is plotter?

### ISSUE THREAD

**Issue by rhubarbdog** [mu-editor/mu#714]
The screen shot at codewith.mu shows a copy of mu with a plotter button.
Is there a version with a plotter?
Is there any documetation and examples of graphing data?

**Comment by wayoda** [comment]
There is a [Tutorial for the Plotter](https://codewith.mu/en/tutorials/1.0/plotter) on the[Code with Mu Tutorials](https://codewith.mu/en/tutorials/) page.

**Comment by wayoda** [comment]
Sorry, I never installed it on an RPi. Can't help on this one.

**Comment by ukBaz** [comment]
There are issues with the plotter on an RPi. See:
https://github.com/mu-editor/mu/issues/689#issuecomment-433419161

**Comment by carlosperate** [comment]
We are going through the process to create PyQtChart (the library that provides the plotted) deb packages, which can then be submitted for inclusion in Debian and/or Raspbian.

Issue  https://github.com/mu-editor/mu/issues/441 is the current thread discussing this work, so I'll close this one as a duplicate. Thanks @wayoda  and @ukBaz for all your help as well.
