### ISSUE TITLE
loss of keyboard focus when closing REPL

### ISSUE THREAD

**Issue by Linguini2004** [mu-editor/mu#715]
If you are reporting a bug, we would like to know:

I was using the REPL and on closing the REPL the keyboard focus had shifted onto the tabs and therefore I had to click back on the text to edit it. I expected to be able type straight into the text area after using the REPL instead the keyboard focus was on the tabs. This isn't a big issue but gets in the way of using the REPL

**Comment by tjguk** [comment]
Fixed in release 1.0.2 via PR #716
