### ISSUE TITLE
Duplicate Tab Name

### ISSUE THREAD

**Issue by tjguk** [mu-editor/mu#722]
This is quite tentative, but I definitely saw it happen; only I was moving quite fast with a beginner and didn't have time to stop and debug.

In some circumstance, we saw the filename from one tab appear on another. ie BEFORE: [abc.py], [def.py]; AFTER [abc.py], [abc.py].

I *think* it was just after the user (accidentally) set a breakpoint by clicking in the gutter before resetting it by clicking again. That is, I can't think of any other unusual action which took place before I noticed the duplication.

**Comment by dybber** [comment]
This should now be fixed per #1063. Closing.
