### ISSUE TITLE
dev-setup: add `venv` to `.gitignore` 

### ISSUE THREAD

**Issue by wayoda** [mu-editor/mu#737]
This relates to the developer setup on Linux (Ubuntu 18.10)

I cloned the mu-repo and installed the virtual environment into `venv`.

When running `git status` it will report `venv` as an `unversioned file`. `venv` should be ignored by `git` just as `env` and `.env` are already. The Makefile targets expect the virtual environment to be in `venv` so installing the virtual environment  into `env` instead is not an option.

So the request would be to add `venv\` to `.gitignore` to get rid of the message (and allow to use the `git add .` shortcut again.  

Thanks
Eberhard

**Comment by carlosperate** [comment]
Thanks for the request @wayoda!
.venv has been added to the .gitignore file as part of https://github.com/mu-editor/mu/pull/862: https://github.com/mu-editor/mu/blob/a4d7288bb5ba412e508bef86126e9db652b8e7ef/.gitignore#L82
