### ISSUE TITLE
wrong version number in portamu_1.0.2_osx.zip? 

### ISSUE THREAD

**Issue by suschizu** [mu-editor/mu#744]
I think you forgot to update the version-number for the last release - I downloaded version 1.0.2 but get the info that it's still v1.0 (portamu_1.0.2_osx.zip)

**Comment by ntoll** [comment]
Aha... thank you... I'll check.

**Comment by ntoll** [comment]
Ahh... OK thanks. I'll look into it.

**Comment by core-code** [comment]
i can confirm the issue. version 1.0.2 claims its actually version 1.0 when selected in the macOS Finder

**Comment by carlosperate** [comment]
Thanks for the report @suschizu.
As this is the same issue as https://github.com/mu-editor/mu/issues/925 I'll this issue to keep things tidy, as we have a bit more info in that issue. Please do reopen this issue if it's not the same or if we should keep them separated.
