### ISSUE TITLE
Debugger run prints to output panel a logger.warn

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#751]
Tested on macOS, on release 1.0.2.

When running the debugger it prints to the panel this logger entry:
https://github.com/mu-editor/mu/blob/3cb427fdfe09cf8b2ea0b75db763da424814b60d/mu/interface/themes.py#L50

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/4189262/51976134-d7b43680-247b-11e9-93b4-4f1ecccfcd0f.png">

**Comment by ntoll** [comment]
@carlosperate I cannot recreate this on my Mac. I'm running on OSX 10.13.6.

**Comment by carlosperate** [comment]
My version of macOS is 10.14.2 (Mojave).

I was able to recreate this with the app bundle downloaded from the website and also running from master branch. Perhaps this is some kind of global setting or environmental variable? I don't think I've set up anything like that for Python, but something to look into.

**Comment by carlosperate** [comment]
I also tested this on @microbit-giles macOS 10.14.2 Mojave laptop with Mu 1.0.1 from the official installer and it shows the same message in the debugger terminal.

**Comment by carlosperate** [comment]
Still an issue in the current master branch:
<img width="952" alt="image" src="https://user-images.githubusercontent.com/4189262/97237394-ea89a580-17de-11eb-8c7d-ee6fc265b1a9.png">

**Comment by carlosperate** [comment]
Fixed via https://github.com/mu-editor/mu/pull/1165
