### ISSUE TITLE
wrong Circuitpython Umlaute äöüß

### ISSUE THREAD

**Issue by Tasm-Devil** [mu-editor/mu#759]
The german Circuitpython-translations aren't displayed properly in the MU-Terminal. 
The encoding is wrong (not UTF-8)
`ZurÃ¼ckverfolgung (jÃ¼ngste Aufforderung zuletzt)` should be `Zurückverfolgung (jüngste Aufforderung zuletzt)`

It is a MU problem because the terminal-program _screen_ shows it correct.

https://github.com/adafruit/circuitpython/issues/1112#issuecomment-460053098

**Comment by carlosperate** [comment]
Thank you for the report @Tasm-Devil, this is still a know issue we are planning to resolve soon, thanks for all your patience.

I hope you don't mind I'll close this ticket in favour of #797 as I'll try to unify all the open issues for this problem there.
