### ISSUE TITLE
UI/UX | Mode button vs. current mode indicator

### ISSUE THREAD

**Issue by tmontes** [mu-editor/mu#761]
## Context

I've been using Mu recently, more and more, while preparing an introductory programming workshop for kids. One of the things I've been trying really hard is to "step into their experience level" as much as possible. From that, I have found a few UI/UX issues I think can be improved.

## The issue

The mode button vs. current mode indicator window locations: the former is a nicely drawn button, on the top-left of the window, the latter is a discreet text string, on the bottom right. They're on completely opposite "locations" within Mu's window.

![mu-ui-study-0](https://user-images.githubusercontent.com/1912206/52219076-d9bf3080-2893-11e9-8979-7991b05f026a.png)

While I'm not sure how often Mu users will/would/do change modes throughout a session, I do believe that we can do better in this area.

## Proposal (for discussion, of course!)

The mode button should become the current mode indicator as well. The idea would be for both its icon and label to dynamicaly change, indicating the currently active mode (and freeing up the status bar that, in my perspective, is not 100% beginner friendly).

I thought about this lot, did my prayers to the Pixels Gods, and mocked up a few ideas here:

![mu-ui-study-proposal](https://user-images.githubusercontent.com/1912206/52219602-e09a7300-2894-11e9-909d-77c20f1b5f50.png)

Notes:
* An obviously missing possibility would be just having the mode button assume the icon for the current mode. But I didn't feel like throwing away the beautiful, inspiring, and very familiar Mu icon with this change. :) Furthermore, a wider button leads to better support longer labels (see below), and a similar but different looking button may make sense to indicate that "this one is somehow different from the others".
* I went, thus, for a combination of the Mu icon along with the mode icon which would vary: such mode icons would be created from the ones in the current mode selection dialog, but single-coloured to visually match the aesthetics of the toolbar.
* The icons in the mode selection dialog should then be single-coloured as well for a fully consistent UI, helping relate the "selection" in the dialog with the "current indicator", in the toolbar button.
* The wording for each of the different modes might need some kind of "horizontal compression", let's call it. While "Python" and "micro:bit" feel short enough, I'm not so sure about "Pygame Zero" or "Adafruit CircuitPython" -- would "PGZero" and "CircuitPython" do? Not sure at all... What about future modes? Longer labels could extend the horizontal space taken by such a mode button, leading to an excessively unbalanced "horizontal space per button". Not sure, but thinking out loud.

## Related thoughts

* Would using a drop down menu to select a mode instead of a modal dialog like we have today be a usability improvement? (such a drop down would look exactly like the current mode list in the modal dialog: big, icons to the left, text to the right) I feel so, but would love to hear other people's perspectives and experience.
  * Inline with this proposal, a drop down menu would be "spatially" closer to the mode button/indicator on the top left.
  * It would require one less click and less mouse cursor movement.
  * It would conflict with the current "initial Mu setup" where users are asked for a mode, right from the start, which needs some thought.
* Should/could the mode selection list (in the current modal dialog or in any other way) omit "unusable" modes at any given moment? Why show the micro:bit / CircuitPython modes when no such device is available? More food for thought. :)

## Epilogue

I have more mode-related ideas up for discussion, but will refrain from dumping them all here. Let's try to keep this issue in focus, hopefully avoiding bike shedding too much... :) The gist is "mode button and mode indicator are too far apart", can we do better? How?

Waiting for other people's thoughts.

**Comment by ntoll** [comment]
Thanks you for your thoughtful suggestions. Here's some feedback and push-back. ;-)

In general the rule of thumb has always been to separate concerns in the UI, for all concerns to work consistently and for there to be one way to do things in the UI. Teachers especially have praised how everything is simple and consistent. So with this in mind... so far we have ensured:

* Buttons should just be buttons - we shouldn't also show state (which is always shown in the footer). However, I concede that the "theme" button breaks this rule as you toggle through the available themes.
* Our use of the footer apes how other IDEs work (e.g. VSCode) and is itself a common pattern for software in general. This fits with Mu's philosophy of being the "real thing" in simplified form. We are, in a sense, helping folks form the habit of where to look.
* The simple layout is: buttons let you do stuff, the editor is for code, the footer is for status and "other stuff" (e.g. the admin cog -- which most folks can ignore).

I'm also concerned this would be quite a big change given folks have already praised the simple layout we already have (thus breaking a bunch of educational resource others have already created) and we will be making the UI more complicated. The three tier UI pattern (buttons, code, status) is simple and easy for teachers to explain.

Having said that, I'm anxious that we remain open minded to suggestions and would welcome further discussion on these points, especially if such discussion can point to evidence or research which shows any suggested change improves upon what we already have (where "improves" means something measurable or based upon user feedback).

**Comment by tmontes** [comment]
Nicholas, thanks for taking the time to go over my ideas. :)

When I thought about this, it was very much tied to the "positive feedback improvement" I shared in #762, which I consider more important than this, UI/UX wise. At that time, wondering, maybe, that the two combined could represent an opportunity for simplification and, who knows, getting rid of the status bar (not that I'm proposing that!)... Maybe it could be a path towards UI simplification... Again, wondering, exploring ideas towards "you + your code" and nothing else to distract you. :)

Having said that:
* I understand and agree with the desire for full consistency: that's a key element in UI/UX.
* I do also agree with the "real thing" approach: that's also a fundamental aspect in the learning process (so there goes my back of mind wondering about getting rid of the status bar!) :)
* I still feel that there's some kind of inconsistency (for the lack of a better word) in the spatial relationship between the "mode changing button" and "current mode indicator"... But maybe that's just me and I currently have no ideas on how to improve that.

Related (maybe even crazier) thoughts:
* Do you have an idea of how often do users change mode during a given session?
* I'm thinking of a workshop scenario where kids may be doing a "Python" based project (say with the `turtle` module) and then a "Pygame Zero" one. Imagine they have both files open, each in its own editor tab.
* Today they would need to change mode every time they would want to run a different project.
* Would it be completely crazy for Mu to somehow remember (and restore) its mode per tab? Per file?
* If so, could the mode be displayed within each editor tab? Say "Python | squares.py" in one tab, and "Pygame Zero | race.py" in another?
* Am I overthinking things?
* Please have me shut up. :)

Again, thanks for taking the time to go over my thoughts. The intention is the best, I do hope you understand.

**Comment by tmontes** [comment]
* Discussion was useful.
* Exploration was interesting.
* Mu is not going in this direction.

Closing.
