### ISSUE TITLE
Enabled Raspbian third party packages install

### ISSUE THREAD

**Issue by martinohanlon** [mu-editor/mu#782]
I have been catching up with @bennuttall, @topshed and @MarcScott and have agreed that it is better to have this functionality available on the Raspberry Pi than not. Without it we disadvantage a subsection of mu's users unnecessarily.

The implementation of the "third party packages" feels like the right first step, its simple and consistent, and as with everything unlikely to be the final one. 

We are all keen to support and explore what could be done in the future to open this up to a wider set of users and support those who would want to install Python packages "system wide" (on any OS) but believe this is the right first step and we should remove the restriction stopping this functionality for Raspberry Pi users.

I have prepped a PR to undo the restriction, which I will raise shortly, hopefully you agree and we can progress. 

:)

**Comment by tjguk** [comment]
100% gratuitous comment: thanks to @martinohanlon and the others for taking this decision in a constructive way. It's hardly a big deal, but my own feeling is that this puts us in a better place re RPi support.

**Comment by ntoll** [comment]
+1
