### ISSUE TITLE
Add builtins to address Undefined Names

### ISSUE THREAD

**Issue by rdagger** [mu-editor/mu#788]
Would it be possible to allow adding terms to the linter? For example, Mu flags the MicroPython _const()_ method as 'undefined name'.

In Atom or VS Code, I use Flake8 which allows me to create a config file.  Adding builtins = const to the config file prevents warnings regarding _const()_.

**Comment by ntoll** [comment]
Good catch. Yes. This should be a thing. :-)

**Comment by dybber** [comment]
An alternative option might be to just add it for the specific modes, (micro:bit and ESP MicroPython modes), or do you see other use-cases for this?

**Comment by carlosperate** [comment]
For v1.1 let's add mode-specific keywords, and if we want to expose these via settings file we can do that for v1.2.

**Comment by devdanzin** [comment]
The keyword feature is already present, but:
* `const` wasn't added to MicroPythonMode;
* regex handling of flake messages regressed just like in #1161.

The trivial patch below fixes const. Any pointers to other content that should be added to any modes? We should also add a test that runs a real check so we spot any regressions, ` test_check_flake_with_builtins` mocks flake's message so it didn't catch it.


```diff
diff --git a/mu/logic.py b/mu/logic.py
index 0f8edcb..356b2ff 100644
--- a/mu/logic.py
+++ b/mu/logic.py
@@ -460,7 +460,7 @@ def check_flake(filename, code, builtins=None):
     check(code, filename, reporter)
     if builtins:
         builtins_regex = re.compile(
-            r"^undefined name '(" + "|".join(builtins) + r")'"
+            r"^.*\d undefined name '(" + "|".join(builtins) + r")'"
         )
     feedback = {}
     for log in reporter.log:
diff --git a/mu/modes/base.py b/mu/modes/base.py
index 29a5e0e..8e96c9a 100644
--- a/mu/modes/base.py
+++ b/mu/modes/base.py
@@ -384,6 +384,7 @@ class MicroPythonMode(BaseMode):
     force_interrupt = True
     connection = None
     baudrate = 115200
+    builtins = ['const']
 
     def compatible_board(self, port):
         """
```

**Comment by devdanzin** [comment]
The builtins_regex should also become a module-level constant, probably in config.py.
