### ISSUE TITLE
requirements_pi.txt does not exist

### ISSUE THREAD

**Issue by robmarkcole** [mu-editor/mu#812]
The dev [setup guide](https://mu.readthedocs.io/en/latest/setup.html) for pi references `requirements_pi.txt` which does not exist

**Comment by carlosperate** [comment]
After PR https://github.com/mu-editor/mu/pull/680 `requirements_pi.txt` is no longer needed, as environment markers are used in the normal `requirements.txt` and `setup.py`.

We should update this line from the docs:
https://github.com/mu-editor/mu/blob/0ce00a74a691290dc381f4ca6d67a9fb28a1b763/docs/setup.rst#L89

**Comment by carlosperate** [comment]
PR https://github.com/mu-editor/mu/pull/813 raised, thanks @robmarkcole!

**Comment by ntoll** [comment]
Fix merged.
