### ISSUE TITLE
ESP mode tries to import microbit.uart in microfs

### ISSUE THREAD

**Issue by ntoll** [mu-editor/mu#814]
This means it's impossible to GET files from the ESP board.

**Comment by carlosperate** [comment]
Proposed PR for this: https://github.com/ntoll/microfs/pull/14/

**Comment by dybber** [comment]
I guess this is solved?

**Comment by carlosperate** [comment]
Yes, as the microFs updates were added to Mu here: https://github.com/mu-editor/mu/pull/850/
And was shipped in v1.1.0-alpha.2.

Thanks @dybber!
