### ISSUE TITLE
Selecting previously searched text in dialog would make it easier

### ISSUE THREAD

**Issue by makermelissa** [mu-editor/mu#831]
I talked to Nick directly, but this is more of a feature request. The idea is that id you had previously searched for a term such as `tuba`, then the next time you brought up the dialog, the word `tuba` would be selected so that you could either just type a new term or modify the existing. Most editors do it this way, and I've been frustrated that Mu doesn't.

**Comment by ntoll** [comment]
@makermelissa should be in the next alpha release. Thanks to @ZanderBrown for fixing this.
