### ISSUE TITLE
Moved console jumps back to bottom

### ISSUE THREAD

**Issue by henrik2706** [mu-editor/mu#833]
When attaching the console to any other placement than bottom, this works fine. However, once you restart your program by hitting Run, the console jumps back to the bottom. It would have been lovely to be able to move the console to the right hand side of the window, and having it stay in place even when restarting a program.

**Comment by carlosperate** [comment]
Thank you for the suggestion @henrik2706, I think we'll end up going with the implementation proposed in https://github.com/mu-editor/mu/issues/1122#issuecomment-702454474.

I'll close this issue to keep things tidy, but please feel free to reopen if you'd still like to discuss this feature.
