### ISSUE TITLE
Deprecation Warning When Displaying Text On Screen in Pygame Zero Window

### ISSUE THREAD

**Issue by amos1969** [mu-editor/mu#838]
When I run code to display text on the screen in Pygame Zero Mode it gives a deprecation warning.

Code to reproduce:
```python
def draw():
    screen.draw.text("Hello", (50, 50))
```

Message:
`
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
/home/amos/mu/myvenv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py:943: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  collections.MutableMapping.register(ParseResults)
/home/amos/mu/myvenv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py:3226: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  elif isinstance( exprs, collections.Iterable ):

---------- FINISHED ----------
exit code: 0 status: 0
`

Running on Linux with Python 3.7.3 using Mu 1.1.0.alpha.1 from github.

If I run the Pygame Zero file using pgzrun on the command line I don't get the message, but it uses Pygame 1.9.6 rather than the reported 1.9.4.

Cheers
Dave

**Comment by ntoll** [comment]
Eyup @amos1969 can you please report this to PyGame/PyGameZero? This is something to do with *that* project, Mu is just the messenger in this case. Thanks!
