### ISSUE TITLE
ESP-mode REPL: Off by one in error-message line numbers. 

### ISSUE THREAD

**Issue by dybber** [mu-editor/mu#839]
Error messages reported when executing a file using the "Run" button in ESP-mode, are reported on line N+1, when error is on line N.

E.g. with an error on line 14, the following error is reported:
```Traceback (most recent call last):
  File "<stdin>", line 15, in <module>```

**Comment by dybber** [comment]
@ntoll: Do you remember why this newline was added:
https://github.com/mu-editor/mu/blob/master/mu/interface/panes.py#L309

**Comment by ntoll** [comment]
No. I believe it may be an un-wanted part of the "recipe" for putting the device into raw mode, copied from the microfs command. I'm up to my eyes in creating a new web mode for Mu, but once that's ready to be a PR I can tackle the "low hanging fruit" bugs in preparation for the alpha.2 release.

**Comment by dybber** [comment]
Okay, I think we should use one of the existing implementations for entering/exiting raw REPL (e.g. call the one in microfs.py), they include very specific timings and checks that all the right phases have passed, and I don't believe a newline here is necessary. I can look at it one of the next days.

**Comment by dybber** [comment]
Okay, the code in microfs is harder to reuse than I anticipated as microfs uses pyserial, and Mu uses QSerialPort which are incompatible.

**Comment by dybber** [comment]
I can see the reason for using QSerialPort to use Qt signals on incoming messages. Should I try porting the enter/exit raw REPL code from microfs.py or pyboard.py to use QSerialPort?

**Comment by carlosperate** [comment]
@dybber did #839 fix this issue?

**Comment by dybber** [comment]
Yes, this was fixed by #1017
