### ISSUE TITLE
Pasting Windows EOL formatted text causes double line spacing on reload

### ISSUE THREAD

**Issue by mavhc** [mu-editor/mu#85]
To reproduce:
1. In Mu type 2 lines.
2. Ctrl-a, ctrl-c
3. Paste into Notepad.exe
4. in Notepad, ctrl-a, ctrl-c
4. Paste back into Mu. appears normal
5. Save file, close file, reload file
6. File has double line spacing

**Comment by carlosperate** [comment]
Just tested this with the latest master, and #133 has fixed this issue as well.

**Comment by tjguk** [comment]
I can confirm that this is fixed in the current build (and probably long before!)
