### ISSUE TITLE
Serial port baudrate fixed in code

### ISSUE THREAD

**Issue by rosco-pc** [mu-editor/mu#865]
Trying to add a new mode to mu-editor for a new microcontroller ([propeller.parallax.com](http://propeller.parallax.com)). The serial port connection for the unofficial micropython port is set to 230400

The baudrate for the serial port in mu-editor is fixed in the code to 115200:

1. mu/interface/main.py (open_serial_link)
2. mu/modes/base.py  (FIleManager)

would it be possible to make this configurable in the mode?

**Comment by dybber** [comment]
Sorry for the delay in responding, some other changes were necessary to make this easy, but I've now made a pull request which makes it possible to do just that. See #1095
