### ISSUE TITLE
Not Detects ""Clones"" adafruit

### ISSUE THREAD

**Issue by tcpipchip** [mu-editor/mu#866]
If your board is not the original adafruit board,
![image](https://user-images.githubusercontent.com/11488460/60035281-d5e54c80-9682-11e9-925c-91d22610b188.png)
Not detects the Board!
For example, i ported CircuitPython to u-blox module (NRF52840), but the mu editor not detects it (only the Mass storage), not the serial
![image](https://user-images.githubusercontent.com/11488460/60035365-0af19f00-9683-11e9-8776-ccabe5472f99.png)
My board opens as mass storage, mu-editor identifies it sucessfully! I can write and read python files.
My boards create a virtual comm! The mu-editor can see it but cant open it, i think that reads a PID value for the serial.
![image](https://user-images.githubusercontent.com/11488460/60035532-6f146300-9683-11e9-90b6-7902c86a6303.png)

**Comment by ZanderBrown** [comment]
Mu whitelists devices for the Adafruit/CircuitPython mode

https://github.com/mu-editor/mu/blob/acf9cb00893d776b5fe52d1c8c4fb9ab04c48503/mu/modes/circuitpython.py#L38-L51

I suspect your device isn't in that list, if it is compatible I suggest opening an PR

**Comment by carlosperate** [comment]
@tcpipchip as @ZanderBrown the board VID and PID are included in the Mu source code to identify the compatible boards. If you have any board you'd like to add you can create a PR to add that.
Thanks!

**Comment by tcpipchip** [comment]
I use the Adafruits! Thanks!
