### ISSUE TITLE
EP2019 BD | Webmode fails when file saved elsewhere

### ISSUE THREAD

**Issue by tmontes** [mu-editor/mu#890]
### Observed behaviour

* Jinja2 exception rendered in the browser.

### Expected behaviour

* The "hello" page should be displayed in the browser.

### Steps to reproduce

* Start Mu.
* Change to web mode.
* Create a new file and immediately save it under, say, `~/Desktop`.
* Click the Run button.
* Click the Browser button.

A ** jinja2.exceptions.TemplateNotFound** page is displayed.

### Notes

Verified both on macOS and Windows 10, running from source.

PS: Might be related to a very odd behaviour we observed with André at the Beginner's Day. I have asked him to run a few tests to help out diagnose his particular case and invited him to join the discussion here.

**Comment by seantibor** [comment]
I think I just duplicated this issue with #923. Seems like it's because the template files are only copied over when the mode changes, not when the working directory path changes.

**Comment by dybber** [comment]
I just created a file in my `mu_code` with the default content when creating a file in web-mode, and I get the same error. I don't have an `index.html` in the `mu_code/templates` directory for some reason.

**Comment by ntoll** [comment]
PR with fix in #1695
