### ISSUE TITLE
ui is quite small

### ISSUE THREAD

**Issue by ak-is-rolling** [mu-editor/mu#921]
i just installed MU on my surface pro 6
i was about use it as it use it at school but in school the ui seems to be alot bigger than usal.
it not too bad but its a bit annoying and it hurts after long time sqwinting at it[
![Annotation 2019-09-23 201638](https://user-images.githubusercontent.com/55714635/65455418-19488600-de3f-11e9-96d5-7b38de744bad.png)
](url)

many thanks 
Alex

**Comment by ZanderBrown** [comment]
In school being:

A) A different device
B) The same surface, just in a different building

I'm also slightly confused, you say you have to squint (and in your screenshot it is quite small) but say the UI is "alot bigger"?

I seem to remember the Surface has a HiDPI display so it's possible we aren't scalling correctly

**Comment by ak-is-rolling** [comment]
A) different device
is there a way to change it 
it is just that it looked like this
![mu](https://user-images.githubusercontent.com/55714635/65457580-cf15d380-de43-11e9-8784-2d7ecaff9b62.gif)

**Comment by ZanderBrown** [comment]
So the Surface is a misdirect :-)

I know that GIF is from the website, I'm assuming your screenshot is from the school device.

What can you tell us about the school device?

**Comment by ak-is-rolling** [comment]
the screen shot is the surface. the gif is what i usually expect at school. we have basic hp nuc's, i expect nomore than a pentium. i think the moniters are 1920 x1080 p.

**Comment by ZanderBrown** [comment]
Okay no I'm really confused, it the problem at school or on the Surface

It _sounds_ like your having a problem at school but based on that screenshot there's an issue on the Surface

**Comment by ak-is-rolling** [comment]
the surface

**Comment by ZanderBrown** [comment]
School was the mislead this whole time?? That's a plot twist :-)

So the problem is that the buttons are _smaller_ than they should be on the Surface?

If so I return to my earlier hypothesis that we aren't handling HiDPI properly

**Comment by ak-is-rolling** [comment]
im sorry about that. im amsuming that HiDPi means somehting to do wiht the high pixel denisty of the screen. would this be something looked into for next release or not?

**Comment by ZanderBrown** [comment]
Well given how increasingly common HiDPI is it would be something to prioritise really

Yes, HiDPI or "high DPI" is where a display has an especially high pixel density, as happens when you have a high resolution display in a small size (such as on the Surface)

**Comment by ntoll** [comment]
Hi folks... I love the epic thread you two are having... :-)

@ak-is-rolling we hope to have a way to configure icon sizes and other UI-ish things in the next alpha. It currently exists as a "draft" solution on my hard drive. I need to clean it up and let folks like @ZanderBrown test it and suggest changes.

It's coming.

**Comment by ak-is-rolling** [comment]
thank you so much@ZanderBrown @ntoll for both helping with querrie. its good to knwo there is a good community out there. i will be using this to carry on my education on coding as it is so easy and usefull. i will wait patiently for the update to come.
thanks once again 
Alex

**Comment by codescrawl** [comment]
I can chime in on this one as I have a surface pro 6 as well and just happened to install Mu myself today. The font size for the code editor is spot on for me on a default installation. Zooming in and out work just fine too. The problem only relates to the icons and the font underneath each at the top of the UI that don't appear to be scaled correctly. 
![Mu UI](https://user-images.githubusercontent.com/11361871/65551265-6ef16100-df19-11e9-8db7-dabc734704be.PNG)

**Comment by s-oldman** [comment]
Seconding this issue. If the latest alpha doesn't fully implement DPI scaling, that'd explain things.

Here's a screenshot from one of the new XPS 13 laptops [resolution is 3200x1800, DPI scaling set to 225%, OS is latest Win10 Pro x64 as of 2019-12-20 (v1909, build 18363.535)]:

![mu HiDPI screenshot 1 1 0-alpha2_win64](https://user-images.githubusercontent.com/5375059/71288172-52a66a00-2338-11ea-8a23-13bad66d5ae2.png)

That's on a screen size of 13". Can confirm that the label text does look quite small in person :)

**Comment by jesseh** [comment]
I had this issues and it resolved when I upgraded to the newest version of Windows 10 (OS build 19541).

**Comment by Saywa94** [comment]
Just installed Mu-editor on a surface pro 4. And the problem still persists. Any update on when a solution will be implemented?

Anyway, thank you for developing such an amazing app. It's actually pretty great for beginners.

**Comment by ronturcotte** [comment]
I ran into this same problem on a new laptop today and found this thread. It didn't give me a solution, but it did lead me to research HiDPI. Here's what I finally found that worked for me:
1. Right click on the mu icon and go to properties. Note: it took me a while to find this because it depends on where you're right-clicking. In my case, I ultimately put the icon in my task bar, right clicked on it there, then right clicked again on Mu in that pop up menu - then I finally found properties.
2. Click on the Compatibility tab.
3. Scroll down and click on the "Change high DPI Settings" button.
4. Here are the settings that worked for me 
- check the box under Program DPI (use these settings instead of system settings).
- under "Use the DPI that's set for my main display when," choose "I open this program"
- check the box under High DPI Scaling override and choose "System (Enhanced)" in the drop down menu.

![properties](https://user-images.githubusercontent.com/10792054/91922108-1edb5c80-ec9b-11ea-9f4b-d044675c0b03.jpg)

I hope this helps.

**Comment by carlosperate** [comment]
Thanks for the tip @ronturcotte! Having this workaround will be definitely be useful for people 👍

**Comment by dybber** [comment]
I've attempted to fix this through changing a few settings. Is anyone in this thread who are experiencing the problem, able to try out the pull request at #1150 and check if it works?

**Comment by dybber** [comment]
@ak-is-rolling @codescrawl @Saywa94 @ronturcotte, could any of you test this development version of Mu, where I've attempted to fix the issue? https://github.com/mu-editor/mu/actions/runs/413062770 

I don't own a Surface Pro myself, so I need someone to confirm that it's actually fixed.

**Comment by ak-is-rolling** [comment]
> @ak-is-rolling @codescrawl @Saywa94 @ronturcotte, could any of you test this development version of Mu, where I've attempted to fix the issue? https://github.com/mu-editor/mu/actions/runs/413062770
> 
> I don't own a Surface Pro myself, so I need someone to confirm that it's actually fixed.

ok i will install the new version of mu now and will come back to you

**Comment by ak-is-rolling** [comment]
> @ak-is-rolling @codescrawl @Saywa94 @ronturcotte, could any of you test this development version of Mu, where I've attempted to fix the issue? https://github.com/mu-editor/mu/actions/runs/413062770
> 
> I don't own a Surface Pro myself, so I need someone to confirm that it's actually fixed.

thank you so much it seems to be resolved now. the gui is now opening at the size expected. i appreciate the help.

**Comment by dybber** [comment]
Great, thanks for reporting in the first place and testing it now. The fix will be included in the next beta-release of Mu.
