### ISSUE TITLE
First time flash of micropython to get REPL not obvious

### ISSUE THREAD

**Issue by whaleygeek** [mu-editor/mu#93]
To use the REPL, I have to flash something micropython based onto the micro:bit first - the way to do this of course is to press NEW then press FLASH. You can then open the REPL and interact with the micro:bit. However this seems non obvious to new users.

**Comment by carlosperate** [comment]
The current [warning message](https://github.com/ntoll/mu/blob/af34dea53dbad427ae97272c08bec8c13bda9dce/mu/logic.py#L174-L178) indicates that MicroPython should have been flashed before REPL will work.

Is the main concern that the message is not clear, or that the most users will not really read it properly (which is a very valid concern)?

**Comment by whaleygeek** [comment]
This works. Thanks.
