### ISSUE TITLE
REPL text getting damaged on re-edit

### ISSUE THREAD

**Issue by whaleygeek** [mu-editor/mu#94]
If I type something into the REPL, press return to run it, then up arrow and edit it, and press return again to re-run the edited version - everything past where I press return gets deleted from the REPL window.

e.g.

> > > display.scroll("Hello nicholas")
> > > [up arrow and cursor to the n]
> > > display.scroll("Hello n^icholas")
> > > [change n to N]
> > > display.scroll("Hello N^icholas")
> > > [press return]
> > > display.scroll("Hello N
> > > [I see the above in the REPL window]

**Comment by whaleygeek** [comment]
This looks to be the same as #82

**Comment by ntoll** [comment]
Just checked... this is fixed in master. Closing.

**Comment by ntoll** [comment]
Thanks for the bug report, sorry it has taken so long to reply! :-)

**Comment by DavidWhaleMEF** [comment]
Thanks @ntoll !!
