### ISSUE TITLE
macOS Catalina | New packaging requirements?

### ISSUE THREAD

**Issue by tmontes** [mu-editor/mu#940]
Just saw this article passing through my regular RSS feeds:

* [Mac Python Distribution Post Updated for Catalina and Notarization](https://glyph.twistedmatrix.com/2019/10/catalina-notarize-python.html)...

Which essentially links to a Catalina updated version of a previous packaging article:

* [Tips And Tricks for Shipping a PyGame App on the Mac](https://glyph.twistedmatrix.com/2018/01/shipping-pygame-mac-app.html).

Both very well written by @glyph, clearly pointing to a "dragons ahead" warning WRT supporting macOS Catalina Mu users. The gist:

* New code signing requirement.
* Needs to be submitted to Apple, somehow.
* A new entitlements file seems to be needed.
* All executable files must now be signed.
* ...and more?

The article uses a different tool for the first packaging step (`py2app` where we use `briefcase`) but from a cursory read the signing / getting the packaged `.app` bundle ready for distribution seems tool agnostic.

PS: macOS Catalina has just been released, earlier this month. As time progresses, we can expect more and more Mu mac users to use Catalina. Actually, #936 is a report from a Catalina user -- wondering how Mu worked for the reporter, there.

**Comment by glyph** [comment]
Always nice to hear that my writing is proving useful to people!  Just a few minor notes:

> * Needs to be submitted to Apple, somehow.

The "somehow" are the `altool` and `stapler` invocations in the library - there's no out-of-band communication other than the email notifying you that you *can* run `stapler`.

> * ...and more?

This should really be it :)

> The article uses a different tool for the first packaging step (`py2app` where we use `briefcase`) but from a cursory read the signing / getting the packaged `.app` bundle ready for distribution seems tool agnostic.

Your reading here is correct.  The `zip` / `codesign` / `altool` / `xcrun` invocations are fairly agnostic to how the bundle was actually built; these ought to work with non-Python stuff, for that matter, as long as they happen to require that one extra entitlement that Python needs.

> PS: macOS Catalina has just been released, earlier this month. As time progresses, we can expect more and more Mu mac users to use Catalina. Actually, #936 is a report from a Catalina user -- wondering how Mu worked for the reporter, there.

Upgrade curves on new macOS releases are shockingly fast; you're likely to see a *majority* of users on Catalina in the not too distant future.

**Comment by tmontes** [comment]
Thanks for chiming in @glyph, and thanks for the article. We will soon fight this fight. :)

**Comment by glyph** [comment]
@tmontes  I’m interested to hear how it goes!

**Comment by tmontes** [comment]
A quick update + thought:

* Much progress has been made towards this -- see https://github.com/mu-editor/pup.
* Of course time (and Apple) does not stand still and now we're faced with macOS Big Sur.
* Once our dependencies (in particular Qt) handle Big Sur nicely, I wonder if `pup`'s efforts are enough...

:-)

**Comment by tmontes** [comment]
Closing this:

* Addressed in PRs #1234 and #1250, recently merged.
* Needs real-world testing -- but that's the next stage of the adventure. :-)
