### ISSUE TITLE
Strange stuff

### ISSUE THREAD

**Issue by WanyeKwest** [mu-editor/mu#949]
if nut == 1 
/\
 |
 |
Why does microbit say this is wrong

**Comment by ntoll** [comment]
Hi @WanyeKwest,

The code you shared isn't valid Python.

Also, you should seek support for these sorts of questyions from the micro:bit community -- you've created an issue for the Mu code editor (which obviously works with the micro:bit), but this is not a problem with Mu, per se. If Mu itself were broken, then we'd be all over it.

I hope this helps, sorry we can't be of more help and best of luck.

N.
