### ISSUE TITLE
Min max

### ISSUE THREAD

**Issue by JLFra** [mu-editor/mu#969]
Hello, in graph mode. You fixe min =-max. And that's create a problem reading the graph, because the signal is not so clear. So could you change the min and mut it to a real min and not -max. And them our students could really read signal from sensor. The actual accuracy off the graph is not correct. Because all signal don't have min=-max. thanks to help reading ours students.
Julien

**Comment by dybber** [comment]
I've added a pull request with a fix, which you might want to check out.

**Comment by dybber** [comment]
The issue should be fixed with the #1059 merged into master, which makes min and max y-coordinates on the graph independent of each other.
