### ISSUE TITLE
issue on windows install

### ISSUE THREAD

**Issue by machinehistories** [mu-editor/mu#994]
I ran into a few issues on the install of the latest release. I uninstalled the previous version and then I began the new installation. Perhaps there is a specific upgrade path that I didn't follow correctly. Many thanks for such a great tool I look forward to getting the latest release back up and running.

![e](https://user-images.githubusercontent.com/26831444/73428466-162e3c80-42ee-11ea-8ece-4b88d83886ba.jpg)

![f](https://user-images.githubusercontent.com/26831444/73428469-18909680-42ee-11ea-987e-f71f6b0b83e5.jpg)

![d](https://user-images.githubusercontent.com/26831444/73428456-12021f00-42ee-11ea-8f2e-a4dafef421ee.jpg)

**Comment by tmontes** [comment]
Interesting that the installer seems to be failing at writing the files in a directory to which you should have write permissions. I wonder if the files are somehow locked.

I know that Windows (at times?) prevents writing to files that are "in use". Maybe Mu is still running?

Suggestion:
* Ensure Mu is not running.
* Go to the Windows software uninstall panel and confirm Mu is not there. If it is, go ahead an uninstall it (maybe, once more). If not, disregard.
* Try installing again.

My 2c. :)

**Comment by ntoll** [comment]
This looks like file permissions on your machine -- i.e. Windows is not allowing Mu's installer to write to the location it references. :-/

I've uninstalled / reinstalled many times on my Windows machine and never seen this problem.

Perhaps you had the old version of Mu running (in which case it was using the referenced files and so you'd be stopped from overwriting them)..?

In any case, I'd reboot the machine (so you can be certain Mu isn't running, and delete the folder `c:\Users\jason\AppData\Local\Mu`. Then the installer should work.

Best of luck and please let us know how you get on..! :+1:

**Comment by ntoll** [comment]
Hah..! @tmontes that's exactly it.

I'm closing the issue because it appears to be a local configuration issue rather than anything to do with Mu per-se.

Please feel free to re-open if you don't think so, or we've missed something.
